### ISSUE TITLE
newsletter column

### ISSUE THREAD

**Issue by kartikey369-ind** [mdazfar2/Ezyshop#1]
hi @mdazfar2 ,

I hope this message finds you well. I would like to request the assignment of the task to add a newsletter column to our website. I believe I can effectively implement this feature to enhance user engagement.

Thank you for considering my request. I look forward to your approval.
if possible add lable for gssoc24-extd and hacktoberfest

**Comment by mdazfar2** [comment]
Hey @kartikey369-ind, thank you for raising the issue.

- Right now, we have decided to convert the code to Next.js so that we can add a backend in the future as well.

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me
