### ISSUE TITLE
[BUG] Add Hover Effects with Proper Transitions in all the Images when hovered over it

### ISSUE THREAD

**Issue by Sapta-Dev27** [mdazfar2/Ezyshop#10]
### Description

I would like to add proper Transitions and hover effects in all the images and boxes present in the project .

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hey @Sapta-Dev27 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me

**Comment by mdazfar2** [comment]
@lakshyeahh Hey @Kcode15, I will reopen the issue and mention you if there is a need in the future.
