### ISSUE TITLE
[BUG] Inconsistent card styling of newly generated cards after clicking load more button on categories pages

### ISSUE THREAD

**Issue by shivam8112005** [mdazfar2/Ezyshop#100]
### Description

CSS Not Applied to Newly Loaded Cards: When new cards are loaded, the associated styles (e.g., padding, borders, colors, or fonts) might not be correctly applied to the new elements, resulting in a mismatch with the already displayed cards

### Screenshots

![Screenshot 2024-10-03 210631](https://github.com/user-attachments/assets/4ee053c0-0021-4372-8602-db89198e94c8)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@shivam8112005, everything looks good. Please check again and raise an issue accordingly, which I’ll be happy to assign to you. Thank you!

![image](https://github.com/user-attachments/assets/0fc0dd41-c377-45c4-a6e6-060e1e23fd96)

- please ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
