### ISSUE TITLE
[Doc]: Update README

### ISSUE THREAD

**Issue by Pallavi-Mukalla** [mdazfar2/Ezyshop#1002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The README file is currently very long, making it difficult to quickly reach specific sections. Adding a table of contents would improve navigation.

### Suggested Change

I would like to add Table of contents for easy navigation.

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Pallavi-Mukalla As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
