### ISSUE TITLE
[Feat] Create Teams Page

### ISSUE THREAD

**Issue by inkerton** [mdazfar2/Ezyshop#1009]
### Description

This page is still shown under development I have checked No other issue resembles this. I would like to work on it .

Please assign me the issue.

Also please specify here You want the team as in the employees of ezyshop or the contributors. I can do both . So do clear this doubt of mine.

### Screenshots

![image](https://github.com/user-attachments/assets/623fa047-a4d7-41cd-abd7-53b96164cafc)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @inkerton, yes, we are considering adding a contributor page, and we already have a page on the navbar called `/Team`. When you click on `/Team`, you'll see the prompt for it. Actually, I want to update the contributor section on the team page to make it look more special, so I need some time for that. I will let you know if there are any updates for the team page. _Thank you!_
