### ISSUE TITLE
[Feat] No proper spacing between the icon and word shopping in the blog section.

### ISSUE THREAD

**Issue by TanishSen** [mdazfar2/Ezyshop#101]
### Description

Proper spacing is required between the icon and the words.

### Screenshots

<img width="106" alt="Screenshot 2024-10-03 at 8 23 21 PM" src="https://github.com/user-attachments/assets/e2c607d0-e347-4ccd-93dd-082658025bb1">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)
- [X] I'm a Hacktoberfest'24 contributor

**Comment by mdazfar2** [comment]
@TanishSen @TanishSen, everything looks good. Please check again and raise an issue accordingly, which I’ll be happy to assign to you. Thank you!

![image](https://github.com/user-attachments/assets/c12c79bc-b9c9-4f35-a210-d54f1c2b49ec)


- please ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
