### ISSUE TITLE
🚀 Automate Connections with GitHub Actions!

### ISSUE THREAD

**Issue by amiya-cyber** [mdazfar2/Ezyshop#1012]
We can implement github workflows for the following things:

Auto comment on issue Closed and Opened
Auto comment on PR mergs
Auto comment on PR raises
Using this workflows makes you'r repo more interactive ! 

please assign me and i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label
@mdazfar2

**Comment by mdazfar2** [comment]
Hey @amiya-cyber, can you add a workflow for the second issue raised? I mean, suppose you raise an issue, and after some time, you raise another one, then your second issue will be closed automatically. What I mean is that each person can raise only one issue at a time, and after completing that issue, the contributor can raise another one. Hope you understand. Please let me know if you can do it.

**Comment by amiya-cyber** [comment]
Yeah sure

**Comment by mdazfar2** [comment]
Alright! You are going to be assigned.
