### ISSUE TITLE
[BUG] Social media handles open in same tab, should open in new tab.

### ISSUE THREAD

**Issue by shahanxd** [mdazfar2/Ezyshop#1015]
### Description

Hi! The social media buttons, when clicked, should open in new tab.
![Screenshot 2024-10-28 125210](https://github.com/user-attachments/assets/a45280aa-241e-4ee3-86fd-c1a7573d1d6b)

This prevents the user from losing or steering away from Ezyshop easily.

Here is how the result would look like:

https://github.com/user-attachments/assets/6a3f6ef8-cbba-48bd-9614-aa65be622eaf

Please assign me this issue under GSSoC 24 Extd, thanks!

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [x] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by shahanxd** [comment]
@mdazfar2 I'd be happy to contribute by working on this issue :)

**Comment by mdazfar2** [comment]
@shahanxd Issue acknowledged! You are going to be assigned.

- Read our [Contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md) and contribute accordingly.

- Don't forget to give 🌟 to our repository.

- Follow us on [LinkedIn](https://linkedin.com/company/Ezyshopz).


***Thank you!***

**Comment by shahanxd** [comment]
Hi @mdazfar2 !

I have raised a pull request for this issue. Please have a look.
Also please add the the hacktober tag, if possible. Thanks!
