### ISSUE TITLE
Alignment Issue in "Secure Payments" Section of Facilities Card for Enhanced UI Performance

### ISSUE THREAD

**Issue by ansiace** [mdazfar2/Ezyshop#1016]
### Description

I have identified a misalignment issue with the **"Secure Payments"** section in the facilities card. The misalignment affects the visual coherence of the facilities card and reduces overall user experience.

#### Problem:
- The **"Secure Payments"** text or icon within the facilities card is not aligned properly, causing an unbalanced appearance.
- This may lead to a less polished and inconsistent visual experience for users.

#### Proposed Solution:
- Adjust the CSS properties to ensure the **"Secure Payments"** section is aligned consistently with other items in the facilities card.
- Test alignment adjustments for responsiveness across different screen sizes and devices.

### Screenshots

![Screenshot 2024-10-28 002122(1)(1)](https://github.com/user-attachments/assets/830559b3-478b-4aa6-b287-cddc0d76a005)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ansiace you are going to be assigned.

**Comment by Shazia-Ilme** [comment]
Hi! I am a participant in GSSoC '24, and I would like to work on this issue. Could you please assign it to me?

**Comment by mdazfar2** [comment]
> Hi! I am a participant in GSSoC '24, and I would like to work on this issue. Could you please assign it to me?



Sorry @Shazia-Ilme, please don't be discouraged, but this issue is already assigned to someone. Only one person can work on a single issue at a time. You can raise another issue, and I will be happy to assign it to you, but make sure that the issue you raise is valid and really needs to be addressed on our website; otherwise, invalid issues will be closed. **Thank you!**
