### ISSUE TITLE
[Feat]Add Multi-Language Support

### ISSUE THREAD

**Issue by Ankul8471** [mdazfar2/Ezyshop#1019]
### Description

Feature Summary
Add Multi-Language Support for Title and Description Generation

Description
Currently, the platform generates titles and descriptions in a single language, limiting accessibility for non-English speakers. Adding multi-language support will allow users to create content in their preferred language, making the platform more inclusive and user-friendly. This enhancement will broaden our reach to a more diverse audience.

Proposed Solution
Integrate a Translation API (e.g., Google Translate API, Microsoft Translator) to handle language translations for titles and descriptions.
User Language Selection: Allow users to select their preferred language through a dropdown or settings menu.
Automatic Translation: Once a language is selected, titles and descriptions are automatically translated to the chosen language.
Fallback Language: Set a default language (e.g., English) in case translation services encounter errors or if the preferred language is unavailable.

Alternatives Considered
Manual Translation: Instead of automatic translation, offer users an option to enter their own translated content manually. However, this approach requires more user effort and does not fully automate the process.
Static Language Packs: Use static language packs with predefined translations. This would limit the number of languages and flexibility in translations but could work for a smaller, fixed set of phrases.

Screenshots/Logs
No response

Additional Information
 I have searched for existing feature requests
 I am willing to help implement this feature
 I can provide more details or clarification if needed

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @coderKrysio,The website requires multilingual support for global usage, where it's understood that everyone knows English, with just minor adjustments.

If we need this feature in the future, we will definitely let you know.

Please don't be discouraged. I need to close your issue. You can raise another issue, and I will be happy to assign it to you, but make sure that the issue you raise is valid and truly needs to be addressed on our website; otherwise, invalid issues will be closed. _Thank you!_

**Comment by Ankul8471** [comment]
I understand about it but there are more than 50 languages in India alone and if someone visits this website and finds the option to view and work in the native or local language then it is helpful and satsfied him

**Comment by Ankul8471** [comment]
This is for user interaction and support only

**Comment by Ankul8471** [comment]
This is for user interaction and support only

**Comment by Ankul8471** [comment]
I hope you understand

**Comment by mdazfar2** [comment]
@Ankul8471Issue acknowledged! You are going to be assigned.

- Read our [Contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md) and contribute accordingly.

- Don't forget to give 🌟 to our repository.

- Follow us on [LinkedIn](https://linkedin.com/company/Ezyshopz).


***Thank you!***

**Comment by Ankul8471** [comment]
Thank you

**Comment by mdazfar2** [comment]
hey @Ankul8471 I hope you are doing well!

- It has been 2 days and you haven't responded to anything. Unfortunately, I have to close this issue because there are many duplicate issues raised. Please don't be discouraged. _Thank you!_
