### ISSUE TITLE
Enhancing the UI of Our facilities card

### ISSUE THREAD

**Issue by DevROHIT11** [mdazfar2/Ezyshop#1023]
### Description

I would to like Enhance the Ui of "our facilities" card by adding shadow effect , hover effect and many more......

### Screenshots

![Screenshot (70)](https://github.com/user-attachments/assets/12cdab87-272e-401f-a193-a53ae57db03d)

I would to like work on this issue please it to me ASAP.
thank you !!

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @DevROHIT11, as we are not decided to add any hover effect to our website, we will let you know if there's any work related to it. You can search for other issues/bugs and raise an issue accordingly. Thank you for raising the issue.
- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.

**Comment by DevROHIT11** [comment]
Ok no problem sirr 👍
