### ISSUE TITLE
[BUG] Privacy Policy page still in white color in dark mode

### ISSUE THREAD

**Issue by shreya2k3** [mdazfar2/Ezyshop#1025]
### Description

The Privacy Policy page is in white color even in the dark mode which doesnot look good

### Screenshots

![image](https://github.com/user-attachments/assets/180abc57-1297-478c-ae74-689629a53b93)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@shreya2k3 you are assigned.
