### ISSUE TITLE
[Feat] add 4th card to the trending deals section

### ISSUE THREAD

**Issue by AMRUTHA-BYSANI** [mdazfar2/Ezyshop#1026]
### Description

i would like to add a 4th card to the trending deals section in the empty space related to books to make it look more enhanced and for the user to have more options

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by AMRUTHA-BYSANI** [comment]
@mdazfar2 kindly assing this to me!

**Comment by mdazfar2** [comment]
Hey @AMRUTHA-BYSANI I don't exactly understand what you're trying to say. You described it in just two sentences, which doesn't clearly explain what you want to work on. Describe it well.
