### ISSUE TITLE
[Feat] Automation of project structure updation using GitHub workflows and Python scripts

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [mdazfar2/Ezyshop#1031]
# Description

Currently, the project doesn't have a **project structure**. And, it would be a bit difficult for newcomers to understand the project structure completely. Also, it's difficult for anyone to manually change the project structure as it grows in size day by day. So, automating this with GitHub workflows and Python script will make the maintenance easier.

I want to add a **detailed project structure** in a separate file(redirect in README.md) for the contributors to refer to and **automate its updation process** as new files are added in the projects. This will help them refer to the structure and will make it easier for them to understand.

# Screenshots

Sample of how the workflow would be automated and the project structure after updation in readme:
![image](https://github.com/user-attachments/assets/81e8ca29-70d3-421e-aabc-1a2e428f13d5)

![image](https://github.com/user-attachments/assets/0bc44243-5a2a-4e6e-8afc-e0dd9097515f)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@rajdeepchakraborty-rc go ahead.
