### ISSUE TITLE
Enhance Admin Login and Registration Pages

### ISSUE THREAD

**Issue by alienx5499** [mdazfar2/Ezyshop#1040]
This issue covers enhancements made to the Admin Login and Registration Pages to improve usability and aesthetic appeal:

Aesthetic Improvements:

Enhanced the admin login and registration interface with a modern dark theme for improved visual appeal.

Responsiveness:

Optimized the layout to ensure a seamless user experience across various devices.

Prisma Seed Data:

Updated the Prisma seed data to include richer blog post content and improved structural organization.

Objective: These changes aim to provide a better user experience for administrators, ensuring both functionality and aesthetics are at their best.

Labels:

hacktoberfest

gssoc-ext

@mdazfar2  please assign this issue to me

**Comment by Khushee21** [comment]
i would like to work on this project . Please assign it to me

**Comment by mdazfar2** [comment]
@alienx5499 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
