### ISSUE TITLE
[Feat] password is not shown 

### ISSUE THREAD

**Issue by Aditya90456** [mdazfar2/Ezyshop#1043]
### Description

 password is not shown 

### Screenshots

![Ezyshop and 13 more pages - Personal 2 - Microsoft​ Edge Beta 10_30_2024 8_52_05 PM](https://github.com/user-attachments/assets/6e296092-ecbe-4493-92b4-9e5f2e243b35)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Aditya90456, there is no need for a password while logging in or creating a new account. You just have to enter your email, and you'll receive an OTP for verification to confirm it's your email. So, there's no need for a password field for the user or shopper. Many e-commerce websites like Flipkart, Zomato, and Swiggy don't use a password section. Hope you understand.

I am closing this issue for now. Please don’t be discouraged, and keep contributing. Thank you!

- And **Aditya**, please don't forget to give our repository a star ⭐
