### ISSUE TITLE
[BUG] Vercel cache error

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#1046]
## Issue: Vercel Deployment Caching Problem

**Description**:  
The fetching in the current Vercel deployment is caching the data. As a result, newly added shops are not reflecting immediately. The requests are hitting Vercel's cache and returning a `307` response.

**Potential Solution**:  
Use cache-control headers to disable caching for critical fetches.

### Screenshots

![image](https://github.com/user-attachments/assets/1d134cbf-552a-484a-9a05-ff48dddbdd9e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays you are assigned.

**Comment by ShivanshPlays** [comment]
@mdazfar2 I am not able to resolve this issue, lets work with #1092 as a temporary solution, please put this on hold until we find a solution
