### ISSUE TITLE
[Feat]Adding a home icon in login/signup pages.

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [mdazfar2/Ezyshop#1047]
### Description

Home icon to navigate back to main page is missing in the login/signup tabs.

### Screenshots

<img width="1440" alt="Screenshot 2024-10-31 at 11 49 07 AM" src="https://github.com/user-attachments/assets/2a119cbe-e4ef-42a5-9447-d8ffe5264468">
Please assign this issue to me.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by BhavikaPachauri** [comment]
please asssign me
