### ISSUE TITLE
[Feat]Frequently Bought Together

### ISSUE THREAD

**Issue by Sai-Dangade777** [mdazfar2/Ezyshop#1055]
### Description

**High User Engagement**: This feature directly supports cross-selling by suggesting related items, which can encourage users to explore more products and potentially increase their cart size.

**E-commerce Standard**: This type of recommendation is widely used on popular e-commerce platforms (like Amazon), so it’s recognizable and trusted by users, and it improves the website's professionalism.

**Minimal Disruption to UI**: Adding this section would be straightforward since it only requires a designated area on product pages without altering the main layout or navigation.

**Easy to Justify**: This feature has clear business value as it encourages higher sales, making it a solid addition that most maintainers would appreciate.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Great observation, @Sai-Dangade777 :) but confirm one thing for me: are you saying that if I add an item, like a book, to the cart, then my recommendation list will mostly show books? Similar to how YouTube and Instagram show videos based on what we like and watch most. Let me know if I'm correct, or please explain what exactly you're trying to explain.

**Comment by Sai-Dangade777** [comment]
@mdazfar2 The maintainer is asking whether your recommendation feature will display products related to the ones users have shown interest in (like suggesting more books if they add a book to the cart). They want to confirm if your idea involves dynamic recommendations based on users' actions, similar to content algorithms on platforms like YouTube and Instagram.

Here’s a good way to respond:

---

Thank you for the feedback! Yes, my idea is to display related items based on the current product the user is viewing or has added to the cart. For instance, if a user is viewing a book, the recommendations would prioritize similar items, like related books or complementary products (e.g., bookmarks or reading lights).

This would involve creating a dynamic recommendation list that adjusts in real-time based on the type of product viewed or added to the cart. The goal is to suggest relevant items that are likely to appeal to the user, encouraging more exploration and potential purchases. Let me know if this aligns with your expectations, or if you’d like further details on the recommendation criteria!

**Comment by mdazfar2** [comment]
Alright @Sai-Dangade777, you are going to be assigned. Make this full functionality with no bugs.

Please note that we use a tech stack of Next.js, TypeScript, and Tailwind CSS, so ensure you follow that exactly. I recommend reading the [README.md](https://github.com/mdazfar2/Ezyshop/blob/main/README.md) file first to understand our what exactly our project work. Check out the [Project Structure](https://github.com/mdazfar2/Ezyshop/blob/main/PROJECT_STRUCTURE.md) for more understanding.

I hope you've read our [contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md).




- Don't forget to give a star to our [repository](https://github.com/mdazfar2/ezyshop). 🌟

- feel free to reach out to me on [Discord](https://discordapp.com/users/877531143610708028) or [LinkedIn](https://linkedin.com/in/md-azfar-alam/), If I am not available to reply here.


_Thank you!_
