### ISSUE TITLE
[Feat]Scroll-Triggered Promotional Pop-ups feature

### ISSUE THREAD

**Issue by Sai-Dangade777** [mdazfar2/Ezyshop#1056]
### Description

**Subtle but Impactful**: These pop-ups are an effective way to promote special offers, discounts, or newsletter sign-ups without disrupting the user's browsing experience.

**Increases Conversions**: By prompting users with limited-time deals or calls to action (like subscribing or exploring more), you create more opportunities for engagement and potential conversions.

**Lightweight Implementation**: This feature only requires JavaScript or CSS to detect the user's scroll position and trigger animations, making it relatively straightforward to implement and test.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Sai-Dangade777 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
