### ISSUE TITLE
[Feat] Add GitHub Stats Section to Home Page for EzyShop

### ISSUE THREAD

**Issue by kavya410004** [mdazfar2/Ezyshop#1057]
### Description

A new section needs to be added to the home page, as shown in the provided screenshot. This section will display the current GitHub repository statistics (stars and forks) and provide easy access for users to contribute to the project or star the repository.

### Requirements:
1. **GitHub API Integration**:
   - Fetch the **stars** and **forks** count from the GitHub API.
   - Display the live stats on the home page.

2. **Buttons**:
   - **"Give a Star" Button**: Redirects to the GitHub repository page.
   - **"Contribute Now" Button**: Redirects to the `CONTRIBUTING.md` page in the GitHub repo.

3. **Description Section**:
   - Add a brief description on the left side for EzyShop, summarizing its purpose and goals. This will replace the text shown in the sample screenshot.

4. **Responsive Design**:
   - Design the section to be visually consistent with the current EzyShop UI.
   - Ensure compatibility with both **dark mode** and **light mode**.

### Screenshots

![image](https://github.com/user-attachments/assets/44111cc2-c833-4758-a333-d0ba10006912)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Great idea, @kavya410004. You are now assigned.
