### ISSUE TITLE
[Feat] Enhancing the css styling of the scroll back button by adding a timeline on it.

### ISSUE THREAD

**Issue by shriyadindi** [mdazfar2/Ezyshop#1058]
### Description

Enhancing the css styling of the scroll back button by adding a timeline on it.

### Screenshots

![Screenshot 2024-10-31 115055](https://github.com/user-attachments/assets/5a82c2f5-1b63-43f4-9fc0-d8e122e7f97e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @shriyadindi As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
