### ISSUE TITLE
[Feat] Hover functionality on the cards of Facilities section

### ISSUE THREAD

**Issue by Abhinav1921** [mdazfar2/Ezyshop#1060]
### Description

In "Our Facilities" section, I would like to make the cards come forward and highlight them whenever the user hovers over the cards.

### Screenshots

![Screenshot (86)](https://github.com/user-attachments/assets/db8b1c7e-959a-414b-b7f3-33c425791e39)

### Checklist

- [x] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by veepanshu-kasana** [comment]
@mdazfar2  I want to contribute to this project on this particular issue. Please assign it to me!

**Comment by mdazfar2** [comment]
Hey @veepanshu-kasana,

We're currently following a first-come, first-served approach for assigning issues. If the initial assignee is unable to complete the task, we'll consider reassigning it.

I appreciate your enthusiasm for open source and your contributions. Keep up the great work! :)

**Comment by veepanshu-kasana** [comment]
@mdazfar2 feat(ui): enhance Card hover effects with smooth animations & gradients #1080
