### ISSUE TITLE
[Feat] add functionality, check description 

### ISSUE THREAD

**Issue by AE-Hertz** [mdazfar2/Ezyshop#1064]
### Description

add a sorting functionality,in the page, so that user can sort the stuff accordingly.
- sort by price
- sory by name
- ascending 
- descending orders

Assign me this issue, i expect a level3 for this./

### Screenshots

![Screenshot 2024-11-04 211815](https://github.com/user-attachments/assets/2cabe3ae-0466-4cf2-aa93-51f79c7ce04a)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@AE-Hertz As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
