### ISSUE TITLE
[BUG] newsletter section issue

### ISSUE THREAD

**Issue by Amanyadav789** [mdazfar2/Ezyshop#1067]
### Description

when i am submitting my email and name in newsletter section . its not getting submitted

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Amanyadav789 You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
