### ISSUE TITLE
[BUG] Inconsistent alignment of profile pictures 

### ISSUE THREAD

**Issue by TanishSen** [mdazfar2/Ezyshop#107]
### Description

**The profile pictures for the three testimonials are not consistently aligned**. 

Specifically:

1. Anita Desai (left): Profile picture is aligned to the left of the name and title.
2. Manoj Gupta (center): Profile picture is aligned to the left of the name and title.
3. Priya Nair (right): Profile picture is aligned to the right of the name and title.

This inconsistency in alignment creates a visual imbalance and could be considered a design flaw. For better visual harmony and professional appearance, all profile pictures should be consistently aligned - either all to the left or all to the right of the names and titles.

### Screenshots

![image](https://github.com/user-attachments/assets/6756b5d2-ba4b-430a-a1f2-0ef29a5bc45c)

### Any additional information?

The layout should be adjusted to ensure that all profile pictures are aligned consistently across all testimonials. This would enhance the overall aesthetic and make the interface appear more polished and intentional in its design.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@TanishSen, everything looks good. Please check again and raise an issue accordingly, which I’ll be happy to assign to you. Thank you!

- please ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
