### ISSUE TITLE
[Feat]Adding FAQ section.

### ISSUE THREAD

**Issue by Rish6392** [mdazfar2/Ezyshop#1071]
### Description

i will make a section of common question arises and answer them.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by veepanshu-kasana** [comment]
@mdazfar2  I want to contribute to this project on this particular issue. Please assign it to me!
