### ISSUE TITLE
[Feat]: Making Cartpage 

### ISSUE THREAD

**Issue by satyam969** [mdazfar2/Ezyshop#1072]
### Description

i want the cart page to store the products even when not logged in just before payment u need to sign in 

would like to be assigned

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @satyam969, please take a look at the website to ensure the changes have been implemented correctly. It's important to review the implementation before raising any issues. This is not the correct way to work on open source, I am not instruct you just trying to show the correct way to contribute to open source.

Don't forget to give a star to our [repository](https://github.com/mdazfar2/ezyshop). 🌟

- _Thank you!_
