### ISSUE TITLE
[Doc]: Add Stargazers and Forkers to README.md

### ISSUE THREAD

**Issue by AnushkaChouhan25** [mdazfar2/Ezyshop#1073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Include sections for Stargazers and Forkers in the README.md to acknowledge contributors and increase community engagement. This addition will display user profiles who have starred or forked the repository, enhancing visibility and interaction.

### Suggested Change

![Screenshot 2024-11-02 232159](https://github.com/user-attachments/assets/1c33db90-1baf-4a4e-b467-bbe9b3389fa8)

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @AnushkaChouhan25, I understand that adding Stargazers and Forkers in the README.md is a good idea, but I don't think it is necessary for our README.md. I apologize, but I need to close this issue for now. Please feel free to raise any other good issue, which I would be happy to assign.


Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star ⭐

- _Thank you!_
