### ISSUE TITLE
[Feat] Implement FAQ page 

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#1074]
### Description

the website is missing a faq page which educates the users about the website 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
