### ISSUE TITLE
[Feat]  Implement Super Admin Functionality on EzyShop Website : Backend schema, server action and necessary routes

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#1076]
### Description

# Issue: Implement Super Admin Functionality on EzyShop Website

## Description

This issue focuses on implementing the super admin functionality for the EzyShop website. The goal is to establish a robust backend infrastructure that enables super admin users to manage the platform effectively, ensuring better control and oversight over vendor and customer activities.

## Requirements

1. **Super Admin Role**: 
   - Introduce a super admin role within the user management system to distinguish super admins from regular admins and vendors.
   - This role will have elevated privileges to perform various management tasks across the platform.

2. **Login Functionality Page**:
   - Implement a secure login mechanism for super admins to access the admin panel.
   - Ensure proper authentication and authorization checks are in place to protect sensitive operations.

3. **Backend Schema Updates**:
   - Update the existing database schema to accommodate the new super admin role.
   - This may involve modifications to the user table to include role-based access control.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays You are assigned.
