### ISSUE TITLE
[Feat]Resizing all cards to  a same size

### ISSUE THREAD

**Issue by tanushac** [mdazfar2/Ezyshop#108]
### Description

Making all the cards the same size for uniformity and better layout

### Screenshots

![image](https://github.com/user-attachments/assets/216d82d6-40a9-4ed6-b19b-9f2f9455279f)
![image](https://github.com/user-attachments/assets/3d0b5121-3617-42ae-b995-deb8274f23aa)
![image](https://github.com/user-attachments/assets/c78a8ef4-9a3e-464e-a064-d0e1ce903b23)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @tanushac great issue found! You are going to be assigned.

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md).

- Don't forget to join our official [Discord server](https://discord.gg/SEzpxqQG).
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
- And please ⭐ our repo
