### ISSUE TITLE
[Feat] Added multiple  language support system

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [mdazfar2/Ezyshop#1086]
### Description

i want to added a multiple language support system for your website that's   help your producat to scall globally for all over country 

### Screenshots

a

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@biswajit-sarkar-007 you are assigned.
