### ISSUE TITLE
[Feat]: Add the form validation to the Contact Page

### ISSUE THREAD

**Issue by Richajaishwal0** [mdazfar2/Ezyshop#1087]
### Description

The form in the contact page is accepting the response eventhough the input are invalid so i want to add form validation over there.

### Screenshots

![image](https://github.com/user-attachments/assets/7fa6d789-2849-4556-9bd8-a8316491c641)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Richajaishwal0 Can you please explain more clearly what exactly you are trying to say? It would help me assign this issue to you. Thank you.

**Comment by Richajaishwal0** [comment]
The given form accept the responses even the inputs are invalid. There is no validation for name, Email and other inputs.
Even after give invalid inputs as 
![image](https://github.com/user-attachments/assets/d3eaecfe-98e7-475c-aeeb-053bdcbb0532)
The form is accepting the responses.
![image](https://github.com/user-attachments/assets/9b646fc0-9777-4e7d-a940-840fb8e10067)
