### ISSUE TITLE
[BUG] Dark mode is not works for Terms page

### ISSUE THREAD

**Issue by dipexplorer** [mdazfar2/Ezyshop#1088]
### Description

Currently the dark mode is not implemented for terms page.

### Screenshots

![Screenshot (275)](https://github.com/user-attachments/assets/16eedb5a-68a9-45bc-b099-29c4f1038be1)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by bhavesh236** [comment]
I'm a GSSoC'24-Extd contributor
 I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
> I'm a GSSoC'24-Extd contributor I am willing to work on this issue

@dipexplorer The PR has already been raised referencing this issue, and it is a work in progress. I cannot assign this issue to you. You can raise any other issue or bug.
