### ISSUE TITLE
[Feat ]Develop a Comprehensive and User-Friendly FAQ Section

### ISSUE THREAD

**Issue by dipexplorer** [mdazfar2/Ezyshop#1089]
### Description

The current website lacks a dedicated FAQ (Frequently Asked Questions) section, which is essential for addressing common user queries and improving the overall user experience. The FAQ section should provide concise, helpful answers to common questions related to services, account management, payment processes, and any other relevant topics. Organizing the FAQs into categories will make it easier for users to find the information they need.

Expected Outcome:

- A structured FAQ section organized into categories (e.g., Account, Services, Payment, etc.) for ease of navigation.
- Clear, informative answers to common questions, ensuring users can resolve issues independently.
- Mobile-friendly design with collapsible or accordion-style questions to keep the layout clean and readable on all devices.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@dipexplorer You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
