### ISSUE TITLE
[Feat]Quick links in footer 

### ISSUE THREAD

**Issue by pavitraag** [mdazfar2/Ezyshop#11]
### Description

Present quick links link are not correctly mapped. I would like to enhance the footer.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @pavitraag, this issue has already been assigned to someone. Please look at any other issue, and I will be happy to assign it to you.

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me

**Comment by mdazfar2** [comment]
hey @pavitraag I hope you are doing well!

- It has been 2 days and you haven't responded to anything. Unfortunately, I have to close this issue because there are many duplicate issues raised. Please don't be discouraged. Thank you.
