### ISSUE TITLE
PULL REQUEST CHECKER WORKFLOW AUTOMATION 🚀

### ISSUE THREAD

**Issue by amiya-cyber** [mdazfar2/Ezyshop#1101]
Description: We need to create a GitHub Actions workflow that automates the validation of pull requests (PRs). This workflow will ensure that all PRs meet the following criteria before being merged:

PR Description Check: Every PR must have a description. If the description is missing, the PR should fail the check.

Issue Reference Check: The PR description must include an issue reference in the format Fixes #. If the PR is not addressing an existing issue, it should mention Fixes #NEW as a placeholder.

Acceptance Criteria:

A GitHub Action workflow is triggered on PR events (opened, edited).
The workflow checks the PR body for:

A non-empty description.
The presence of Fixes # or Fixes #NEW.

If the criteria are not met:
The workflow should fail and return clear error messages.

If the checks pass:
A confirmation message is outputted.

Expected Output:

1. Error message if the PR description is missing.
2. Error message if the issue reference is missing or incorrectly formatted.
3. Success message when all checks are satisfied.

ASSIGN WITH LEVEL 3

**Comment by mdazfar2** [comment]
@amiya-cyber Tell me one thing: if a contributor creates a PR without referencing any issues, will the PR be closed automatically, or will a message be given to add issue references by **github-actions**? Also, tell me one more thing: can I reopen a PR that was closed without referencing any issue for merging which was closed by **github-actions**, especially when I create a PR from my own repo with `another branch` to the `main` branch? Then it will close automatically! Am I right?

**Comment by amiya-cyber** [comment]
It will drop a msg and checks will be crossed

**Comment by mdazfar2** [comment]
> It will drop a msg and checks will be crossed

@amiya-cyber That's a nice suggestion. Can you make it so that when I create a PR without referencing any issue, it should be correct, and no message will be dropped, only for the owner of the repo?
