### ISSUE TITLE
to add progress bar at all the required pages ...

### ISSUE THREAD

**Issue by 2004pra** [mdazfar2/Ezyshop#1104]
please assign me this issue under gssoc extd 24,
please make it level 2 
@mdazfar2

**Comment by mdazfar2** [comment]
Hey @2004pra, I don't exactly understand what you're trying to say. You described it in just two sentences, which doesn't clearly explain what you want to work on. Please don't do that.

You raised a blank issue. You should choose the appropriate issue template and describe it accordingly, as the chosen template will clarify what you want to work on. I will be happy to assign issues that are clearly understandable. Please keep this in mind—I'm not instructing you, just trying to show the correct roadmap for working on open source. Please don't be discouraged; I am closing this issue for now.

**Comment by 2004pra** [comment]
There is a feature called progress bar which goes to the end of website top
horizontally it’s a thin line which gets completed as you scroll  down and
gets unfilled if you scroll up again ! Simple

**Comment by 2004pra** [comment]
see this red bar as a sample --> 
![Screenshot 2024-11-08 235530](https://github.com/user-attachments/assets/6d25fa18-c7fa-41e0-b33b-a020bd4822cb)
@mdazfar2

**Comment by mdazfar2** [comment]
@2004pra, this is a very good feature, but it does not look good on our website. According to our website's design, a simpler effect and feature will look more attractive. So, as of now, I don’t think this issue is necessary for our website. Please work on any other issue that is needed and raise issues accordingly. ***Thank you!***

**Comment by 2004pra** [comment]
> @2004pra, this is a very good feature, but it does not look good on our website. According to our website's design, a simpler effect and feature will look more attractive. So, as of now, I don’t think this issue is necessary for our website. Please work on any other issue that is needed and raise issues accordingly. _**Thank you!**_

it will be slim and will match the theme of the website  too 
you dont have to worry it will surely look attractive sir .. not too flashy decent

**Comment by Swati970** [comment]
Please assign me this issue, I will work on it
