### ISSUE TITLE
[BUG]  Deployment link

### ISSUE THREAD

**Issue by VJ12More** [mdazfar2/Ezyshop#1108]
### Description

When we click on Deployment link , web page of our website is not visible instead a white screen appears at the screen . 

### Screenshots

![Screenshot 2024-11-09 093353](https://github.com/user-attachments/assets/1463d2b4-77c2-44f6-bc1a-1d939214968e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @VJ12More, I know, I also want to use this link, but it is not accessible because it is already in use. That's why we use the link - ezshopz.vercel.app.

- Can you help us improve this if possible?

**Comment by VJ12More** [comment]
Yess
