### ISSUE TITLE
[Feat] Chat Functionality Between Users and Sellers

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#1110]
# Feature Request: Chat Functionality Between Users and Sellers

## Description
The chat feature will be implemented in stages across multiple pull requests. Users will have the ability to search and choose any seller to start a conversation, while sellers will be able to view and respond to user messages. This feature will be introduced in a series of PRs, starting with frontend UI design using dummy data and gradually moving to backend integration with dynamic data.

### PR Series:

1. **Backend setup for chat functionality (EDIT : completed in  #1117  )**   
   - Implement server actions and schema modifications to dynamically populate the specific chat page for both users and sellers.

2. **Frontend: User Dashboard page with list of all available vendors to select and explore their offerings
   (EDIT : completed in #1118  )**
   - Implement a fully responsive and attractively designed frontend page where users select any vendor's list.
   - Json server will be used initially to simulate the list of vendors for users.
   - Ensure design , responsiveness , consistency , theme and usability for the page.

3.. **add a user profile section in the  (EDIT : completed in  #1122  )**   
   - Add a user profile section to the dashboard, which will include stats for users.

4. **OfferingsByVendor Page (EDIT : completed in #1119   )**
- Page with list of all available offerings of a specific vendor to select and and discuss about that specific offering with the vendor
   - Implement a fully responsive and attractively designed frontend page where users can search and select who to chat with.
   - Json server will be used initially to simulate the list of vendors for users.
   - Ensure design , responsiveness , consistency , theme and usability for the page.

5. **Frontend: Specific Chat Page  (EDIT : completed in #1120    )**
   - Design a fully responsive chat interface where users can view their conversation with a specific vendor.
   - add preview of the offering that is being discussed about
   - Use JSON server to send dummy data to simulate messages between users and sellers.
   - Ensure design , responsiveness , consistency , theme and usability for the page.

6. **Backend: Dynamic User Selection**
   - Implement necessary server actions and modify the schema to dynamically populate the pages made in PR 2 and 3.
   - Connect dynamic data to the frontend, replacing the dummy data for a functional search and selection experience.

7. **Backend: Dynamic Chat Functionality**
   - Integrate real-time messaging or refreshable data to keep the chat experience responsive and engaging.
   - Connect dynamic data to the frontend, replacing dummy data to support actual message exchanges.

## Additional Notes
- Break down each stage into separate PRs to ensure modular, testable code at each stage.
- Ensure all schema and server actions are well-documented for future extensibility.
- Consider security measures and privacy of chat data between users and sellers.

---

This series of PRs will introduce an intuitive and feature-rich chat experience between users and sellers on the platform.

**Comment by mdazfar2** [comment]
@ShivanshPlays you are assigned.
