### ISSUE TITLE
[Feat] Order functionality and Integrate payment setup using razorpay SDK

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#1111]
### Description

1. create schema and server actions: full backend for order functionality
2. create seller dashboard page for orders 
3. add razorpay integration on frontend and backend: logic to mock a successful payment and thus order creation on backend that will trigger the razorpay sdk webhook.
4. add backend logic to catch the webhook by razorpay and set the order status to paid

the above tasks will be covered under this issue and PRs will be generated accordingly

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays go ahead
