### ISSUE TITLE
[BUG] Loading error

### ISSUE THREAD

**Issue by nikhilritgithub** [mdazfar2/Ezyshop#1114]
### Description

page is not loading after taking too much time .

### Screenshots

![page-not](https://github.com/user-attachments/assets/34a30d2e-4945-41e7-bd4a-945c79bb9d84)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@nikhilritgithub use this link- `ezyshopz.vercel.app`

**Comment by nikhilritgithub** [comment]
@mdazfar2 now its working
