### ISSUE TITLE
Change in link of instagram in footer

### ISSUE THREAD

**Issue by ShaikHafiza** [mdazfar2/Ezyshop#1116]
Instagram link in footer section needs to change...
currently, the icon is directing again to the same page..
I would like to change the redirecting link to the instagram default link

![image](https://github.com/user-attachments/assets/38a7a0cf-49a5-4d63-b6a2-b98ceac1aa79)

Can you please assign me this issue...

**Comment by mdazfar2** [comment]
Hey @ShaikHafiza, we don't have an Instagram account for Ezyshop at the moment. Once we create one, we'll let you know to add the correct redirection link.

**Comment by ShaikHafiza** [comment]
for now I will add default link to this

**Comment by mdazfar2** [comment]
@ShaikHafiza leave this for now.
