### ISSUE TITLE
[Feat] Add a  CI Build Pipeline 

### ISSUE THREAD

**Issue by ShobhitPatra** [mdazfar2/Ezyshop#1124]
### Description

Set up a build pipeline that ensures the application can successfully build whenever a pull request (PR) is raised. This will prevent merging changes that break the build and maintain the stability of the main branch.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShobhitPatra you are assigned

**Comment by ShobhitPatra** [comment]
Hey @mdazfar2 ,this PR https://github.com/mdazfar2/Ezyshop/pull/1127 soives this issue,Hence Closing It
