### ISSUE TITLE
Make card section of the body more attractive using hover 

### ISSUE THREAD

**Issue by Vaibhavkumar5158** [mdazfar2/Ezyshop#113]
![image](https://github.com/user-attachments/assets/475fa574-c83e-4d05-9272-f94d847b53fe)

Adding hover feature in these 6 cards  will make this more attractive in website .

Pls assign GSSOC'24 extd and HACKTOBERFEST badge .

**Comment by thakuratul2** [comment]
@Vaibhavkumar5158 assigned

**Comment by Abhi0049k** [comment]
@Vaibhavkumar5158 would like to work on this issue

**Comment by Samyak137** [comment]
I have to work on that will you please assign it to me.
