### ISSUE TITLE
[Feat]Add animated cursor

### ISSUE THREAD

**Issue by jvkousthub** [mdazfar2/Ezyshop#116]
### Description

adding a cursor pointer that is responsive and animated would be good

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Samyak137** [comment]
I have to work on that will you please assign it to me.

**Comment by jvkousthub** [comment]
@mdazfar2 I'm ready to contribute waiting for you to assign

**Comment by mdazfar2** [comment]
@jvkousthub please share the demo video

**Comment by Kavish-Paraswar** [comment]
I would like to work on this issue , as I have a strong background in CSS and HTML. Please assign me under GSSOC'24 extended.
