### ISSUE TITLE
[BUG] The footer on desktop devices is not aligned

### ISSUE THREAD

**Issue by rishuishind** [mdazfar2/Ezyshop#117]
### Description

On desktop devices the footer links and other tags are not alligned and hence they're not visible

### Screenshots

Currently the footer sections looks like this:
<img width="1470" alt="Screenshot 2024-10-03 at 11 32 27 PM" src="https://github.com/user-attachments/assets/0561d4c7-8211-4147-98a4-97225340ac74">

Whereas it should be looking like this:
<img width="1465" alt="Screenshot 2024-10-03 at 11 55 09 PM" src="https://github.com/user-attachments/assets/52ee2153-d3a5-4ed1-9549-709dc3382e2c">

### Any additional information?

I have changed the code and will raise a PR, if you find it correct, you can merge it :-)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@rishuishind Thank you for the issue, everything looks good. Please check again and raise an issue accordingly, which I’ll be happy to assign to you. 

![{FEA4CF33-CC87-42E5-9458-E64A6B423408}](https://github.com/user-attachments/assets/f18028c0-9a08-4984-9f3a-e7574cf8b799)



- please ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
