### ISSUE TITLE
[Feat] Signup / Login page is not available 

### ISSUE THREAD

**Issue by Mr-DK07** [mdazfar2/Ezyshop#12]
### Description

Problem :-
There is signup and login pages are not available. It is very important part of any website.

Solution :- 
I wanted to build these pages which are align with your existing website.
I have better understanding of designing, so I can build it with user friendly and responsiveness functionality. I can also add some user validation.

### Screenshots

![Screenshot 2024-10-01 210428](https://github.com/user-attachments/assets/c633267e-2579-489a-a6d1-5691dcd116fe)

### Checklist

- [x] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Mr-DK07** [comment]
@mdazfar2 Could you assign me this, so that I can start working on this. please add tag GSSoC'24-Extd ,Hacktoberfest'24 accepted  and also level this.

**Comment by mdazfar2** [comment]
hey @Mr-DK07, You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)

**Comment by Mr-DK07** [comment]
@mdazfar2 Thanks to know me, It was my mistake. I will take care of it in future.

**Comment by mdazfar2** [comment]
@Mr-DK07 It is already solved thank you
