### ISSUE TITLE
[Feat] Login and Registration Page 

### ISSUE THREAD

**Issue by achintyasrivastav** [mdazfar2/Ezyshop#125]
Implement a modern login and registration page that opens on the same screen with a blur background effect. This will enhance user focus on the forms while maintaining a visually appealing interface.

Key Requirements:

Blur Background Effect: The background should blur when the form is active, highlighting the login/registration area.
Responsive Design: Ensure forms are mobile-friendly and accessible.
Toggle Functionality: Allow users to switch between login and registration seamlessly.
Request:

Please label this issue under Hacktoberfest 2024 for contributions. Looking forward to any suggestions!

**Comment by mdazfar2** [comment]
Hi @achintyasrivastav, thank you for raising the issue. Could you please share a demo video? This will help me understand the issue in more detail and assign it appropriately.

**Comment by achintyasrivastav** [comment]
Hi @mdazfar2 ,

Thank you for your prompt response! I appreciate your willingness to look into this issue. I can share demo images to illustrate the design concept for the login and registration pages with a blur background effect.

Please find the images attached below:

Login Page Example : 
![Screenshot 2024-10-03 025022](https://github.com/user-attachments/assets/0f41b1ba-365c-47d4-b781-ffdeb57fc7aa)

Registration Page Example : 
![Screenshot 2024-10-03 025050](https://github.com/user-attachments/assets/52ef339e-8d3b-47c0-aad0-4874e6888524)

Let me know if you need any further details or if a video would still be preferred!

**Comment by mdazfar2** [comment]
@achintyasrivastav It is good, but it looks weird on our website. The current one is better. Can you please look at another issue, which I am happy to assign to you.

* please give ⭐ our repo

* Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
* And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
