### ISSUE TITLE
hovering effect on images

### ISSUE THREAD

**Issue by Codewithmeowmeow** [mdazfar2/Ezyshop#127]
### Description

i would like to create hovering effect on images which will make it more interesting and nice.
kindly assign it to me and also add labels.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Codewithmeowmeow As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
