### ISSUE TITLE
I want to add some animation for a better user experience 

### ISSUE THREAD

**Issue by akhileshverma92** [mdazfar2/Ezyshop#128]

**Comment by mdazfar2** [comment]
@akhileshverma92 we don't need any particular animation. than you!
]
- please give ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
[01:34, 10/4/2024] Azfar:
