### ISSUE TITLE
[Bug] The Login/Signup button is only active on the home page. When navigating to other pages, the button appears disabled, or it does not redirect to the Login/Signup page.

### ISSUE THREAD

**Issue by JangidVish** [mdazfar2/Ezyshop#129]
### Description

Issue/Bug Description:

The Login/Signup button works correctly on the home page, but when navigating from other pages, the button either appears disabled or fails to redirect to the Login/Signup page.

What I Tried:

Verified that the button and link are correctly set up on the home page.
Checked the routing and confirmed that the correct path is being used for navigation.

### What browser are you seeing the problem on?

Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @JangidVish, great issue found! You are going to be assigned.

-  please ⭐ our repo

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md).

- Don't forget to join our official [Discord server](https://discord.gg/SEzpxqQG).
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)

**Comment by Hamza20203064** [comment]
@JangidVish @mdazfar2 I believe this issue has already been resolved.
