### ISSUE TITLE
Active Button Highlight Stuck on Home Button in Navbar Despite Navigation

### ISSUE THREAD

**Issue by Hamza20203064** [mdazfar2/Ezyshop#13]
### **Description:**

In the navigation bar, there are buttons such as **Home**, **About**, **Category**, **Team**, **Page**, and **Contact**. Each button is expected to highlight when clicked to indicate the active page. However, the highlight (active state) remains on the **Home** button even when navigating to other pages.

**Expected Behavior:**
The button corresponding to the active page should be highlighted, and the highlight should switch as the user navigates between pages.

**Actual Behavior:**
The highlight (active state) is stuck on the **Home** button, even after navigating to a different page.

**Before:**
![Screenshot 2024-10-01 205903](https://github.com/user-attachments/assets/12406a4e-7ffc-4feb-9e3a-97175660aa9d)

**AFTER:**
![Screenshot 2024-10-01 210132](https://github.com/user-attachments/assets/4e76b074-4a1d-4303-9b54-0daa6d93de7c)

**Additional Information:**
Ensure that the active state correctly switches to the current page’s button when navigating. This might require adjustments to the CSS or JavaScript handling the active class.

**If you assigned this issue to me under gssoc'24-extd, I can fixed it.**

**Comment by mdazfar2** [comment]
@Hamza20203064 Issue acknowledged! you are going to be assigned

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me

**Comment by mdazfar2** [comment]
Hey @Hamza20203064, it's been 2 days, and you haven't responded, so I have to reassign this. Please don't be discouraged. I will assign this to @lakshyeahh. Please create a PR as soon as possible and let me know when you start working on it.

**Comment by Hamza20203064** [comment]
@mdazfar2 please give me 24 hour I will pull the request within 24 hour. This is my request.

**Comment by lakshyeahh** [comment]
Sir can i also work along side?

**Comment by lakshyeahh** [comment]
Right on it sir.

**Comment by Hamza20203064** [comment]
@mdazfar2 had created the pull request. Please review and accept the pull request

**Comment by mdazfar2** [comment]
@Hamza20203064 please update the sync fork and let me know.

**Comment by Hamza20203064** [comment]
@mdazfar2 I updated the sync, if there is any issue let me know

**Comment by mdazfar2** [comment]
> @mdazfar2 I updated the sync, if there is any issue let me know


@Hamza20203064 The login/signup page opens only from the homepage and does not open from any other page. Hope you understand. If you want to work on it, kindly create an issue and PR. Thank you!

**Comment by Hamza20203064** [comment]
Yeah, sure, I can do that. Please assign it to me.
