### ISSUE TITLE
[Feat] ScrollBar Styling

### ISSUE THREAD

**Issue by MishraTanishq619** [mdazfar2/Ezyshop#133]
### Description

Currently : We have the dafault styles for Scrollbar. We hadn't gave a custom styles to our scrollbar.
Expectation : We can add our custom styles to the scrollbar. So that it can be aligned with our app theme.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@MishraTanishq619 assigned

**Comment by Pariyul** [comment]
Hello! I’m excited to work on this issue as a GSSOC'24 contributor. Could you please assign it to me?

**Comment by Kavita1928** [comment]
@MishraTanishq619 size of scrollbar is so small it is not easily accessible. fix it

**Comment by mdazfar2** [comment]
no any reply on pull sorry i have to close this issue for now
