### ISSUE TITLE
Feature Request: Add Hover Effect to Cards

### ISSUE THREAD

**Issue by GAURAV8520** [mdazfar2/Ezyshop#135]
### Current Behavior
The cards currently display information without any hover interaction.

### Proposed Solution
- Add a hover effect to the cards in the section.
- On hover:
  - Each card should have a slight elevation (increase in box-shadow).
  - Background color of the card should change subtly.
  - The icon inside the card should slightly scale up.

### Acceptance Criteria
- [x] Cards should display an increased box-shadow and slight background color change on hover.
- [x] Icons should scale up slightly on hover.
- [x] The hover effect should be smooth and consistent across different devices and screen sizes.

### Additional Context
This enhancement will improve user engagement by providing visual feedback when users interact with the cards.

### Screenshots

![Screenshot 2024-10-04 101910](https://github.com/user-attachments/assets/7156c510-7ba6-426f-8400-2b9129359b5f)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by GAURAV8520** [comment]
@thakuratul2 assign me

**Comment by mdazfar2** [comment]
Thank you @GAURAV8520 for creating such an attractive and well-defined issue. Can you please suggest what type of hover criteria we should add according to the website and its functionality?

**Comment by GAURAV8520** [comment]
### Criteria for the Hover Effect

#### 1. User Engagement
The hover effect should highlight actionable elements (such as product details, icons, or buttons) to make them stand out without overwhelming the user. For instance:
- Increasing the shadow depth and adding a slight lift can help users easily identify which card they are interacting with.

#### 2. Functional Indicators
Icons or clickable elements should visually communicate their interactivity. Consider:
- Scaling up icons slightly to indicate their functionality.
- Changing the icon color to match the site’s theme, such as using the blue `#007bff` to align with branding.

#### 3. Consistency
It is crucial to maintain a consistent hover effect across all cards to ensure a cohesive user experience:
- Ensure that all cards exhibit the same hover behavior for uniformity in design and interaction.

### Hover Effect Demo


https://github.com/user-attachments/assets/040c74c9-9142-4c6c-9d1c-292647cca417

**Comment by GAURAV8520** [comment]
@mdazfar2 assign this to me and also label it for ggsoc-ext and Hacktoberfest

**Comment by arpit74170** [comment]
Hi ,this one issue is very intresting for me ,i am designing the website with hower effects ,please asign this one issue to me

**Comment by mdazfar2** [comment]
Hey @GAURAV8520 the hover on icon does not look good add hover on full card
