### ISSUE TITLE
[BUG] Privacy Invasion for users entering their data

### ISSUE THREAD

**Issue by maitri-vv** [mdazfar2/Ezyshop#136]
### Description

In the login page there in input field for username, it stores and keeps input entered by users previously which can lead to data privacy issues.

### Screenshots

![image](https://github.com/user-attachments/assets/dabd8806-5239-4cce-9283-3349ddfcb4b9)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@maitri-vv As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
