### ISSUE TITLE
[BUG] Contact us div issue

### ISSUE THREAD

**Issue by 4F24L** [mdazfar2/Ezyshop#137]
## Contact Us Div Issue
- That blue div is too big in height.

### There are two solutions :
- Div can be narrow down to look better.
- Keeping the height unchanged, we can put the texts in the center.

### Screenshots

![image](https://github.com/user-attachments/assets/d69da045-d971-4b21-9716-7f3018df8105)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@4F24L can you please share the screenshot how much div you want to decrease.

**Comment by 4F24L** [comment]
### Changes Made
- That div is too unnecessarily big and for mobile devices also. 
- You can check before and after images.


## Before : 

![image](https://github.com/user-attachments/assets/0fa65d00-fd6a-492b-92d6-47a0bd8a7f36)
![image](https://github.com/user-attachments/assets/06fef809-ca60-4d53-b4d0-05c3c2190d9d)


## After : 
- Now this is perfect for every devices. ✅

![image](https://github.com/user-attachments/assets/6acfdc6b-8af3-4ae2-87a8-140788bfd564)
![image](https://github.com/user-attachments/assets/7cb50c44-da28-4531-b4cb-851af9a701af)


### Please add hactoberfest and GSSoC24 tag. You can assign me for this issue.

**Comment by mdazfar2** [comment]
It is good please leave for now sorry we have to close the issue for now

**Comment by 4F24L** [comment]
Why ? This is a legit issue?! 

Why you don't want to fix ?

**Comment by mdazfar2** [comment]
Sorry @4F24L, I didn’t mean to say it like that, it sounded very weird. I apologize, but I need to close this issue for now. Please don’t be discouraged!


- please give ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
