### ISSUE TITLE
[BUG] Alignment of card elements 

### ISSUE THREAD

**Issue by anushkajjadhav** [mdazfar2/Ezyshop#140]
### Description

The various card elements are misaligned. I can align them and enhance it keeping the project's aesthetic in mind

### Screenshots

<img width="766" alt="Screenshot 2024-10-04 at 1 22 02 PM" src="https://github.com/user-attachments/assets/05415f68-f55e-46f5-9315-6803ddd3cf41">
<img width="766" alt="Screenshot 2024-10-04 at 1 21 51 PM" src="https://github.com/user-attachments/assets/aff3412f-d915-4714-abf5-4f7d9b142b89">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
**@anushkajjadhav Thank you for the issue, everything looks good. Please check again and raise an issue accordingly, which I’ll be happy to assign to you.** 

![{4C856607-81AA-4F78-9E69-4D8C8D3DC252}](https://github.com/user-attachments/assets/3a94c240-d1f5-4e79-b0c6-f283f373fbb8)


![{7A3935D4-EF50-440B-8D35-17CE9527F5BA}](https://github.com/user-attachments/assets/7f66f6b2-6fd1-497a-aab5-9426cab3f552)



- please ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
