### ISSUE TITLE
I wanted to add dark and light theme toggle Feature. 

### ISSUE THREAD

**Issue by anshumanat** [mdazfar2/Ezyshop#142]
### Description

I propose adding a **dark theme** to our application to enhance user experience by reducing eye strain and improving accessibility in low-light environments. This addition will not only modernize our design but also meet  user preferences.
will provide more comfortable viewing experience.
Tech Stack:-HTML,CSS, JavaScript.
 

Please assign me this.

### Screenshots

![Screenshot 2024-10-04 133529](https://github.com/user-attachments/assets/a0bd8a93-7d2e-4575-a490-0ad49ae65745)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hey @anshumanat Thank you for creating the issue.

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.


- please give ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)

**Comment by anshumanat** [comment]
Hi @mdazfar2,

Thank you for the update! I understand and appreciate the clarity. However, I have already worked on this and have a video demonstration ready. I'd be happy to share it if you'd like to reconsider or review it for future reference.

Let me know if you're open to checking it out! Also, I've already given a ⭐ to the repo.

Looking forward to contributing more. :)

https://github.com/user-attachments/assets/992a9042-15b3-43f0-9818-64a29af81de8

**Comment by mdazfar2** [comment]
@anshumanat, I really appreciate your work, but the website is not fully dark. Some cards and sections are the same color. Try to make the entire website dark.

**Comment by anshumanat** [comment]
Thank you for the feedback! I see what you mean, and I’ll work on making the entire website fully dark, including the cards and sections. I’ll update you once the changes are made.

**Comment by anshumanat** [comment]
Hi @Kavita1928 mam! Thank you for your feedback regarding the color contrast on the website. I understand your concerns about the black background not fitting well with the design. I will focus on other issues for now, but if you ever reconsider this aspect in the future, I would appreciate the opportunity to revisit it. Thank you again for your input!
