### ISSUE TITLE
[Enhancement] Can we just move a bit styling for the Founder in the center

### ISSUE THREAD

**Issue by maitri-vv** [mdazfar2/Ezyshop#145]
### Description

![image](https://github.com/user-attachments/assets/86433741-3489-450d-b015-942e8a05e39f)
This is off-center can i make it centered ? 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@maitri-vv go ahead
