### ISSUE TITLE
Color Optimization in Website to differentiate Cards and Navbar

### ISSUE THREAD

**Issue by Trumilnasit** [mdazfar2/Ezyshop#147]
@mdazfar2  
I have analyzed the website and found that the cards and navbar is diffused with the background color ,so to feel like its really a card and a different section I have given the unique color combo according to the theme of your website .
To correct that please allow me to this repo. 
also, add some labels like @hackoteberfest , @gssoc,etc..
Screenshot 1: 
![Screenshot 2024-10-04 155733](https://github.com/user-attachments/assets/73b1188f-b0ed-411b-a916-2d5de69b7142)

Screenshot 2:
![Screenshot 2024-10-04 155755](https://github.com/user-attachments/assets/a262ca3d-6a40-4b13-b574-8d3c227576f9)

**Comment by mdazfar2** [comment]
@thakuratul2 @Kavita1928

What are your opinions on it?

**Comment by Trumilnasit** [comment]
> @thakuratul2 @Kavita1928
> 
> What are your opinions on it?

@mdazfar2 :-Thank you for responding ,I want to change some color opacity of  navbar and cards to make it distinguise b/w them  I saw this issue in many pages.

**Comment by Kavish-Paraswar** [comment]
I would like to work on this issue , as I have a strong background in CSS and HTML. Please assign me under GSSOC'24 extended.

**Comment by Kavita1928** [comment]
@mdazfar2  According to me present color gradients  are good

**Comment by mdazfar2** [comment]
> @mdazfar2 According to me present color gradients are good

@Kavita1928 Alright! closing issue for now.

**Comment by Trumilnasit** [comment]
@Kavita1928 :there is clear diff b/w this two pictures which posted above and if you will apply it you can get good visibility and showing diff b/w cards and rest of things this also make diff. in contact page .
@mdazfar2 :-can you assign me this repo. also i will change some more things which will add some attractiveness to this web-application.

**Comment by mdazfar2** [comment]
@Trumilnasit, if you really want to contribute, please look at issue #159 and ping me accordingly. Thank you. Only PRs that are necessary will receive the GSSoC label; changing colors and text won't qualify. Please don't be discouraged, I appreciate your interest in contributing. Thank you.
