### ISSUE TITLE
[Feat] want to add framer motion

### ISSUE THREAD

**Issue by Kratik1093** [mdazfar2/Ezyshop#15]
### Description

want to add framer motion in home page

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me

**Comment by mdazfar2** [comment]
@lakshyeahh As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you. ***thank you***.
