### ISSUE TITLE
[Feat] Add a Password Visibility Toggle

### ISSUE THREAD

**Issue by Priyesh017** [mdazfar2/Ezyshop#154]
### **Add a password visibility toggle to the login page and also add a margin top to the Sign-in/Login card**

@mdazfar2  Assign me this issue under GSSoC'24-Extd and Hacktoberfest'24 to make my contribution count.

**Solve:**

- Add Password Visibility Toggle
- Add Margin Top to the Sign-in/Login Card

The Screenshot is provided below

### Screenshots

![Screenshot 2024-10-04 185034](https://github.com/user-attachments/assets/193f7619-9eea-4a05-8ca5-22c4bda937d3)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Priyesh017** [comment]
I have starred your repo and join your discord

Hope you will assign me to this issue as mentioned above under label GSSoC'24-Extd and Hacktoberfest'24

**Comment by mdazfar2** [comment]
Hey @Priyesh017 great issue found! You are going to be assigned.

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md).
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)

**Comment by Priyesh017** [comment]
@mdazfar2 The issue is fixed, could you help me contribute it as it's my first time contributing ?

**Comment by mdazfar2** [comment]
Hey @Priyesh017, no worries! It is very easy to contribute to open source. I will provide you with the guidelines below:

- Firstly you have to fork our [repo](https://github.com/mdazfar2/ezyshop)

- Then create [issue](https://github.com/mdazfar2/ezyshop/issue/) which you already raised.

- clone your fork repository and setup in your local machine and open terminal by which file you want to keep as see the below command.

```bash
 git clone https://github.com/priyesh017/ezyshop.git
```

- then all the Ezyshop project code will come in your file

- then changes from your vs code and complete the changes, open terminal and do the below commands

```bash
 git status
```

```bash
 git add .
```

```bash
 git commit -m "write your command here"
```

```bash
 git push origin main
```

- that's all good now open forked GitHub of `Ezyshop`

- Click on the `contribute` button 

- click on `Create new pull request`

- then write description and titile and scroll down and then final click again `create pull request`

- Congrats! 🥳 You've made your first pull request to this project repo.


---

Hope you understand if you stuck any where then you can react out to me on [Discord](https://discordapp.com/users/877531143610708028) or [Linkedin](https://linkedin.com/in/md-azfar-alam/).

**Comment by mdazfar2** [comment]
Hey @Priyesh017, no worries! It is very easy to contribute to open source. I will provide you with the guidelines below:

- Firstly, you have to fork our [repo](https://github.com/mdazfar2/ezyshop).

- Then create an [issue](https://github.com/mdazfar2/ezyshop/issue/) if you haven't already raised one.

- Clone your forked repository, set it up on your local machine, and open the terminal in the directory where you want to work. See the command below:

    ```bash
    git clone https://github.com/priyesh017/ezyshop.git
    ```

- The Ezyshop project code will be cloned to your local machine.

- Make changes in VS Code, and after completing the changes, open the terminal and run the following commands:

    ```bash
    git status
    ```

    ```bash
    git add .
    ```

    ```bash
    git commit -m "write your commit message here"
    ```

    ```bash
    git push origin main
    ```

- That's all good! Now open your forked GitHub repository of `Ezyshop`.

- Click on the `Contribute` button.

- Click on `Create new pull request`.

- Write the description and title, scroll down, and finally click `Create pull request`.

- Congrats! 🥳 You've made your first pull request to this project repo.

---

Hope you understand! If you get stuck anywhere, feel free to reach out to me on [Discord](https://discordapp.com/users/877531143610708028) or [LinkedIn](https://linkedin.com/in/md-azfar-alam/).

**Comment by Priyesh017** [comment]
After "git push origin main" it's showing an error:  "! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/Priyesh017/Ezyshop_Copy.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details." how to solve it ?

**Comment by Priyesh017** [comment]
The error is fixed by using "git push --force origin main"

**Comment by Priyesh017** [comment]
> Hey @Priyesh017 great issue found! You are going to be assigned.
> 
> * Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md).
> * And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)

@mdazfar2 Thank you for assigning me to this issue.
