### ISSUE TITLE
🚀 Migrate EzyShop Website to Next.js Framework

### ISSUE THREAD

**Issue by mdazfar2** [mdazfar2/Ezyshop#159]
## **Description**
Our current Ezyshop website, built with HTML & CSS, needs to be upgraded to **Next.js**, a serverless React framework. This transition will enhance performance, scalability, and backend functionality.

## We’re introducing a **Login/Signup** page with two distinct roles:
- **Store Manager** 🛍️: Manage store operations like inventory and orders.
- **Shopper** 🛒: For customers to browse, compare, and shop.

## **Task Breakdown**
We need to migrate each page of the current website to Next.js with full responsiveness and backend as well. To ensure clean and efficient code, create a **Pull Request (PR)** for each page ***one by one***, ensuring all functionality is preserved and optimized for the new framework. 

## **Contribution Guidelines**
- Use **Tailwind CSS** for styling to ensure a consistent and responsive design across the platform.
- Create a folder in the root directory named `Benjamin` and add all Next.js converted code there.
- Make sure to test each page thoroughly before submitting the PR.
- For each page, create a **Pull Request (PR)** one by one.
- After all the code is converted, we will remove the current HTML & CSS code and extract the contents of the `Benjamin` folder to the root directory.

Let’s take it step-by-step and make EzyShop even better with Next.js and Tailwind CSS!

**Comment by rimmon1234** [comment]
i will try to migrate about us to next js please assign me the task

**Comment by Bhum-ika** [comment]
I will fix the bug <Redirection to products page>
Kindly assign me this issue #181

**Comment by mdazfar2** [comment]
Sure @Bhum-ika go ahead with that hope you read the whole issue where and which file you have to keep the whole next.js file

- @rimmon1234 after completion of the homepage you can convert the About us page.

**Comment by mdazfar2** [comment]
@Bhum-ika feel free to reach out to me on [Discord](https://discordapp.com/users/877531143610708028) or [LinkedIn](https://linkedin.com/in/md-azfar-alam/).

**Comment by Bhum-ika** [comment]
Sure. Thankyou

**Comment by Sonuu20** [comment]
@mdazfar2 I'm willing to contribute to contribute to this, but currently there is no issue opened under. How can I contribute to this??

**Comment by mdazfar2** [comment]
@Bhum-ika Did you start the conversion? When will you create the PR?

**Comment by Bhum-ika** [comment]
I will create it by tomorrow noon positively.

**Comment by mdazfar2** [comment]
Hey @Bhum-ika please let me know

**Comment by Bhum-ika** [comment]
Kindly check the discord, i messaged you for the same. And also you closed it so I thought u don't want me to contribute anymore

**Comment by mdazfar2** [comment]
@Bhum-ika There is no message received on discord
