### ISSUE TITLE
[Feat] want to add hover effect on all buttons 

### ISSUE THREAD

**Issue by Kratik1093** [mdazfar2/Ezyshop#16]
### Description

currently the website dont have hover animation i want to add hover to itt

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me

**Comment by mdazfar2** [comment]
@Kratik1093 will let you know later.
