### ISSUE TITLE
[Feat] Redirect to dialer

### ISSUE THREAD

**Issue by pankaj-bind** [mdazfar2/Ezyshop#163]
### Description

I will update code so that when user clicks on phone number, it will redirect to email dialer pad.

### Screenshots

![{4F0BE289-7D5C-4B02-9E8A-A5FD4D6CE2E8}](https://github.com/user-attachments/assets/fd819128-4fb4-4d4b-8952-3cfbadcfa641)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@pankaj-bind, thank you for creating the issue.

I noticed that you've created two issues. You can combine the email and contact number issues into one issue template. This is not the correct way to work on open source.

As of now, we do not need this. We will let you know in the future if there is a need. Please search for another issue and raise it, and I'd be happy to assign it to you.
