### ISSUE TITLE
[BUG] Not similar box size ( customer reviews box ,   Latest article from blog )

### ISSUE THREAD

**Issue by Anshuaman2001** [mdazfar2/Ezyshop#169]
### Description

 size of the customer reviews box and  Latest article from blog and not similar their size is different from each other .

### Screenshots

![Screenshot 2024-10-05 025904](https://github.com/user-attachments/assets/844c54cb-e0a7-48d7-9a09-0b9cf1fb4997)
 all boxes are not of same length

![Screenshot 2024-10-05 025643](https://github.com/user-attachments/assets/b650ee07-dca2-4514-9ddb-100e6fa29858)
 all boxes are not of same length

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Anshuaman2001 go ahead

**Comment by mdazfar2** [comment]
@Anshuaman2001 you are assigned.

- please give ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)

**Comment by mdazfar2** [comment]
@Anshuaman2001 no response anything
