### ISSUE TITLE
[Feat]Show Password feature in login screen

### ISSUE THREAD

**Issue by 17arindam** [mdazfar2/Ezyshop#170]
### Description

there is no toggle to show and hide password due to which user can enter wrong password and they wont know that

### Screenshots

![image](https://github.com/user-attachments/assets/a7e5c846-1275-4931-9d59-aa4ae7e81622)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by 17arindam** [comment]
@mdazfar2 can you assign me this issue

**Comment by ChauhanAyush04** [comment]
@mdazfar2  assign me i will solve this also

**Comment by mdazfar2** [comment]
@17arindam You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
