### ISSUE TITLE
[Feat] Dark and Light Mode Toggle

### ISSUE THREAD

**Issue by Shreya-Pandey-01** [mdazfar2/Ezyshop#171]
### Description

If we add a feature where our customer can switch between light and dark mode it would certainly enhance the experience of our website even more.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Shreya-Pandey-01** [comment]
pls. assign this issue to me , I'll love to work on this and will complete it very quickly , and pls. assign the tags of gsscoc extd , level and hacktoberfest

**Comment by mdazfar2** [comment]
@Shreya-Pandey-01 we will let you know in future

**Comment by Shreya-Pandey-01** [comment]
ok sir
