### ISSUE TITLE
[BUG]  Header not in center, for other pages

### ISSUE THREAD

**Issue by Shreya-Pandey-01** [mdazfar2/Ezyshop#172]
### Description

The header like About,Contact of these pages doesn't seem vertically in middle , it seems more upward , I'll correct it align it perfectly 

### Screenshots

![issue](https://github.com/user-attachments/assets/47c19ea6-fb46-4571-9454-2f41917234c5)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Shreya-Pandey-01** [comment]
I'll love to work on this issue , pls. assign it to me , and pls. add all the necessary tags

**Comment by mdazfar2** [comment]
@Shreya-Pandey-01 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

**Comment by Shreya-Pandey-01** [comment]
Ok sir
