### ISSUE TITLE
Adding animation to the about us section

### ISSUE THREAD

**Issue by riyarane46** [mdazfar2/Ezyshop#173]
### Description

@mdazfar2 to make the home page more visually appealing i would like to add an animation that would make the about us section only to flow in from the left when any user scrolls down to the page . 
this will make the website look more interesting and attractive.

please assign me this issue and also assign level label . 

### Screenshots

![Screenshot 2024-10-05 084635](https://github.com/user-attachments/assets/1bcb150f-635a-4b9b-a235-b5acc334d300)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Koushik-Biswas** [comment]
Hi, I'd like to work on this issue. Please assign it to me.

**Comment by mdazfar2** [comment]
Hello @riyarane46 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
