### ISSUE TITLE
[BUG]  The reply button is not woking in blog details

### ISSUE THREAD

**Issue by Shreya-Pandey-01** [mdazfar2/Ezyshop#175]
### Description

make working reply button , so that viewers can also interact with each other in comments under blog

### Screenshots

![issue](https://github.com/user-attachments/assets/ff53f66b-2fc9-41f7-bf8a-7dde82ecce50)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Shreya-Pandey-01 Go ahead with that the reply button should work after the completion of login/signup and reflect username which we keep while creating account.

**Comment by Shreya-Pandey-01** [comment]
ok sir , I'll proceed as you have instructed

**Comment by mdazfar2** [comment]
Hey @Shreya-Pandey-01, please let me know if you are working on this issue, or if we need to close it or assign it to someone else.

**Comment by Shreya-Pandey-01** [comment]
No need to worry sir , I'm working on the issue

**Comment by Kavita1928** [comment]
@Shreya-Pandey-01 Is there any update?

**Comment by mdazfar2** [comment]
hello @Shreya-Pandey-01, I hope you are doing well!

- It has been 2 days, and you haven't responded to anything. Unfortunately, I have to close this issue because there are many duplicate issues raised. Thank you.

**Comment by Shreya-Pandey-01** [comment]
No sir , it's almost done , I'll complete it by today night

**Comment by Shreya-Pandey-01** [comment]
ok sir , you can reassign this to someone , as it needs integration with backend also , and with my current knowledge , I can implement only frontend ,but will be unable to integrate it with expressJS

**Comment by mdazfar2** [comment]
Okay, @Shreya-Pandey-01, no problem! Don't get discouraged. You're a great developer, and I appreciate your hard work.

**Comment by Shreya-Pandey-01** [comment]
Thank you sir for kind words.
