### ISSUE TITLE
adding add to cart option on website 

### ISSUE THREAD

**Issue by Janhavi078** [mdazfar2/Ezyshop#176]
### Description

website does not contain a simple basket box that shows you added an items in a website i can add that items showing on website
please assign me this issue under hacktoberfest and gssoc24 ext @mdazfar2 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Janhavi078 in which you put the added add to cart option please let me know

**Comment by Janhavi078** [comment]
@mdazfar2 sir when we add some items in cart it just shows added to cart there is no actual cart present so i want to added that with logo and functions

**Comment by mdazfar2** [comment]
@Janhavi078 No if you add the cart option then it must be  functional and working fine

**Comment by Janhavi078** [comment]
Yes I will do it that

**Comment by mdazfar2** [comment]
@Janhavi078 you are assigned.

**Comment by mdazfar2** [comment]
@Janhavi078 btw tell me in which place you keep the cart icon in website??

**Comment by Janhavi078** [comment]
Right side

**Comment by mdazfar2** [comment]
Send me the screenshot and mark with red color

**Comment by Janhavi078** [comment]
![Screenshot_20241005_125817_Chrome.jpg](https://github.com/user-attachments/assets/ef562f77-1e1c-400c-8a78-c875fb9f027c)

There I can

**Comment by Janhavi078** [comment]
What happened is it not assigned to me @mdazfar2
