### ISSUE TITLE
Enhancement Of aboutus page

### ISSUE THREAD

**Issue by rimmon1234** [mdazfar2/Ezyshop#179]
About us Page Has Needs Some Optimization And Fixes like  SEO Enhancements,Code Structure and Consistency,Usability Enhancements 

And Also Exclusive Discounts & Offers Section is a bit bigger than other sections which looks odd
![EzyshopFix](https://github.com/user-attachments/assets/238b75ac-fa88-40a9-b325-a06316dba3ea)

Please Assign Me The Task I Would Like To Work On It @mdazfar2

**Comment by mdazfar2** [comment]
Hey @rimmon1234 will let you know later about that actually we are converting code to next.js after that we optimize out code. can you convert the code please look at the issue #159.

**Comment by rimmon1234** [comment]
Ok Then i will try to convert it to next js you can assign me

**Comment by mdazfar2** [comment]
Comment on that issue. Hope you have read everything in that issue, including which file you need to convert the code in. Please reply on #159, which I assigned to you.
