### ISSUE TITLE
[Feat] wants to create contact us page 

### ISSUE THREAD

**Issue by Kratik1093** [mdazfar2/Ezyshop#18]
### Description

currently the contact us page does not exist I want to create the page for you 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Kratik1093 It already exists please check again.
