### ISSUE TITLE
[BUG] Redirection to products page 

### ISSUE THREAD

**Issue by Bhum-ika** [mdazfar2/Ezyshop#181]
### Description

When clicked on "Start Shopping" button, the website should take user to the part of the home page where categories of products are listed. I will fix it
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @Bhum-ika! Do you want to work on issue #159 please let me know.

**Comment by Bhum-ika** [comment]
Yes, I would like to.

**Comment by mdazfar2** [comment]
@Bhum-ika Comment on that issue. Hope you have read everything in that issue, including which file you need to convert the code in. Please reply to #159, which I assigned to you.

**Comment by Bhum-ika** [comment]
Commented

**Comment by mdazfar2** [comment]
Hey @Bhum-ika are there please let me know if you are interested.

**Comment by Bhum-ika** [comment]
I have commented where you asked me to. I am interested. 
Please assign it to me
