### ISSUE TITLE
[Feat]social login

### ISSUE THREAD

**Issue by Tanyashri** [mdazfar2/Ezyshop#182]
### Description

As I observed there's no social login feature in the login page. So i'd like to contribute by adding the social login feature in the login page

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Tanyashri you mean you want to add authentication in html css right??

**Comment by Princeag1310** [comment]
Yes, I want to do it.

**Comment by Princeag1310** [comment]
Please assign me this issue

**Comment by mdazfar2** [comment]
@Tanyashri I apologize, but I need to close this issue for now. Please don't be discouraged!
