### ISSUE TITLE
[Feat] I want to add some effect from css in home page

### ISSUE THREAD

**Issue by Dipanita45** [mdazfar2/Ezyshop#183]
### Description

I want add hover effect on the choices when it is being used to make it attractive

### Screenshots

![Screenshot 2024-10-05 123018](https://github.com/user-attachments/assets/7ad7f6d8-c335-43bf-a1dc-5d1267080b3a)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Dipanita45 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- please give ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
