### ISSUE TITLE
Google firebase authentication while login/signup

### ISSUE THREAD

**Issue by riyaaryan2004** [mdazfar2/Ezyshop#185]
### Feature Description
I want to add Google firebase authentication.
I will add google button "continue wit google"

### Use Case
User don't have to enter gmail password everytime they login.
User can directly login their account with existing google account in their browser

### Benefits
This feature give smooth user experience and an option of easy signup/login

### Screenshots

![Screenshot 2024-10-05 132431](https://github.com/user-attachments/assets/7d16e600-6906-47ea-a0d0-15cd526bf262)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [x] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@riyaaryan2004 Is it possible to add this with html, css?

**Comment by riyaaryan2004** [comment]
Yes @mdazfar2  I have added this in many projects.. just using raw  html , css and js file.
You have to create a firebase project for this web app. and provide the firebase credential..
You can give this after I complete  google sing in button and related function.
You can assign me this project with gossoc-ext and other lables.

**Comment by mdazfar2** [comment]
@riyaaryan2004 Actually, we are converting this project to Next.js, so after that, can you please wait and then add the authentication?

**Comment by riyaaryan2004** [comment]
@mdazfar2 Okay you can assign me after. I would be great to work with existing libraries

**Comment by mdazfar2** [comment]
Sure @riyaaryan2004 

- Please don't forget to give star ⭐ us
