### ISSUE TITLE
adding add to cart option on website 

### ISSUE THREAD

**Issue by Janhavi078** [mdazfar2/Ezyshop#186]
### Description

website does not contain a simple basket box that shows you added an items in a website i can add that item in a website please assign me this issue under hactoberfest and gssoc24 @mdazfar2 

### Screenshots

![Screenshot (6)](https://github.com/user-attachments/assets/fe7feabe-0409-4f01-a56e-4b49d8610455)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Janhavi078 can you please describe it again what exactly you want to contribute to our project?

**Comment by Janhavi078** [comment]
I want to make shopping cart 🛒 for adding options to it ....fully functional can you assign it to me again ..under gssoc hactoberfest @mdazfar2

**Comment by mdazfar2** [comment]
@Janhavi078 you are assigned.

**Comment by mdazfar2** [comment]
hey @Janhavi078 I hope you are doing well!

- It has been a day and you haven't responded to anything. Unfortunately, I have to close this issue because there are many duplicate issues raised. Please don't be discouraged. Thank you.
