### ISSUE TITLE
UI Consistency Enhancement: Standardize Button Text, Spacing, and Box Heights for Improved Design

### ISSUE THREAD

**Issue by ragini-gp** [mdazfar2/Ezyshop#187]
### Description

The current layout contains the following inconsistencies that affect the overall design and user experience:
**Button Text Inconsistency**: The first two sections display a "**Shop Now**" button, while the third section displays "**Order Now.**" To maintain uniformity and improve user interface clarity, all buttons should have the same label, such as "**Shop Now**."
![image](https://github.com/user-attachments/assets/c35a5ea5-8df8-41f0-84b1-7c7fa93f857a)

**Excessive Padding/Margin**: There is an unnecessary amount of space on the left and right sides of the content, leading to an uneven layout. 
![image](https://github.com/user-attachments/assets/94abef19-3a5f-48ad-8a06-b395ed9dcd6f)

This should be adjusted to ensure optimal use of space and alignment, to look like this
![image](https://github.com/user-attachments/assets/aad7ce3e-4634-401e-aaea-2a40d60fa9c2)

**Uneven Box Heights**: The boxes currently have inconsistent heights, which creates visual imbalance. 
![image](https://github.com/user-attachments/assets/2cab2866-a3e8-4423-829e-f4bbaceca099)
All boxes should be equal in size to provide a more polished and uniform appearance like this
![image](https://github.com/user-attachments/assets/7eda96dd-1d19-409a-ba00-abd68327d422)

Please assign me this issue under gssoc-ext, hacktoberfest-accepted, with level.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ragini-gp I apologize, but I need to close this issue for now. Please don't be discouraged!

**Comment by ragini-gp** [comment]
But, the reason for it ?

**Comment by mdazfar2** [comment]
@ragini-gp It's been two days, and you haven't responded to anything, that's why.

**Comment by ragini-gp** [comment]
Sorry, but I raised the issue on Saturday, and was waiting for it to be assigned.
