### ISSUE TITLE
[BUG] Fix inconsistent border-radius for input fields across all forms

### ISSUE THREAD

**Issue by kavya410004** [mdazfar2/Ezyshop#189]
### Description

There is a styling issue where the input fields across various forms on the website have a border-radius applied only to the top-left and bottom-left corners. This creates an uneven and inconsistent appearance in the form fields. There seems to be clash in the styling for form input fields and search input field.

**Expected Behavior:** All corners (top-left, top-right, bottom-left, and bottom-right) of the form input fields should have the same border-radius for a balanced and consistent appearance.

Please assign this issue to me, I would like to work on this.

### Screenshots

![image](https://github.com/user-attachments/assets/17829c98-29af-47da-8046-73c3e0e261e1)
![image](https://github.com/user-attachments/assets/34c72990-762e-4c54-a6c0-c0ebcd7f0e57)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@kavya410004 you are assigned.

**Comment by kavya410004** [comment]
@mdazfar2 Thank you for assigning, I will start working on it.
