### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by S7viks** [mdazfar2/Ezyshop#19]
### Description

Alignment issue with boxes.

### Screenshots

![Screenshot 2024-10-01 215729](https://github.com/user-attachments/assets/ab1107d9-e9c0-4aef-8213-6ca476a8562a)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by S7viks** [comment]
I would like to work on this, please assign gssoc label and level label

**Comment by mdazfar2** [comment]
@S7viks go ahead.
