### ISSUE TITLE
[Doc]: Enhance Navigation Bar Design with Transform Effects and Improved Typography

### ISSUE THREAD

**Issue by Renu1418** [mdazfar2/Ezyshop#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I would like to propose enhancements to the navigation bar to improve the user experience and visual appeal. The changes I plan to implement include:

Font Size Adjustment: Increase the font size for better readability and accessibility.
Transform Effects:
Add a subtle transform effect to the nav bar items on hover to scale them up slightly, providing a more interactive feel.
Shadow Effect: Add a slight shadow effect to the nav items to create depth and separation from the background.
Smooth Transition: Use CSS transitions to ensure that all changes occur smoothly for a better user experience.
I believe these enhancements will make the navigation bar more engaging and user-friendly. I am excited to contribute and would love to take this issue on!

### Suggested Change

Font Size Adjustment: Increase the font size for better readability and accessibility.
Transform Effects:
Add a subtle transform effect to the nav bar items on hover to scale them up slightly, providing a more interactive feel.
Shadow Effect: Add a slight shadow effect to the nav items to create depth and separation from the background.
Smooth Transition: Use CSS transitions to ensure that all changes occur smoothly for a better user experience.
I believe these enhancements will make the navigation bar more engaging and user-friendly. I am excited to contribute and would love to take this issue on!

### Rationale

I would like to propose enhancements to the navigation bar to improve the user experience and visual appeal.

### Urgency

Medium

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [ ] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hey @Renu1418 thank you for creating the issue.

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
