### ISSUE TITLE
[Feat]Dark mode toggle feature.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [mdazfar2/Ezyshop#193]
### Description

A dark mode feature can be added to improve the overall User experience with background theme.

@mdazfar2 can you please assign me this task , i would love to fix this issue.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @T-Rahul-prabhu-38 Thank you for raising the issue 

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

**Comment by T-Rahul-prabhu-38** [comment]
can i improve the UI of this  , @mdazfar2  
<img width="563" alt="Screenshot 2024-10-05 at 7 20 43 PM" src="https://github.com/user-attachments/assets/476c408d-e309-4e81-98dd-048e072db050">

**Comment by mdazfar2** [comment]
Actually @T-Rahul-prabhu-38, we are converting the code to Next.js, so after that, you can change the UI. Do you want to contribute to us using the Next.js framework?


- please don't forget to give Star ⭐ us
