### ISSUE TITLE
Add Google Login/Sign Up Option to Authentication Pages

### ISSUE THREAD

**Issue by ritiksingh-01** [mdazfar2/Ezyshop#195]
### Description

I kindly request to be assigned this issue to enhance the login and sign-up pages by adding a Google authentication option and a "Forgot Password" feature. These improvements will provide users with:

- **Faster Authentication:** Google login allows users to sign in quickly without creating new credentials.
- **Enhanced Security:** OAuth authentication ensures secure access.
- **Convenience:** Reduces the need to remember multiple passwords, making the process user-friendly.
- **Password Recovery:** The "Forgot Password" feature enables users to reset their password easily, improving account recovery and security.

These features will enhance user experience, security, and convenience.

Kindly assign this issue to me under the GSSoC'24-Extd.

Thank you for considering my request.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by AhanaGanguly965** [comment]
I want to work on this issue.Can u assign me this?

**Comment by mdazfar2** [comment]
hey @ritiksingh-01 You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
- Don't forget to give star.
