### ISSUE TITLE
[Feat]Add Forgot Password Feature On Login Screen

### ISSUE THREAD

**Issue by K-Rasti** [mdazfar2/Ezyshop#196]
### Description

Users often forget their passwords. Providing a quick, easy way to recover or reset it reduces frustration and ensures they can regain access without contacting support.

I **want to add Forgot Password functionality** on Login Screen. I would be grateful if you assign me this issue under gssoc-ext..My GitHub username is @K-Rasti.

### Screenshots

![image](https://github.com/user-attachments/assets/f53044a0-8ee4-4549-b4f3-f80e5ceb9c42)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@K-Rasti assigned

**Comment by PrAyAg9** [comment]
@Kavita1928 #196 Solved in pull request #366, Could you please assign this issue to me first and then approve my pull request as I have solved this issue.

**Comment by mdazfar2** [comment]
hey @PrAyAg9 please update sync fork and let me know
