### ISSUE TITLE
[Feat] Add Hover Effect in Article and product cards  

### ISSUE THREAD

**Issue by ratna-jaiswal** [mdazfar2/Ezyshop#198]
### Description

As there is no hover effect present previously .Adding hover effect is making contents more attractive  

https://github.com/user-attachments/assets/f9e7a895-23ff-4037-afe2-16d3eea6c411

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@ratna-jaiswal  assined, you can work on this issue
