### ISSUE TITLE
[BUG] Navbar Visibility Issue on Shops Page

### ISSUE THREAD

**Issue by kavya410004** [mdazfar2/Ezyshop#199]
### Description

I noticed that the navbar is only displaying the nav item **Shops** on the Shops page, and it is not visible on any other pages. As a result, users can only access the shop by clicking the Shop Now button in the category page or the Explore Shops button. And also the dropdown menu named **Pages** is not appearing in the navbar on the Shops page.

**Expected Behavior:** The navbar should display consistently across all pages, allowing users to navigate easily. The Pages dropdown menu should also be visible on the Shops page.

### Screenshots

**Navbar in shops page: (Pages dropdown option not visible)**
![image](https://github.com/user-attachments/assets/099f4db4-cfbf-42ad-8ba4-127764b19ae6)

**Navbar in all other pages: (Shops option not visible)**
Home page:
![image](https://github.com/user-attachments/assets/f6c45a20-36fe-4cba-b36f-43b7ea43aaa7)
About page:
![image](https://github.com/user-attachments/assets/1e757e19-3a72-475a-bc84-6f15c240359c)
Categories page:
![image](https://github.com/user-attachments/assets/0e195948-05f7-4bfc-b94b-d0685e0f3128)
Teams page:
![image](https://github.com/user-attachments/assets/7f10e4dd-6f8a-4154-aa01-98e3f79eb834)
Contact page:
![image](https://github.com/user-attachments/assets/68f997ba-a2d6-4038-bfdb-1a6b343521f0)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hey @kavya410004 It is already solved by someone try to find any other issue or bugs. Thank you
