### ISSUE TITLE
[BUG] . Header Not Sticky When Scrolling

### ISSUE THREAD

**Issue by NikitaYewale007** [mdazfar2/Ezyshop#2]
### Description

The header in the Ezyshop project does not remain fixed at the top of the viewport while scrolling, leading to a poor user experience. When users scroll down the page, the header disappears, making navigation difficult.

Expected Behavior:
The header should remain sticky at the top of the viewport while scrolling, allowing users to easily access navigation links.

I would like to work on this issue and implement a fix for the sticky header. Please assign this task to me.

### Screenshots

![Screenshot 2024-10-01 182744](https://github.com/user-attachments/assets/e18e7e51-8302-4933-8e3f-d16d1414d57a)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ParasY1724** [comment]
Please Assign this task to me  under gssoc-extd24 , i have worked on similar bug before.Thanks!!

**Comment by riyaaryan2004** [comment]
assign this issue to me. I will fix the problem of scrolling header.

**Comment by NikitaYewale007** [comment]
### could you pls assign this task to me @mdazfar2, i have worked on similar bug before.Thanks!!

**Comment by NikitaYewale007** [comment]
Thank you for acknowledging the issue Please let me know if there's anything specific I should keep in mind.

**Comment by rishabhhverma** [comment]
I would like to resolve this issue by implementing a sticky header. Kindly assign this task to me.

**Comment by thakuratul2** [comment]
@mdazfar2 Hii i am the mentor of your project can you please give me the access to review code easily.

**Comment by riyaaryan2004** [comment]
assign this project to me as well.
I have worked on this before .

**Comment by AyutheCoder** [comment]
Can you please assign this work to me,I can fix this issue

**Comment by thakuratul2** [comment]
@AyutheCoder Assigned task to you and Create the PR and assigned to me as a reviewer

**Comment by mdazfar2** [comment]
@NikitaYewale007 It has been 2 days and you haven't responded to anything. Unfortunately, I have to close this issue because there are many duplicate issues raised. Please don't be discouraged. Thank you.
