### ISSUE TITLE
[Feat] create login page and animated buttons all cross the pages.

### ISSUE THREAD

**Issue by anish013326** [mdazfar2/Ezyshop#20]
### Description

Create a responsive login page with animated buttons across pages using HTML, CSS, and JavaScript. Implement smooth hover effects, button transitions, and animations to enhance user interaction and experience.

### Screenshots

![Screenshot 2024-10-01 225404](https://github.com/user-attachments/assets/909b3e09-7fe8-4bbc-ab21-8ccd8b29ee79)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hey @anish013326 Thank you for raising the issue.

- You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)

**Comment by anish013326** [comment]
Hi @mdazfar2 ,

Thank you for bringing this to my attention. I apologize for raising a duplicate issue; I didn’t realize it had already been reported. As this is my first time contributing to an open-source project, I’m still learning the best practices for issue tracking.

I’ll make sure to review existing issues more carefully in the future to avoid this mistake. I appreciate your guidance, and I’m eager to improve my contributions as I continue my journey in open source.

Thanks for your understanding!

Best,
Anish
