### ISSUE TITLE
[Feat]Adding hover effect and animations in home page cards

### ISSUE THREAD

**Issue by Subashree-selvaraj** [mdazfar2/Ezyshop#200]
### Description

Idea is to add animation and hovering effect to the below section:

### Screenshots

![Screenshot 2024-10-05 213230](https://github.com/user-attachments/assets/53d4fd33-3eb0-486e-97c9-474807c93451)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Subashree-selvaraj As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
