### ISSUE TITLE
[BUG] NavBar has more width than other sections

### ISSUE THREAD

**Issue by vedant3337** [mdazfar2/Ezyshop#201]
### Description

NavBar has more width than other sections on home page on mobile screens. 

I will fix this.

**Please assign me this issue and label gssoc-ext, hacktoberfest**

### Screenshots

![SmartSelect_20241005_214442_Chrome](https://github.com/user-attachments/assets/59737f64-b8f3-4b82-af66-558ef75556fe)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@vedant3337 go ahead

**Comment by Kavita1928** [comment]
@vedant3337  any update ?

**Comment by mdazfar2** [comment]
@vedant3337 I apologize, but I need to close this issue for now. Please don't be discouraged! Try to create a new issue, which we would be happy to assign to you. Thank you!

- Please don't forget to give us a star.
