### ISSUE TITLE
[BUG] To change the twitter logo to X logo

### ISSUE THREAD

**Issue by Pavan8421** [mdazfar2/Ezyshop#202]
## Please assign me this issue under gssoc-ext and hacktoberfest.
@mdazfar2 @thakuratul2 @Kavita1928 

### Screenshots

![Screenshot 2024-10-05 214426](https://github.com/user-attachments/assets/db9bb866-8834-4cdb-833d-3fce4b97b6d7)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@Pavan8421 Do it

**Comment by Pavan8421** [comment]
please add the level tag

**Comment by mdazfar2** [comment]
@Pavan8421 solved will closing the issue. please don't forget to give star us thank you
