### ISSUE TITLE
[Feat] Want to add search functionality option at categories section

### ISSUE THREAD

**Issue by Pavan8421** [mdazfar2/Ezyshop#203]
## Please assign me this issue under gssoc-ext and hacktoberfest.

@thakuratul2 @mdazfar2 @Kavita1928 

### Screenshots

![Screenshot 2024-10-05 215726](https://github.com/user-attachments/assets/5e214814-f20e-4611-b078-c1d454ac8faf)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Pavan8421 thank you for raising the issue.

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Please give star us ✨
