### ISSUE TITLE
[Doc]: Add hover effects

### ISSUE THREAD

**Issue by Mahima-2404** [mdazfar2/Ezyshop#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Add hover effects  and ezyshop logo

### Suggested Change

Add transition through css by hover effects

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Go ahead @Mahima-2404
