### ISSUE TITLE
[Feat] ADD TOGGLE BUTTON for dark/light modes

### ISSUE THREAD

**Issue by laxmikandivalasa** [mdazfar2/Ezyshop#205]
### Description

A toggle button can enhance the website more attractive..
@mdazfar2 can you assign this to me??
I'd love to contribute!!

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by laxmikandivalasa** [comment]
I had an idea like this... @mdazfar2 
If you assign I'd love to add this feature
![Screenshot 2024-10-05 234037](https://github.com/user-attachments/assets/ef63c243-56ec-46e1-973e-27ca357994e6)
![Screenshot 2024-10-05 234051](https://github.com/user-attachments/assets/8b92c3ed-0188-409e-aa12-76da6f9151cb)

**Comment by mdazfar2** [comment]
Hey @laxmikandivalasa, please don't be discouraged, but you shouldn't do it like this. Below, I'll show you what you should avoid:

1. You created a Pull Request without assigning your issue, which is not the correct way to work on open source.
2. I apologize, but I need to close this PR for now.
4. Next time, please keep this in mind. I'm not trying to instruct you; I'm just trying to provide the correct steps to work on open source.

- Thank you!

**Comment by laxmikandivalasa** [comment]
Hello mentor!
Can you confirm that I've sent a pull request?

**Comment by laxmikandivalasa** [comment]
Mentor!
I guess I just raised an issue!!
