### ISSUE TITLE
[BUG] Change the twitter logo to X 

### ISSUE THREAD

**Issue by rupeshv2121** [mdazfar2/Ezyshop#206]
### Description

Twiiter logo seen in this is became old fashion. I want to change to the current scenario which is "X" symbol logo
Please assign this under gssoc'24-ext and hacktoberfest

### Screenshots

![Ezyshop](https://github.com/user-attachments/assets/e0f68ad1-7998-44aa-8dfb-0e0b9d9bcfb9)

### What browser are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ChauhanAyush04** [comment]
@mdazfar2  assign me. i will solve it

**Comment by Kavita1928** [comment]
@rupeshv2121 this issue has been already created by someone else So you can create some other issue or can work on someone's

**Comment by rupeshv2121** [comment]
@Kavita1928 My issue is different check first

**Comment by rupeshv2121** [comment]
@mdazfar2 sir pls assign me asap so that i can work on it

**Comment by mdazfar2** [comment]
@rupeshv2121, this is not the correct way to work on open source. If Kavita says that the issue is a duplicate, then you must agree. You are mentioning it again and again; please don't do that again.

- I am not instructing you; I am just trying to show you the correct path to work on open source. Thank you!
- Hope you star us.

**Comment by rupeshv2121** [comment]
@mdazfar2 Sir can you pls check in the issue section , no one raise issue where i m raise , everyone raise in the footer section but i raise in the page section 
Pls check my issue is not duplicate 
Hope u understand what i m telling

**Comment by mdazfar2** [comment]
@rupeshv2121 Issue reopened. Do one thing, instead of the Twitter icon, add `GitHub`, and instead of Facebook, add `LinkedIn`. For the third icon, add the `link icon`, which will insert my portfolio link. You can get all my social links from my [GitHub profile](https://github.com/mdazfar2/).

**Comment by rupeshv2121** [comment]
I make the PR 
pls Add label hacktoberfest-accepted and gssoc-ext

**Comment by rupeshv2121** [comment]
Sir pls merge my PR

**Comment by rupeshv2121** [comment]
Sir pls add label hacktoberfest-accepted
