### ISSUE TITLE
Improve Scroll Bar UI

### ISSUE THREAD

**Issue by VidhanThakur09** [mdazfar2/Ezyshop#207]
### Description

The current Scroll bar Ui has a very basic layout and outdated design. The Thumb and Track has outdated and default styling. Enhancing the colour scheme of Thumb and Track, improving spacing and modernizing the scroll bar design would greatly improve the user experience and website presentation

### Screenshots

https://github.com/user-attachments/assets/006ffc37-48cf-4d95-80fd-97777ad10162

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hello @VidhanThakur09 thank you for creating the issue.

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
- Please don't forget to give star us.

**Comment by VidhanThakur09** [comment]
Thank you for your time. I will inform you if I encounter any issue.
