### ISSUE TITLE
[Feat] Hover effects to the card 

### ISSUE THREAD

**Issue by rupeshv2121** [mdazfar2/Ezyshop#209]
### Description

I think it is looking better when we add hover effect over the cards. This give best User experience.

### Screenshots

![Hover effect](https://github.com/user-attachments/assets/eadf1214-e3d2-4444-aadb-04608fae3f56)
![Hover effect-2](https://github.com/user-attachments/assets/ae7f5c21-22d5-4e86-bb43-59ed9dca96e9)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
