### ISSUE TITLE
[BUG] PADDING OF THE FOOTER IS NOT UP TO THE MARK

### ISSUE THREAD

**Issue by Risheendra183** [mdazfar2/Ezyshop#21]
### Description

adding a bit more bottom padding to the footer, so the design doesn't feel too "tight" against the bottom edge of the browser.

### Screenshots

![image](https://github.com/user-attachments/assets/a09d17ea-07b7-4521-9139-368866c038c3)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by DivyaJyothi9** [comment]
Hello! I would like to take on the issue of adjusting the footer padding, as it is not currently up to the mark. Improving the footer’s padding will enhance the overall layout and user experience. Please assign this issue to me. Thank you!

**Comment by thakuratul2** [comment]
@DivyaJyothi9 acknowledged

**Comment by DivyaJyothi9** [comment]
> @DivyaJyothi9 acknowledged

Thank you sir

**Comment by Divyansh2992** [comment]
i want to contribute in it.Please assign it to me.

**Comment by mdazfar2** [comment]
@Risheendra183 It is all right thank you for your issue.

- Don't forget to join our official [Discord server](https://discord.gg/SEzpxqQG).
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
- And please ⭐ our repo

**Comment by mdazfar2** [comment]
hey @Risheendra183 I hope you are doing well!

- It has been 2 days and you haven't responded to anything. Unfortunately, I have to close this issue because there are many duplicate issues raised. Please don't be discouraged. Thank you.
