### ISSUE TITLE
[BUG] Alignment Of Contact Us and extra space in footer

### ISSUE THREAD

**Issue by rupeshv2121** [mdazfar2/Ezyshop#210]
### Description

Contact Us written is not align to center, In footer section copyright written takes to much space , I want to reduce that space which is good for user experience

### Screenshots

![footer](https://github.com/user-attachments/assets/837a8902-7e7c-4e1b-af91-969da198b71d)

![contact us alignment](https://github.com/user-attachments/assets/56b884eb-8843-4aa2-9672-692c2c1747e0)

### What browser are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@rupeshv2121 you are assigned.

**Comment by rupeshv2121** [comment]
I make the PR
