### ISSUE TITLE
[Feat] Footer Section needs Adjustment

### ISSUE THREAD

**Issue by Abhi9shinde** [mdazfar2/Ezyshop#212]
### Description

The footer section is way too wide and needs to be slick and appealing.
As seen in the screenshot below it covers up almost whole window

### Screenshots

![image](https://github.com/user-attachments/assets/8930900d-25de-4d5b-b4de-33b637ef5236)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Abhi9shinde, please share a screenshot of how you made it appealing. It would be great if you share the screenshot, as it will help me assign the issue to you.

**Comment by Abhi9shinde** [comment]
Original :
![Screenshot 2024-10-06 123931](https://github.com/user-attachments/assets/e671bac7-d380-4cc8-b02a-d148e5eaf27f)

Updated:
![Screenshot 2024-10-06 123916](https://github.com/user-attachments/assets/d62adf55-b9ad-4e43-b55a-48950591031d)

Changes made:
1. Adjusted the social media logos at the center.
2. Proper distribution of all the information in footer section.
3. Reducing the size of the footer so that it doesnt cover whole page.

You can also suggest some more changes.

**Comment by mdazfar2** [comment]
@Abhi9shinde Alright! You are assigned. 

- Make the changes on every page on footer.

**Comment by Abhi9shinde** [comment]
Sir, I have made changes in all web pages and also created PR please review it and merge.
Thank you

**Comment by mdazfar2** [comment]
Hello @Abhi9shinde, please mention your issue number in your PR so we know that this PR is created for that issue. Hope you understand.

**Comment by Abhi9shinde** [comment]
yes @mdazfar2 , I have raised PR and mentioned the issue number in the description.
Sorry for the inconvenience that I caused earlier!
