### ISSUE TITLE
[BUG] Start Shopping Button

### ISSUE THREAD

**Issue by Princeag1310** [mdazfar2/Ezyshop#213]
### Description

I want to fix the "Start Shopping" Button.
As we click on the start shopping button, it didn't go to anywhere. 
I fix it as it goes to other webpage of shopping.
Assign me this issue.

### Screenshots

<img width="839" alt="Screenshot 2024-10-06 at 12 55 18 AM" src="https://github.com/user-attachments/assets/8ff136ba-9624-4f24-9cc4-e6dc2606555c">

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@Princeag1310 which webpage you want it to go?

**Comment by thakuratul2** [comment]
@Kavita1928 assgined

**Comment by Princeag1310** [comment]
I want it to go the the shopping items page.

**Comment by Princeag1310** [comment]
assign me this issue

**Comment by mdazfar2** [comment]
@Princeag1310 I apologize, but I need to close this issue for now. Please don't be discouraged!
