### ISSUE TITLE
[Feat] Add a Hover Effect on the Buttons in the Sign-in/Login Card

### ISSUE THREAD

**Issue by Priyesh017** [mdazfar2/Ezyshop#214]
### **Add a Hover Effect on the Buttons in the Sign-in/Login Card**

@muhafiz5814 Please assign me this assign.

**Enhancement:**

- Add a Hover Effect on the Buttons to make them more interactive.

### Screenshots

![Screenshot 2024-10-06 014119](https://github.com/user-attachments/assets/9572136e-ce87-4764-920a-5618c6f79518)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@Priyesh017  assigned

**Comment by Priyesh017** [comment]
Hey @Kavita1928, can you kindly add a Level 1 label to this issue if possible.

**Comment by tanishirai** [comment]
Can i work on this issue?

**Comment by Kavita1928** [comment]
@Priyesh017 have you completed ?

**Comment by Priyesh017** [comment]
> @Priyesh017 have you completed ?

I need two days more.

**Comment by mdazfar2** [comment]
Hey @Priyesh017, for now, I will close this issue. Please don't feel discouraged. You are a very-very-very good developer. I will make sure to assign you new issues, bugs, or features that are really needed for our website. Thank you.

**Comment by Priyesh017** [comment]
> Hey @Priyesh017, for now, I will close this issue. Please don't feel discouraged. You are a very-very-very good developer. I will make sure to assign you new issues, bugs, or features that are really needed for our website. Thank you.

It's okay, I'm looking forward to it.
