### ISSUE TITLE
[BUG] not redirect at home page 

### ISSUE THREAD

**Issue by anish013326** [mdazfar2/Ezyshop#215]
### Screenshots

![image](https://github.com/user-attachments/assets/2b66d785-ffd1-40b5-8f0e-67fdeeae5f5f)

### Any additional information?

Adding functionality like mouse movement tracking

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@anish013326 we are showing only the path and nothing else. If the user wants to go to the homepage, they can tap on the logo as well.

- Please don't forget to give a star on the repo.

**Comment by anish013326** [comment]
#### If there's any work or task available, please feel free to assign it to me. I'm ready to assist!

**Comment by mdazfar2** [comment]
Sure, @anish013326, I will mention you if there is any work. Can you please tell me if you have ever worked with Next.js?
