### ISSUE TITLE
[Feat]  Tracking Mouse Movement Using JavaScript

### ISSUE THREAD

**Issue by anish013326** [mdazfar2/Ezyshop#216]
### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@anish013326 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Please star us

**Comment by anish013326** [comment]
#### Thank you for letting me know. I appreciate the update, and I’m happy to assist with any future issues. I will keep an eye out for other opportunities and raise any relevant matters when they arise
