### ISSUE TITLE
UI Improvements for the Category Cards

### ISSUE THREAD

**Issue by Abbas7120** [mdazfar2/Ezyshop#217]
From this 💯 

![image](https://github.com/user-attachments/assets/8ddfcdba-1fce-47bb-8e9c-0aecfb65010c)

To this 👍 { Just OnlyUI of Cards Section changes not other things  }

![image](https://github.com/user-attachments/assets/caa3ce51-cce0-4333-8d8c-32e1c80f2b4d)

Hi  @mdazfar2  ,

I hope this message finds you well. I would like to request permission to take on the issue regarding UI improvement of Category Cards . 
Add prominent discount banners inside each card (e.g., “UP TO 70% OFF” or “50-80% OFF”), using large, bold typography with contrasting colours that make the text pop. Ensure the offer text stands out with a clear and modern font similar to how Myntra uses product-related styling that are visually engaging. Align the image above the offer text to create a cleaner look. 

I believe I can contribute effectively to this project and help enhance user engagement.

Please assign me this issue with "hacktoberfest" "hacktoberfest-accepted" "gssoc-extd" "level-1" labels to make more confident towards Open Source .

Please let me know if I can proceed with this issue. I appreciate your consideration!

Best regards,
Abbas

**Comment by mdazfar2** [comment]
@Abbas7120 great issue found, but remember not to use downloaded images. Try to create images using AI or DALL·E if you're adding new ones.

- please give ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)

**Comment by Rishikagoyal** [comment]
Hi @mdazfar2 

I would like to make a carousel of cards with better typography that looks more appealing. Please assign me this issue with "gssoc-extd" and "hacktoberfest.".

<img width="953" alt="Screenshot 2024-10-07 122017" src="https://github.com/user-attachments/assets/176f9644-a2f4-472d-ad64-98a5dc3ac87c">


Thanks 
Rishika Goyal

**Comment by Abbas7120** [comment]
But I made this issue first and it's resolved now just only merging
required
