### ISSUE TITLE
Add a myorder option , trackorder , edit order  , wishlist at the navbar

### ISSUE THREAD

**Issue by prvn-kumar01** [mdazfar2/Ezyshop#219]
add a my order option and wishlist option for better user interection 
by adding this user can aesily access their items

**Comment by prvn-kumar01** [comment]
@mdazfar2 assign this issue I can make it more impressive 
and solve this issue

**Comment by Sana1902** [comment]
Can u please assign me this issue under gssoc-ext

**Comment by mdazfar2** [comment]
@prvn-kumar01 go ahead and try to make it more appealing and user-friendly.

- please give ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)

**Comment by prvn-kumar01** [comment]
https://github.com/user-attachments/assets/95990eca-8651-40d4-99cd-11e9f8e7f786

 when any user clicks on the cart or wishlist without logging in, an alert says "Please login first." Once the user successfully logs in, they can access the wishlist and cart buttons.
 
 I added above  feature

**Comment by mdazfar2** [comment]
Hey @prvn-kumar01 @Sana1902, for now, I will close this issue. Please don't feel discouraged. You guys are very-very-very good developer. I will make sure to assign you new issues, bugs, or features that are really needed for our website. Thank you.



- I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
