### ISSUE TITLE
[Feat] logo issues in footer

### ISSUE THREAD

**Issue by Risheendra183** [mdazfar2/Ezyshop#22]
### Description

discord logo is missing,we can replace the the twitter logo with the updated one.
i would like to work on it .please assign and add label Gssoc 24- ext and level

### Screenshots

![image](https://github.com/user-attachments/assets/430966c0-4eb0-42da-9c97-f3c885b214d1)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Risheendra183 go ahead

**Comment by Subashree-selvaraj** [comment]
I'll resolve this issue now!can you assign this to me!

**Comment by mdazfar2** [comment]
hey @Risheendra183 I hope you are doing well!

- It has been 2 days and you haven't responded to anything. Unfortunately, I have to close this issue because there are many duplicate issues raised. Please don't be discouraged. Thank you.
