### ISSUE TITLE
[Feat]want to add animation in the social media icons in the footer

### ISSUE THREAD

**Issue by ritikm31** [mdazfar2/Ezyshop#220]
### Description

wants to add enhanced rich animations in the social media icons in the footer section

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ritikm31 it would be great if you could share a demo video. I would be happy to assign it to you, and it would make things more understandable.

**Comment by ritikm31** [comment]
ok .

**Comment by ritikm31** [comment]
Here's a sample
[iPhone-12-PRO--j73_0PihjJ.webm](https://github.com/user-attachments/assets/05554d93-e0ee-412a-8e0b-0b1c28d51e62)

**Comment by mdazfar2** [comment]
hey @ritikm31 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

**Comment by ritikm31** [comment]
it's ok
