### ISSUE TITLE
[Feat] wants to scale the size of header headings title  and shop now buttons on hovering.

### ISSUE THREAD

**Issue by ritikm31** [mdazfar2/Ezyshop#221]
### Description

the size of title headings and shop now buttons scale a bit when some on hover on them .

assign it to me for this change.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ritikm31 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

**Comment by ritikm31** [comment]
ok

**Comment by mdazfar2** [comment]
@ritikm31 please give star to our repository ⭐
