### ISSUE TITLE
[Feat] Alert Message for Unauthenticated Users Accessing Products and Shops Page

### ISSUE THREAD

**Issue by kavya410004** [mdazfar2/Ezyshop#225]
### Description

Currently, when an unauthenticated user attempts to access the products page or shops page, there is no alert message to inform them that they need to log in first. I would like to implement a feature that enhances user experience by displaying an alert message when this occurs.

**Proposed Solution:**
- When a user who is not logged in clicks on the products or shops page, an alert message should appear, stating: "Please login first."
- This alert message should be visible for about 2-3 seconds before automatically disappearing.
- This alert message will appear on the current page where the user is.

**Additional Information:**
This feature aims to provide clear feedback to users attempting to access restricted content, guiding them to log in without causing frustration from immediate redirection.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@kavya410004 you are assigned.
