### ISSUE TITLE
[Feat] Sidebar Navigation menu

### ISSUE THREAD

**Issue by archanasingh11** [mdazfar2/Ezyshop#226]
### Description

**Description:**

The website would benefit from the addition of a **collapsible sidebar navigation menu** to improve the user experience. A collapsible sidebar provides users with easy access to different sections of the website while keeping the interface clean and uncluttered when not in use.

Suggested features for the collapsible sidebar:
- Expandable categories and subcategories for better content organization.
- A responsive design that adapts to different screen sizes (desktop and mobile).
- Smooth animations for collapsing and expanding the sidebar.
- An intuitive toggle button for users to show or hide the menu as needed.

Implementing this feature will streamline navigation, enhance accessibility, and provide a more modern, user-friendly design.

Please @mdazfar2 assign me this task with labels "GSSOC-Ext", "hacktoberfest-accepted" and "level2".

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@archanasingh11 could me provide a screenshot of it

**Comment by archanasingh11** [comment]
> @archanasingh11 could me provide a screenshot of it

Are you a contributor or this project owner
