### ISSUE TITLE
[BUG] Found a bug in Fashion page

### ISSUE THREAD

**Issue by Prudhvi-232** [mdazfar2/Ezyshop#228]
### Description

On the Fashion page, clicking the Add to Cart button for products with titles that contain single quotes (e.g., "Men's Casual Shirt") does not trigger the alert message due to a JavaScript error caused by the single quote in the title.

### Steps to Reproduce

Go to the Fashion category page.
Click the Add to Cart button for one of the first three items, such as "Men's Casual Shirt".
Observe that the alert message does not appear as expected.

### Expected Behavior

When clicking the Add to Cart button for products with single quotes in their title, the alert should display correctly, showing the product name in the message.

### Screenshots

https://github.com/user-attachments/assets/2dda6c9e-b4e3-4a38-b3eb-12c998034847

### Any additional information?

Possible Solution
To handle the case where product_title contains special characters like single quotes, the onclick function should work properly without breaking due to the embedded quotes. A suggested fix involves escaping single quotes in the product title.
product.product_title.replace(/'/g, "\\'") replaces all single quotes (') in the product title with an escaped version (\'), so that the title won't break the JavaScript code when passed to addToCart().

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing issues
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Prudhvi-232 assigned.
