### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by shivamy009** [mdazfar2/Ezyshop#23]
### Description

Improve card styling

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@shivamy009, please provide a detailed description of the issue so I can fully understand it and assign it to you accordingly.

**Comment by shivamy009** [comment]
> @shivamy009, please provide a detailed description of the issue so I can fully understand it and assign it to you accordingly.

![Screenshot 2024-10-02 002012](https://github.com/user-attachments/assets/d5b05923-99fa-4fcd-9309-b19c14968634)
here you can improve  font style  and height of card .
![Screenshot 2024-10-02 002027](https://github.com/user-attachments/assets/f9a52b6e-f02d-41cf-9e3f-c35c2682e91c)
here height of card are not well positioned
