### ISSUE TITLE
login signup page is not responsive

### ISSUE THREAD

**Issue by AyushSharma72** [mdazfar2/Ezyshop#230]
### Description

the login page is not responsive i want to make it responsive

### Screenshots

![image](https://github.com/user-attachments/assets/c034245f-1df0-480a-99ea-b31bdfff84c6)

### Any additional information?

please add level2 tag

### What browser are you seeing the problem on?

chrome 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Go ahead @AyushSharma72, but make sure it doesn't affect the desktop view.

**Comment by AyushSharma72** [comment]
> Go ahead @AyushSharma72, but make sure it doesn't affect the desktop view.

Okay 👍

**Comment by AyushSharma72** [comment]
> Hi @mdazfar2 I can see that login and signup page is still not fixed. Can you please assign me this issue? I will fix it within half an hour.

i already did it i ahve a pending PR

**Comment by mdazfar2** [comment]
Solved
