### ISSUE TITLE
User Experience Improvement by implementing smooth scrolling using Lenis

### ISSUE THREAD

**Issue by MuraliKarthikS** [mdazfar2/Ezyshop#231]
Hello,

I would like to propose adding the Lenis library to the EzyShop project to enhance the scrolling experience across all pages. Smooth scrolling can significantly improve user experience by providing a more fluid transition between sections of the website.

Proposed Changes

- Integrate Lenis: Add the Lenis library to the project, preferably via CDN for ease of use.

- Implementation: Implement smooth scrolling functionality throughout the website.

- Performance Testing: Ensure that the integration does not adversely affect load times or performance metrics.

Benefits

- Enhanced User Experience: A smoother scrolling experience can make navigation more enjoyable and engaging for users.

- Modern Aesthetics: Smooth scrolling is a contemporary design trend that can elevate the overall look and feel of the site.

- Mobile Optimization: Lenis is designed to work well on mobile devices, ensuring a consistent experience across platforms.

**Comment by MuraliKarthikS** [comment]
I know its not that important. I am currently into UI/UX and just started contributing. let me know if i can contribute to better issues.

**Comment by mdazfar2** [comment]
@MuraliKarthikS As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
