### ISSUE TITLE
[Feat]Create Custom ScrollBar

### ISSUE THREAD

**Issue by shivam8112005** [mdazfar2/Ezyshop#232]
### Description

The current scroll bar design does not align with the overall style of the application. To improve user experience and aesthetics, we propose implementing a custom scroll bar that matches the design language of the website.

### Screenshots

![Screenshot 2024-10-06 174143](https://github.com/user-attachments/assets/d7e0d457-8af8-412d-a0d0-744d62bb6be8)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@shivam8112005 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

**Comment by shivam8112005** [comment]
ohk
