### ISSUE TITLE
Adding email ,address ,phone icon hover effect in footer 

### ISSUE THREAD

**Issue by Charul00** [mdazfar2/Ezyshop#233]
### Description

To enhance user experience and interaction on your website, i am implementing a hover effect for the email, address, and phone icons in the footer section. This feature will provide visual feedback when users hover over these icons, making the footer more engaging and intuitive.

### Screenshots

![Screenshot 2024-10-06 182249](https://github.com/user-attachments/assets/44fdec91-347f-42c9-8082-5267a12a4dbc)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Charul00** [comment]
please assign to me and add a label gssoc-ext and level

**Comment by mdazfar2** [comment]
@Charul00 go ahead and make this in all pages footer

**Comment by Swatidevi** [comment]
please assign to me and add a label gssoc-ext and level

**Comment by vijaychandra1910** [comment]
I want to work on it please assign it to me @mdazfar2

**Comment by mdazfar2** [comment]
@vijaychandra1910 go ahead create PR as soon as possible

**Comment by vijaychandra1910** [comment]
Complete #233 also adding link of address, phone and email.
![Screenshot 2024-10-07 030443](https://github.com/user-attachments/assets/90c21e60-b7b9-4c48-844c-f15f97475c87)
@mdazfar2  please check once then merge it.
I will send pull request
