### ISSUE TITLE
Adding hover effect services part

### ISSUE THREAD

**Issue by Charul00** [mdazfar2/Ezyshop#234]
## Adding Hover Effect to Services Section

To improve the interactivity and visual appeal of your services section, you can add a hover effect to the service cards or icons. This effect will enhance the user experience by drawing attention to each service as the user hovers over it, making the section more dynamic and engaging.

### Key Considerations:
1. **Service Cards or Icons**: Each service, whether displayed in a card format or with an icon and description, should respond to user interaction with a hover effect.

2. **Visual Feedback**: The hover effect can include subtle changes like increasing the size of the service card, altering the background color, or adding shadows. These effects should be smooth and not overly distracting, ensuring they complement the design while maintaining clarity.

3. **Ease of Interaction**: Users should clearly perceive the change when they hover over a service, helping them identify clickable areas or highlighting key services. Visual transitions can guide the user’s attention and make the section more engaging.

4. **Consistency**: Ensure the hover effects are consistent across all services, maintaining uniform behavior throughout the section. This creates a professional and cohesive look.

### Benefits:
- **Enhanced User Engagement**: Interactive elements naturally draw users' attention, increasing their likelihood of exploring your services.
- **Improved Aesthetic Appeal**: Adding hover effects introduces a sense of depth and movement, making the page feel more modern and polished.
- **Guiding User Focus**: Subtle hover effects can guide users' focus towards specific services, helping you highlight important offerings.

### Best Practices:
- **Smooth Transitions**: Use smooth and subtle animations for the hover effect to avoid overwhelming the user.
- **Maintain Accessibility**: Ensure that all users, including those with disabilities, can interact with the services section. This includes adding appropriate focus states for keyboard navigation and making sure the hover effect doesn’t compromise readability or usability.

### Screenshots

![Screenshot 2024-10-06 182503](https://github.com/user-attachments/assets/1c618cc0-0a87-422b-8491-0235460368fd)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Charul00 you are assigned.

**Comment by vijaychandra1910** [comment]
I want to work on it please assign to me @mdazfar2

**Comment by Charul00** [comment]
@mdazfar2 can you please add label 3 i added to home and about page also

**Comment by mdazfar2** [comment]
@Charul00 Adding hover effects and all is only considered level 1, but I gave you level 2. I can give you level 3, but when the GSSoC team coordinator reviews it, your points might be reduced to level 1. However, if you still want, I can give you level 3.

**Comment by mdazfar2** [comment]
@Charul00 Adding hover effects and all is only considered level 1, but I gave you level 2. I can give you level 3, but when the GSSoC team coordinator reviews it, your points might be reduced to level 1. However, if you still want, I can give you level 3.

**Comment by Charul00** [comment]
okk no issue i can flexible with level 2 also

**Comment by Raj-Aditya-27** [comment]
Hi @mdazfar2 
I can still see that the task is not done yet.
Can you please assign this issue to me.
I will do it shortly.

**Comment by vijaychandra1910** [comment]
#234 completed please check 
@mdazfar2 

https://github.com/user-attachments/assets/408ccab3-c357-4469-853b-2b4118284f6f

**Comment by vijaychandra1910** [comment]
Why I hvn't getting the tag of #234 after completing this issue.
![Screenshot 2024-10-07 234308](https://github.com/user-attachments/assets/8160da94-ded6-4eb1-a7b2-ab1132082bfe)
