### ISSUE TITLE
[Feat] Make a page which comes after "Submit" in forms listed on index.html

### ISSUE THREAD

**Issue by Shan-N** [mdazfar2/Ezyshop#235]
### Description

I wanna build a **"Your request was submitted"/"We'll get back to you shortly"** page after user clicks the submit button on any form listed on Ezyshop.

This page will be responsive and will include the name of the User mentioned.

Please label as level 2/3

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Shan-N** [comment]
@mdazfar2 Please assign

**Comment by Kavita1928** [comment]
@Shan-N Can you provide preview or screenshot of the page you want to create

**Comment by Shan-N** [comment]
![Screenshot 2024-10-06 193035](https://github.com/user-attachments/assets/55eaf3ea-33c5-494c-9bca-78840fb7ee34)
Should look something like this

**Comment by Kavita1928** [comment]
@Shan-N  yess , match theme according the website

**Comment by Sourabh782** [comment]
@Kavita1928  is this issue free? If yes I m intrested
