### ISSUE TITLE
[BUG] Deployment issue

### ISSUE THREAD

**Issue by eshalshaikh07** [mdazfar2/Ezyshop#237]
### Description

The deployed website is not loading would like to work on deploying the website correctly using vercel.

### Screenshots

<img width="857" alt="image" src="https://github.com/user-attachments/assets/38fc9761-8245-4ff0-92b6-33bbc6b5afc6">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@eshalshaikh07 I know, I also use this link, but it is not accessible because it is already in use. That's why we use the link - ezshopz.vercel.app.

- Can you help us improve this if possible?

**Comment by eshalshaikh07** [comment]
I can try doing it!!
