### ISSUE TITLE
[BUG] Add to Cart without signup

### ISSUE THREAD

**Issue by Shan-N** [mdazfar2/Ezyshop#238]
### Description

A alert is shown added to cart even though the user hasn't logged in or signed in. 

I'll make it so that when the user isn't logged in the alert instead shows "Please login to continue" and when the user logs in the product then will be correctly added to cart

This feature will be helpful when firebase auth service is deployed in this project.

Please label this as a level 3

### Screenshots

![Screenshot 2024-10-06 193423](https://github.com/user-attachments/assets/9bd6b7b9-3228-4aa4-81ae-1977e3c41c30)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Shan-N You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
 - Hope you star our [Repo](https://github.com/mdazfar2/Ezyshop).
