### ISSUE TITLE
[BUG]  Error Encountered on Categories Page After Multiple Selections

### ISSUE THREAD

**Issue by pavan-234** [mdazfar2/Ezyshop#239]
### Description

I would like to bring to your attention an issue with the "Categories" functionality on the Electronics page. After opening the Categories page and selecting one of the options listed, if I proceed to select another option and then attempt to click back on the Categories page, it fails to open and instead displays an error.

### Screenshots

![Screenshot 2024-10-06 195426](https://github.com/user-attachments/assets/85c41b4f-5626-4b4a-a651-32056444d4b0)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hey @pavan-234 please check it again in deployment version it is working fine. Thank you for raising the issue.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
