### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by shivamy009** [mdazfar2/Ezyshop#24]
### Description

fix issue when clicking categories

### Screenshots

![Screenshot 2024-10-01 234523](https://github.com/user-attachments/assets/884bfd6a-d102-4d47-8eb4-77ddc931c779)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@shivamy009 you are assigned. go ahead

**Comment by shivamy009** [comment]
> @shivamy009 you are assigned. go ahead

not showing  i am assigned it showing mention

**Comment by muhafiz5814** [comment]
Hey @mdazfar2 Can I work on this issue?
I was about to raise an issue about it but I found it here already.
I think @shivamy009 is having some problems.

**Comment by mdazfar2** [comment]
Sure @muhafiz5814 go ahead I'm also assigning you.
