### ISSUE TITLE
[BUG] Hover Effect to the cards

### ISSUE THREAD

**Issue by rupeshv2121** [mdazfar2/Ezyshop#240]
### Description

It will be good user experience if there is any hover effect in all card.

Pls assign me under label gssoc-ext and hacktoberfest , level 3

### Screenshots

![Hover effect](https://github.com/user-attachments/assets/d2600707-b67d-424f-b0b4-226db46e2a72)
![Hover effect-2](https://github.com/user-attachments/assets/ed26c660-e230-4367-9c15-ec0ed684f46c)

### What browser are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@rupeshv2121 You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)

**Comment by rupeshv2121** [comment]
sorry sir this is by mistake
