### ISSUE TITLE
[Feat] Addition of "Deals of the day" page

### ISSUE THREAD

**Issue by priyanka350** [mdazfar2/Ezyshop#241]
### Description

Summary:
The "Deals of the Day" section in the navbar will prominently feature time-sensitive discounts and exclusive offers to encourage user interaction and impulse buying. By displaying limited-time deals, users will feel motivated to visit frequently and act quickly to take advantage of discounts, thus increasing site traffic and sales.

Proposed Solution:
- Display a dedicated "Deals of the Day" section in the navbar.
- On navigating to that page , 2 products from each category will be displayed with some discount.
- Include a countdown timer to show the remaining time for each deal.

Benefits:
- Increased Sales: Urgency from time-sensitive offers drives faster purchasing decisions.
- Higher User Engagement: Frequent visitors return to check daily deals.
- Improved Customer Experience: Easy access to top deals enhances user satisfaction.
- Boosts FOMO: Countdown timers create urgency, pushing users to act quickly.

### Screenshots

N/A

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@priyanka350  could you provide a preview or screenshot of you modifaction

**Comment by priyanka350** [comment]
sure @Kavita1928 

under Deals of the day
- 2 products from each category will be displayed

![image](https://github.com/user-attachments/assets/20043cbd-13df-4a67-a15d-816e47036188)

**Comment by Kavita1928** [comment]
@priyanka350 okk, but where you will add them in navbar ,once  provide a screenshot after adding it in navbar

**Comment by priyanka350** [comment]
@Kavita1928 sure

navbar will look like this 

![image](https://github.com/user-attachments/assets/3fc3b964-d148-444e-a1e3-7d6a9ef5749e)

**Comment by Kavita1928** [comment]
@mdazfar2 Do want to add this section in navbar ?

**Comment by mdazfar2** [comment]
@Kavita1928, first, we will make all products fully functional. After that, we can consider it in the future, so close this for now or move it to waiting-approval for future reference.

**Comment by SanikaBhalerao1345** [comment]
@mdazfar2 can i work on this issue?
