### ISSUE TITLE
[Feat] Adding dark mode and light mode option

### ISSUE THREAD

**Issue by eshalshaikh07** [mdazfar2/Ezyshop#242]
### Description

Hi Team,

I’ve been reviewing the project and I think it’s coming along great! I wanted to suggest a potential enhancement for the website—adding an option for both dark and light modes. This would allow users to switch between themes based on their preference, which can improve accessibility and overall user experience.

Along with this, I’d also like to make a few adjustments to the README.md file, including reorganizing the text and adding some visuals (icons) to make it more interactive and user-friendly.

I’m excited to contribute these features and would love to get your thoughts on moving forward with them!

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@eshalshaikh07 thankyou for raising this issue but for now it is not required will let you know if required in future
