### ISSUE TITLE
ENHANCEMENT OF THE  CONTACT US FORM AND MAKE IT MORE INTERACTIVE AND ATTRACTIVE

### ISSUE THREAD

**Issue by dnyanesh99borse** [mdazfar2/Ezyshop#243]
**### ENHANCEMENT OF THE  CONTACT US FORM AND MAKE IT MORE INTERACTIVE AND ATTRACTIVE**

i can make the contact us form more interactive and attractive by adding the respective icons to the input fields of the form as well as by  managing the design and effects of the form 

AS a experienced frontend developer i am requesting you to please give me a chance to resolve this issue i can enhance this 10x.
@dnyanesh@99
@mdazfar2

**Comment by Kavita1928** [comment]
@dnyanesh99borse  could you provide a screenshot of enhancement you want

**Comment by dnyanesh99borse** [comment]
here it is..! 
![image](https://github.com/user-attachments/assets/f140c98d-8264-4e3c-aa37-bb98a1524a74)

![image](https://github.com/user-attachments/assets/1f3e7365-bffb-4632-a690-10e6ec3638b6)

please assign this task to me . i can enhace this to 10x.

**Comment by mdazfar2** [comment]
@dnyanesh99borse As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Don't forget to give our repository a star and let me know once you've done it.

**Comment by dnyanesh99borse** [comment]
Ok
