### ISSUE TITLE
[Feat]Enhancing User Experience with Character-Based Validation in Contact Forms

### ISSUE THREAD

**Issue by meghanakn473** [mdazfar2/Ezyshop#244]
### Description

Switching from word-based validation to character-based validation for the message input in a "Contact Us" form can improve user experience and ensure that all input is properly captured.

@mdazfar2 please assign me this issue i want to work on it
please label level 2/3, hacktoberfest, gssoc-extd labels

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@meghanakn473, please share a demo video for clarification so I can assign this issue to you.

**Comment by meghanakn473** [comment]
![20241007_141432.jpg](https://github.com/user-attachments/assets/3b4fe11d-8162-4761-b2c9-42fd60a78871)

Here in the above form wen user types only single letter then error is shown and user can't Submit the form

I want to implement this feature

**Comment by mdazfar2** [comment]
@meghanakn473 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Don't forget to give our repository a star and let me know once you've done it.
