### ISSUE TITLE
[Feat]Ading feedback/rate us option

### ISSUE THREAD

**Issue by Aditijainnn** [mdazfar2/Ezyshop#245]
### Description

In the bottom footer adding feedback option option

### Screenshots

assign this to me under gssoc ext and hacktoberfest

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @Aditijainnn thank you for raising the issue.

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- and please star us
