### ISSUE TITLE
In readme.md adding contributors profile

### ISSUE THREAD

**Issue by Aditijainnn** [mdazfar2/Ezyshop#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

In readme adding contributors profile 

### Suggested Change

Assign this to me under gssoc ext and hacktoberfest

### Urgency

Medium

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Aditijainnn go ahead.

**Comment by Aditijainnn** [comment]
> @Aditijainnn go ahead.

ok
