### ISSUE TITLE
[Feat] Background Shadow Effect to the Trending Deals(Favorite Products) Section.

### ISSUE THREAD

**Issue by HeartTick** [mdazfar2/Ezyshop#247]
### Description

Adding  a shadow hovering effect to the Trending deals section and Latest blogs section.

### Screenshots

![image](https://github.com/user-attachments/assets/1a83e58e-9c22-4d9f-bc02-430bd8654ec2)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@HeartTick As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- and please give star us
