### ISSUE TITLE
[BUG] Height of the Cards is not same

### ISSUE THREAD

**Issue by HeartTick** [mdazfar2/Ezyshop#248]
### Description

I would like to adjust the heights of the Cards in Latest Blogs section So can You please assign the task to me . 
Thank You.

### Screenshots

![image](https://github.com/user-attachments/assets/f601a023-eae1-4b75-a546-057a9d7b0c0f)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@HeartTick assigned

**Comment by mdazfar2** [comment]
Hello @ayushku634, I really appreciate your interest in contributing to Ezyshop, but this issue is already assigned to someone else. Assigning it to you again wouldn’t be fair, hope you understand.

**Comment by Kavita1928** [comment]
@HeartTick  Are you working on the issue ? or should i assign to someone else

**Comment by HeartTick** [comment]
Actually I made the changes but forgot to make the pull request. Give me some time to do that....

**Comment by HeartTick** [comment]
This Issue is already Resolved by me.Can you please check @Kavita1928

**Comment by HeartTick** [comment]
Can you please review the Changes . Thank you

**Comment by mdazfar2** [comment]
I apologize, but I need to close this issue for now. Please don't be discouraged!
