### ISSUE TITLE
[Feat] Form improvements✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [mdazfar2/Ezyshop#249]
### Description

I can improve this feature and also add a local storage implementation to this form, @mdazfar2 please assign me this task.

### Screenshots

<img width="519" alt="Screenshot 2024-10-06 at 8 53 25 PM" src="https://github.com/user-attachments/assets/479d61fb-736e-4998-8a83-d8b2d4dddfbb">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@T-Rahul-prabhu-38 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
