### ISSUE TITLE
[BUG] Give me access as a maintainer

### ISSUE THREAD

**Issue by thakuratul2** [mdazfar2/Ezyshop#25]
### Description

@mdazfar2 hii i am atul pratap singh and i am mentor of your project and I contact in the LinkedIn but no respond so can you give me the access as maintainer to make this project more effective and winning project with help of my skills`

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [x] I'm a GSSoC'24-Extd contributor
- [x] I'm a Hacktoberfest'24 contributor
- [x] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @thakuratul2,

- Thank you for tagging me here. I am mostly active on GitHub. Wait, I'll give you access. Actually, Atul, I am thinking of adding a complete backend and going for full functionality according to the project, so we need to convert the code into a good framework like Next.js.

- We can also talk on LinkedIn or Discord.

***Thank you.***

**Comment by thakuratul2** [comment]
@mdazfar2 oky so what is your approach to create the backend for it and I am specially backend background I will help you and new developer to make it possible
