### ISSUE TITLE
[Feat] adding of stationary and household items to the website

### ISSUE THREAD

**Issue by swethapadmavathimukku** [mdazfar2/Ezyshop#253]
### Description

Adding a stationary section and also a section of household items to the website.

could you please assign me on this issue

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@swethapadmavathimukku you can work on it

**Comment by swethapadmavathimukku** [comment]
Thank you for assigning me to this issue. I will do my best to solve the issue.

Could you please add the "level" label

**Comment by Kavita1928** [comment]
@swethapadmavathimukku  any update?

**Comment by Kavita1928** [comment]
@swethapadmavathimukku No there is no deadline but try to complete it soon

**Comment by swethapadmavathimukku** [comment]
okay thank you

**Comment by mdazfar2** [comment]
Hey @swethapadmavathimukku, for now, I will close this issue. Please don't feel discouraged. You are a very-very-very good developer. I will make sure to assign you new issues, bugs, or features that are really needed for our website. Thank you.

**Comment by swethapadmavathimukku** [comment]
hi there, may i know the reason for closing the issue
