### ISSUE TITLE
[Feat] ADD A DARK MODE FEATURE IN THE NAV BAR

### ISSUE THREAD

**Issue by rocky4446** [mdazfar2/Ezyshop#254]
### Description

I CAN ADD A SMALL BUTTON WHICH CHANGES THE OVERALL THEME OF THE PAGE FROM LIGHT TO DARK.
if there is any more front end help you need do let me know
please assign this issue to me and label it as hacktoberfest and gssoc 24exd.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@rocky4446  for now we don't need dark mode ,thanks for raising issue you can work on some other issue
