### ISSUE TITLE
[Feat] Add FAQ page

### ISSUE THREAD

**Issue by subin-shk** [mdazfar2/Ezyshop#255]
### Description

Add FAQ page for the website answering all the frequently asked questions.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@subin-shk assigned

**Comment by subin-shk** [comment]
please add level also
