### ISSUE TITLE
[BUG] Contact Us Align Issue

### ISSUE THREAD

**Issue by 4F24L** [mdazfar2/Ezyshop#257]
## Alignment issue

- Address, Email, Phone and opening hours texts are not aligned with icons.

### Screenshots

![image](https://github.com/user-attachments/assets/e8266e79-6d8a-4843-8a27-1cc9fab6fece)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@4F24L you are assigned

**Comment by 4F24L** [comment]
Can you please add level2 for this issue ?!
