### ISSUE TITLE
[BUG]  Issues with Contact Us Redirection and Read More Button on Home Page

### ISSUE THREAD

**Issue by pavan-234** [mdazfar2/Ezyshop#267]
### Description

I would like to report a couple of issues I encountered on the Home page:

1. When clicking the "Send Message" button in the "Contact Us" section, it is not redirecting to the Contact Us page as expected.

2. The "Read More" button in the "Latest Articles from Blog" section is also unresponsive in home page.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@pavan-234 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Don't forget to give our repository a star and let me know once you've done it.
