### ISSUE TITLE
Responsive Login/Sign up page

### ISSUE THREAD

**Issue by ParulPrashar** [mdazfar2/Ezyshop#268]
### Description

The login and sign up page is not responsive on mobile phone. The following are screenshots attached of the problem. 

@muhafiz5814 @Hamza20203064 @kindly assign this issue to me with label hacktoberfest amf gssoc
Etc. 

![Screenshot_2024-10-07-09-29-04-501_com android chrome](https://github.com/user-attachments/assets/9fe22a78-b753-4940-89d0-6bde2528a5af)
![Screenshot_2024-10-07-09-29-08-668_com android chrome](https://github.com/user-attachments/assets/3708657f-6dd4-463e-88a6-291d535872eb)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ParulPrashar You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)


- Don't forget to give our repository a star and let me know once you've done it.
