### ISSUE TITLE
[Feat] Customizable Scroll Bar Color to Match UI Theme

### ISSUE THREAD

**Issue by shashankgoud18** [mdazfar2/Ezyshop#270]
### Description

I would like to add the ability to customize the color of the scroll bar within our web interface. Currently, the default system scroll bar color does not align with our design aesthetics, and a customizable scroll bar would enhance the overall user experience.

Feature Requirements:

1.The scroll bar color should be customizable via CSS or configuration settings.
2.Cross-browser support (Chrome, Firefox, Edge, Safari) and compatibility with platforms like Windows, macOS, and mobile 
   devices.
3.Include customization for:
   Scroll bar thumb color
   Scroll bar track color
   Optional border or shadow effects for enhanced visibility

Benefits:
1.Provides a more polished and consistent UI by matching the scroll bar to the overall color scheme.
2.Improves user experience, especially in terms of visibility and ease of interaction.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@shashankgoud18 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Don't forget to give our repository a star and let me know once you've done it.
