### ISSUE TITLE
Issue Title: "Add Cursor-Following Animation"

### ISSUE THREAD

**Issue by AswaniBolisetti** [mdazfar2/Ezyshop#271]
@mdazfar2 
Issue Description: The website currently lacks interactive design elements that enhance user experience. I propose adding a cursor-following animation to create dynamic interactions where design elements move along with the mouse cursor, providing a more engaging and visually appealing experience.

I’d like to work on adding this feature. Please assign this issue to me under gssoc-ext, hacktoberfest-accepted, level

**Comment by mdazfar2** [comment]
@AswaniBolisetti As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Don't forget to give our repository a star and let me know once you've done it.
