### ISSUE TITLE
[Feat]chatboat integration

### ISSUE THREAD

**Issue by govindumeesala** [mdazfar2/Ezyshop#272]
### Description

Adding chat bot to the website, increases user experience

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by govindumeesala** [comment]
@mdazfar2 assign this to me please

**Comment by thakuratul2** [comment]
@govindumeesala assigned

**Comment by govindumeesala** [comment]
@thakuratul2 thank you will work on it

**Comment by Kavita1928** [comment]
@muhafiz5814 
@govindumeesala chatbox is not much responsive  .Can u fix it ?

**Comment by govindumeesala** [comment]
@Kavita1928 Can you please tell me what I have to improve. 
I will do the req changes

**Comment by mdazfar2** [comment]
Hello @govindumeesala, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue again. Please don't be discourage I need to close this PR now.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.

**Comment by govindumeesala** [comment]
@mdazfar2  please consider merging this pr
You can still change it to Next.js right after merging 

I really worked hard for this.

**Comment by mdazfar2** [comment]
@govindumeesala Merging a PR is not the solution. Why do you guys always think about points? Please work on valid issues, and I'll be happy to merge your PR. Please proceed me to close your PR
