### ISSUE TITLE
[BUG] Incorrect linking of products and shops images

### ISSUE THREAD

**Issue by Abankita** [mdazfar2/Ezyshop#274]
### Description

The website currently has a problem in linking of products images. Additionally some categories such as books don't have any products. I can fix it. 

### Screenshots

![Screenshot_2024-10-07-13-50-37-138~2](https://github.com/user-attachments/assets/8cab485c-95ef-4875-b30a-3ac3a46b9404)
![Screenshot_2024-10-07-13-50-18-538~2](https://github.com/user-attachments/assets/7f1084b3-6ebb-4ca5-8281-d79f419e8a87)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by thakuratul2** [comment]
@Abankita assigned

**Comment by Abankita** [comment]
@thakuratul2 Recently a pr was merged which made clicking the Explore stores create an alert to login. I'm not able to preview the products.html file as it is redirecting me to register page. Any suggestions on how can I preview the changes?

**Comment by Abankita** [comment]
![Screenshot_2024-10-08-00-01-38-618~2](https://github.com/user-attachments/assets/d3a12405-aa92-4fb0-853f-f019650bbddb)
@thakuratul2 A recent merged pr has created an alert to explore courses button and opening the products.html file is redirecting me to register page. Any suggestions on how to preview my changes? Thanks in advance

**Comment by mdazfar2** [comment]
Hey @Abankita, this isn't our mistake; it is correct. Thanks for raising the issue.


- Don't forget to give our repository a star and let me know once you've done it.
