### ISSUE TITLE
[BUG] Align the cards in the About us section

### ISSUE THREAD

**Issue by RhiyaBhat** [mdazfar2/Ezyshop#279]
### Description

I would like to align the about us section 

### Screenshots

![image](https://github.com/user-attachments/assets/ef765203-59f5-4f0f-8c86-3367499bee0f)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@RhiyaBhat As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Don't forget to give our repository a star and let me know once you've done it.
