### ISSUE TITLE
I want to add more category

### ISSUE THREAD

**Issue by Suvadip-sana** [mdazfar2/Ezyshop#28]
Hi! I am Suvadip Sana, I want to work on this project

**ISSUE**
I think in shopping website has more categories, For now it has only 3

**Suggestion**
I suggest for this categories  for adding - 
1. Home & Living

2. Beauty & Personal Care

3. Sports & Fitness

4. Books & Media

5. Toys & Games

Please assign me this issue if you think it's an issue need to fix

**Comment by mdazfar2** [comment]
@Suvadip-sana go ahead, but remember to upload AI-generated images. Please don't copy from Google or any other website.

**Comment by Suvadip-sana** [comment]
Could you please provide me the images? or shall i add myself.

**Comment by mdazfar2** [comment]
> Could you please provide me the images? or shall i add myself.

You can add yourself @Suvadip-sana

**Comment by Suvadip-sana** [comment]
Ok. Thank you.

**Comment by Suvadip-sana** [comment]
@mdazfar2 @thakuratul2  I add this three more row of categories for 9 new and essential categories that might be presnt on shopping site.

![image](https://github.com/user-attachments/assets/5758677e-b918-4595-ad61-ba4948765e9d)
![image](https://github.com/user-attachments/assets/e54221ff-69e3-4744-a011-12f9ccd800c4)
![image](https://github.com/user-attachments/assets/5bc68263-3e98-4c40-8a90-1b7ad33b4111)


Please see! If you are happy then I create a new branch and make a pull request.

**Comment by mdazfar2** [comment]
@Suvadip-sana That's amazing! 

- Do one thing: for every three columns, add a load more button. After clicking it, more columns will become visible, and after clicking load more again, it will show another set. Hope you understand.

- hope you understand.


- Don't forget to join our official [Discord server](https://discord.gg/SEzpxqQG).
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
- And please ⭐ our repo

**Comment by Suvadip-sana** [comment]
Ok. Try my best.

**Comment by Suvadip-sana** [comment]
https://github.com/user-attachments/assets/32c1bd3a-84a1-4d96-be5f-3ec4551756e8

Check it.

Should you please give me max label for this. It take way more time.  Actually I work on two issue. So 
Please! If you give me I would be very grateful!

**Comment by mdazfar2** [comment]
@Suvadip-sana, that's amazing! Please create a pull request and update your sync fork your branch.

**Comment by Suvadip-sana** [comment]
Could you please give me max label for this?

**Comment by mdazfar2** [comment]
Added @Suvadip-sana

**Comment by Suvadip-sana** [comment]
You miss hactoberfest label

**Comment by mdazfar2** [comment]
> You miss hactoberfest label. please add this. Then i raise a pull request
> 

Done! Anything else which i forget please let me know

**Comment by Suvadip-sana** [comment]
Should you close this issue? Because it merge already!
