### ISSUE TITLE
Update social media icon

### ISSUE THREAD

**Issue by Antima2004** [mdazfar2/Ezyshop#281]
### Description

In the footer section there are social media icon but the twitter logo is not updated 
Please assign this to me and also add label

### Screenshots

Here's the image of it:
![Screenshot_2024-10-07-16-19-46-13_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/fcd15da2-0e3b-453d-af8d-42faadfa8ee2)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kuldeepcoder2006** [comment]
I want to work on this project please assign it to me.

**Comment by mdazfar2** [comment]
@Kuldeepcoder2006 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
