### ISSUE TITLE
[Feat] Add Scroll Progress Bar to Enhance User Experience

### ISSUE THREAD

**Issue by shashankgoud18** [mdazfar2/Ezyshop#284]
### Description

I would like to propose adding a scroll progress bar at the top of the webpage to improve user experience. The progress bar will provide visual feedback to users about how much of the page they have scrolled through and how much content remains, especially useful for long pages.

https://github.com/user-attachments/assets/72d3ca62-98c7-4479-9267-f72797dbeab9

I’ve attached a video as a reference that demonstrates the transition effect I would like to implement. If you’re okay with adding this feature to the project, could you please assign the issue to me? I’m excited to work on this and would be happy to submit a pull request once it's completed.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by shashankgoud18** [comment]
Hey @mdazfar2 

 I just wanted to follow up on the issue I raised regarding of adding a scroll progress bar at the top of the webpage to improve user experience. I believe this feature could add value to the project, and I’m happy to work on it.

If you think it’s a good fit, could you please assign the issue to me so I can start working on it?

Thank You!

**Comment by mdazfar2** [comment]
Hello @shashankgoud18, sorry for the delay. Sometimes, some issues get overlooked while reviewing many.

As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
