### ISSUE TITLE
[Feat] Create User Accounts Page with Essential Features

### ISSUE THREAD

**Issue by kavya410004** [mdazfar2/Ezyshop#285]
### Description

Currently, there is no dedicated Accounts Page for users to view and manage their account details. I would like to create an "Account" page that displays the user's account details and provides buttons to navigate to other relevant sections of the website. Here's the proposed structure:

**1. User's Details Section:**
- Display user information like name, email, etc.
- Add options like changing the password.

**2. Buttons for navigation such as:**
- Order History
- Wishlist
- Address Management
- My Cart
- Loyalty Points or Rewards
- Logout

These buttons will be displayed as list items and will redirect the user to the respective pages for further interactions.
Also let me know if any other options has to be included.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @kavya410004, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.
