### ISSUE TITLE
change the color of social icons at footer on hover 

### ISSUE THREAD

**Issue by Shekhar-Raj** [mdazfar2/Ezyshop#286]
### Description

<h2>I want to change the color each social icon to their primary color when user hover on it
like: facebook:blue
instagram:pink, and many more</h2>

### Screenshots

<h2>I want to apply here:</h2>

![image](https://github.com/user-attachments/assets/6c4f8540-8e86-4253-b5f9-d9ea71fe9c48)

<h2>Demo:</h2>

https://github.com/user-attachments/assets/7842039a-816b-4fec-8bca-67d40dfd412f

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Shekhar-Raj As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Don't forget to give our repository a star and let me know once you've done it.
