### ISSUE TITLE
[Feat] Responsiveness in page

### ISSUE THREAD

**Issue by Mansi07sharma** [mdazfar2/Ezyshop#287]
### Description

The page is not responsive well. when we make it reduce the navbar options becomes hide and all the body ' s items look so big and not looking so good.

I want to work on it. Kindly assign me to do it @mdazfar2 .

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Mansi07sharma share a screenshot of how it's hide

**Comment by Mansi07sharma** [comment]
![image](https://github.com/user-attachments/assets/4b987b69-5404-40e3-854a-a9d08d54c56a)
 See and if you like then kindly assign me it. I would like to work on it and I will make it more attractive and responsive

**Comment by mdazfar2** [comment]
@Mansi07sharma You are very late now it is done and it been 5 days and you didn't respond anything. closing the issur for now
