### ISSUE TITLE
[BUG] layout issue

### ISSUE THREAD

**Issue by sauraabhh** [mdazfar2/Ezyshop#290]
### Description

The layout of navigation bar and its icon is not looking nice 
the below layout of the shared screenshot doesnot have good ui/ux

### Screenshots

![Screenshot 2024-10-07 191210](https://github.com/user-attachments/assets/f31c6fb3-d2d2-48a4-ae7b-ade81d2e0eb1)

### What browser are you seeing the problem on?

Firefox

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by sauraabhh** [comment]
@mdazfar2 please assign me this under gssoc'24 ext

**Comment by mdazfar2** [comment]
@sauraabhh share with me the updated footer UI which we can assign accordingly.

**Comment by Kavita1928** [comment]
@sauraabhh  As no update i am closing it
