### ISSUE TITLE
[Feat] changing navbar 

### ISSUE THREAD

**Issue by AnkushUjawane** [mdazfar2/Ezyshop#293]
### Description

your webpage navbar is not attractive
assign me task to make navbar attractive and responsiveness 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@AnkushUjawane As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Don't forget to give our repository a star and let me know once you've done it.
