### ISSUE TITLE
[BUG] I want to update Latest Article from blog Card in home page.

### ISSUE THREAD

**Issue by PrAyAg9** [mdazfar2/Ezyshop#294]
### Description

When you scroll down upto Latest Articles from blog then you see down there a **Read More** button, I want to fix its position down in the card so that it looks properly aligned, Now when you see it changes it's positon according to the description above but it would look really good if all the read more in each card are aligned properly side by side. I hope you understand what i am trying to say.

### Screenshots

![image](https://github.com/user-attachments/assets/0d75344b-892f-452c-80ed-fff3d71cc9ed)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@PrAyAg9 you are assigned.
