### ISSUE TITLE
[BUG] There is an alignment issue in the homepage 

### ISSUE THREAD

**Issue by priyaahm** [mdazfar2/Ezyshop#3]
### Description

In the homepage under Shop for Your Favorite Products, the first block - Fashion & Accessories is slightly bigger in size than the other two blocks causing an alignment issue.

Please assign this to me and add gscod-extd, levels, hacktober labels.

### Screenshots

![alignment issue ](https://github.com/user-attachments/assets/966209f5-5f6d-428f-b4e1-7699cdaf6b37)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@priyaahm go ahead

**Comment by mdazfar2** [comment]
closed as complete
