### ISSUE TITLE
Update the header and menu 

### ISSUE THREAD

**Issue by himanchal08** [mdazfar2/Ezyshop#30]
### Description

Can give a better look to the header and can update the hamburger menu in the mobile view (allign it ). 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hey @himanchal08 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

**Comment by himanchal08** [comment]
Thank you for the response . I'll let you if I find any other issue .
