### ISSUE TITLE
[Feat] Add Pre-loader

### ISSUE THREAD

**Issue by soumyajit254** [mdazfar2/Ezyshop#302]
### Description

I want to contribute in this project. Please assign me. I can add Pre-loader

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@soumyajit254 please share demo video which types of loader you want to contribute
