### ISSUE TITLE
[Feat] Missing "Learn More" Button in Product Details on EazyShop Site

### ISSUE THREAD

**Issue by Iamanujosh** [mdazfar2/Ezyshop#304]
### Description

 In the current product display, as shown in the provided screenshot, the product cards only offer an "Add to Cart" button. There is no option for users to access additional product details. Adding a "Learn More" button next to or below the "Add to Cart" button would allow users to explore more detailed information about the product, such as specifications, materials, sizes, and reviews, before making a purchase decision.

Impact:

Users may feel they lack sufficient information to make informed purchasing decisions.
Could lead to reduced engagement with products, as users are not encouraged to explore further.
Potential customers may leave the site to find more information about the products elsewhere, leading to lost sales.
Proposed Solution:

Add a "Learn More" button beside or beneath the "Add to Cart" button on each product card.
Link the button to a detailed product page where users can view more information about the item.
Ensure the product page includes specifications, available sizes, detailed descriptions, customer reviews, and any additional product details.

### Screenshots

![image](https://github.com/user-attachments/assets/f9bd1e72-215b-4ae4-862f-1d84a234538c)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Iamanujosh, thank you for raising this. Actually, we are converting our code to the Next.js framework, so after that, you can apply your changes.

**Comment by Iamanujosh** [comment]
Okay you can assign me after. And I have stared it.
