### ISSUE TITLE
[Feat]Add special deals and offers sliding section

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [mdazfar2/Ezyshop#305]
### Description

Display special deals for festive season, offer on first purchase, bonus deals if user shares it with more people.

### Screenshots link
https://photos.app.goo.gl/p44vvimsFThk2NrW8

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hey @SanikaBhalerao1345 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Don't forget to give our repository a star and let me know once you've done it.
