### ISSUE TITLE
[Doc]: Create a `pull_request_template.md` File

### ISSUE THREAD

**Issue by ansiace** [mdazfar2/Ezyshop#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

To enhance our contribution process and ensure that all pull requests provide essential information, I propose adding a `pull_request_template.md` file to the repository. This template will guide contributors in including relevant details and improve the overall quality of our pull requests.

### Suggested Change

A well-structured pull request template can:
- Streamline the review process
- Ensure all necessary information is provided
- Help maintain consistency across contributions
- Improve communication between contributors and maintainers

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ansiace you are assigned.
