### ISSUE TITLE
[Feat] In nav bar category page is NOT FOUND

### ISSUE THREAD

**Issue by Suvadip-sana** [mdazfar2/Ezyshop#31]
### Description

Hi! I am Suvadip
**ISSUE**
In Navbar the category page is Not Found
i want to create a full page with all of it's category.

**NOTE**
I also raise anoteher isuue for adding new catogories

Please assign me that issue, i want to work on it

### Screenshots

![image](https://github.com/user-attachments/assets/0d1dc947-fbe0-48f0-8d03-2500711949bb)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Suvadip-sana go ahead

**Comment by Suvadip-sana** [comment]
One more clarification!

I add all the category in category page.
But should I add all the category in home page. 
My suggestion is add more 3 category in home page, and rest all are shown in category page!

**Comment by mdazfar2** [comment]
@Suvadip-sana, it has already occurred. You can look at the below; just mention them where they can be visible on the deployed website.

https://github.com/user-attachments/assets/dbb1fc71-0caa-41f3-bd01-7d1e3015c9f4

**Comment by Suvadip-sana** [comment]
Ok! Got it. @mdazfar2

**Comment by rohitsharma2610** [comment]
Hey, i have experience in this work so can you assign me?

**Comment by mdazfar2** [comment]
@rohitsharma2610 it is already assigned to @Suvadip-sana
