### ISSUE TITLE
Adding feedback section to the footer part .

### ISSUE THREAD

**Issue by Tanushree084** [mdazfar2/Ezyshop#310]
### Description

Hey @mdazfar2 

I want to add the feedback section to the footer part to make the website more efficient and feasible .

Can you please assign me this issue ?

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hello @Tanushree084 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
