### ISSUE TITLE
Duplicate quick links and Newsletter in Footer of Teams page.

### ISSUE THREAD

**Issue by Tanushree084** [mdazfar2/Ezyshop#312]
### Description

Hello @mdazfar2 

I want to remove the duplicate quick links and Newsletter in footer of teams page to make it look more better.
<img width="932" alt="image" src="https://github.com/user-attachments/assets/6afa52b6-fa0f-44c3-ae38-e9a8c0a1549b">

Can you please assign me this issue ?

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@Tanushree084 Thanks for raising the issue but we don't need such changes.You can choose some other issue
and hope you star our https://github.com/mdazfar2/ezyshop
