### ISSUE TITLE
[BUG] : The Contact us Page has address and email-id unresponsive

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [mdazfar2/Ezyshop#313]
### Description

Adding links to address and email-id in the contact us page.

### Screenshots

<img width="1289" alt="Screenshot 2024-10-08 at 12 53 11 PM" src="https://github.com/user-attachments/assets/368fc6a1-4313-4dc0-9372-ad8de71df239">

### Any additional information?

Please assign this issue to me.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@Arghya-Chakraborty0812 assigned

**Comment by Arghya-Chakraborty0812** [comment]
Please add level1 label on it

**Comment by Kavita1928** [comment]
@Arghya-Chakraborty0812 your issue is already closed
