### ISSUE TITLE
[BUG] Footer not working as expected in Category page and Teams Page

### ISSUE THREAD

**Issue by somil0701** [mdazfar2/Ezyshop#314]
### Description

In the Category page, the footer width is not the same as the other pages. You can see in the ss i attached that some white space is left on the both sides of the footer.

In the Teams page, the quick links and newsletter section are duplicated.

Please assign this PR to me, I will resolve this issue ASAP.
Thank You :)

### Screenshots

Home Page(Normal):
![image](https://github.com/user-attachments/assets/b9648c14-e33e-4b53-8ae6-980e2ef34c20)

Category Page(Abnormal):
![image](https://github.com/user-attachments/assets/0158e2f7-e181-45b4-b479-9c6f9bf57616)

Teams Page(Abnormal):
![image](https://github.com/user-attachments/assets/c0eb165b-72e8-49d7-8e29-6383dcf660ef)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ansiace** [comment]
hey @mdazfar2 I updated the footer as you can see the screenshot below below assign this issue to me



![{4D8D75CC-833D-479A-B8E1-645A41722BD4}](https://github.com/user-attachments/assets/135517d2-629a-4273-a784-45f1b9607a42)

**Comment by mdazfar2** [comment]
@ansiace Great. 


- Don't forget to give our repository a star and let me know once you've done it.

**Comment by ansiace** [comment]
> @ansiace Great.
> 
> * Don't forget to give our repository a star and let me know once you've done it.

Thanks for assign me I starred the repository
