### ISSUE TITLE
"Start Shopping" Button Link on Home Page

### ISSUE THREAD

**Issue by Shweta-1902** [mdazfar2/Ezyshop#317]
The "Start Shopping" button on the home page currently does not navigate users to the intended categories page, leading to a poor user experience. I would like to work on this issue by linking the button to the categories page.

In addition, I propose to enhance the functionality of the categories page by adding more features, such as:

Displaying featured products for each category
Adding filters for better product navigation
Improving the visual layout for a more engaging user experience
Please assign this issue to me under the labels gssoc ext and Hacktoberfest. 
Thank you!
![Screenshot (385)](https://github.com/user-attachments/assets/2c8d6236-c488-4520-bdef-e60e69bba140)

**Comment by mdazfar2** [comment]
Hii @Shweta-1902 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
