### ISSUE TITLE
[Feat] Implement Popup Sign-Up Page

### ISSUE THREAD

**Issue by RaiDevX8** [mdazfar2/Ezyshop#319]
### Description

The current sign-up process may be disruptive to users as it takes them away from the current page. A better user experience would be to allow users to sign up through a modal popup, without leaving the main page. Modal popups allow users to sign up without being redirected away from the current page

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @RaiDevX8, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
