### ISSUE TITLE
[BUG] Add hover effect to feature cards

### ISSUE THREAD

**Issue by Devaki01** [mdazfar2/Ezyshop#32]
### Description

**Description of the bug**
Current UI of the cards is not very interactive. 

**Expected Outcome**
Cards can be made interactive by using hover effects by adding subtle shadows to create depth and elevation when user hovers over them. 

### Screenshots

<img width="959" alt="image" src="https://github.com/user-attachments/assets/b634e899-e039-440e-a161-97544f796439">

### Any additional information?

I would love to contribute by working on this issue. Please assign it to me. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Devaki01 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- And please ⭐ our repo

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me
