### ISSUE TITLE
[Feat]Implement Dark Mode Theme switcher for Improved User Experience

### ISSUE THREAD

**Issue by RaiDevX8** [mdazfar2/Ezyshop#320]
### Description

Many users prefer dark mode for better readability and reduced eye strain, especially in low-light environments. The current light theme may not be ideal for users who work at night or prefer a darker aesthetic. Adding dark mode will enhance user comfort and accessibility.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Shiva-Bajpai** [comment]
@RaiDevX8 Go for it

**Comment by RaiDevX8** [comment]
@Shiva-Bajpai can you give labels please

**Comment by mdazfar2** [comment]
Hey @RaiDevX8, dark mode is a very good feature, but we have not decided to add the dark mode feature, we will let you know if it is needed in the future. Thank you for raising the issue.
- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
