### ISSUE TITLE
[Feat] Adding Contributer list in the Teams page

### ISSUE THREAD

**Issue by Jay-1409** [mdazfar2/Ezyshop#324]
### Description

I would like to add the contributer list in the teams section.
It shows how much work was doing while building this website hence increases its value.
Thank you.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @Jay-1409, this is a very good feature, but according to our website, it will not look good. Try to find any other bugs or features, which I am happy to assign to you. **Thank you!**

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
