### ISSUE TITLE
Elevate User Experience by Introducing a Custom Cursor and increasing responsiveness

### ISSUE THREAD

**Issue by AnujShrivastava01** [mdazfar2/Ezyshop#328]
# Description:

I propose adding a custom cursor to the website to enhance the overall user experience. A visually appealing and unique cursor design can significantly increase engagement by giving the site a more polished and modern feel, differentiating it from competitors.
Also I will work on the responsiveness of website .
# Benefits:
Improved User Experience
Brand Identity Enhancement
Increased Interaction

Assign this to me .
Thankyou !

**Comment by mdazfar2** [comment]
Hello @AnujShrivastava01, this is a very good feature, but according to our website, it will not look good. Try to find any other bugs or features, which I am happy to assign to you. **Thank you!**

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
