### ISSUE TITLE
[BUG] No redirection to homepage after login/signup

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#329]
### Screenshots

https://github.com/user-attachments/assets/c4c2d145-1a5d-4905-9d12-710f605d6e49

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hello @ShivanshPlays can you please describe it better what exactly you want to say.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.

**Comment by ShivanshPlays** [comment]
The user should be redirected to homepage after successful login/signup, which is not happening on the website right now

**Comment by Kavish-Paraswar** [comment]
I would like to work on this issue

**Comment by Kavita1928** [comment]
@ShivanshPlays assigned

**Comment by Kavita1928** [comment]
@ShivanshPlays any update?

**Comment by ShivanshPlays** [comment]
> @ShivanshPlays any update?
> 
> 

On it

**Comment by Kavita1928** [comment]
@ShivanshPlays  its more than a week , I am closing it
