### ISSUE TITLE
[BUG] Improve the UI of the user testimonial section 

### ISSUE THREAD

**Issue by Devaki01** [mdazfar2/Ezyshop#33]
### Description

**Description of the issue**
Current user testimonial section lacks interactivity as well as responsiveness. 

**Expected outcome**

1. Ensure the section is fully responsive, with testimonials stacking or adjusting properly across different screen sizes (desktop, tablet, mobile).
2. Add hover animations or fade-in effects to increase interactivity and engagement.
3. Include social media icons to make testimonials more engaging.

I would love to contribute by working on this issue. Please assign it to me.

### Screenshots

<img width="959" alt="image" src="https://github.com/user-attachments/assets/f34bf810-066c-43e1-b3d7-98e5d5fe3884">

<img width="584" alt="image" src="https://github.com/user-attachments/assets/e0c13017-5f88-4c65-8ea8-0b94e2d7ff2f">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Devaki01, great issue found! You are going to be assigned.

- Don't forget to join our official [Discord server](https://discord.gg/SEzpxqQG).
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
- And please ⭐ our repo

**Comment by mdazfar2** [comment]
hey @Devaki01 I hope you are doing well!

- It has been 1 days and you haven't responded to anything. Unfortunately, I have to close this issue because there are many duplicate issues raised. Please don't be discouraged. Thank you.
