### ISSUE TITLE
[BUG] Change the font styling of the whole website

### ISSUE THREAD

**Issue by shubhamjh15** [mdazfar2/Ezyshop#330]
### Description

the font in this website is giving un-professional looks, and i think the customers will be hesitant just because of some UI issues, i can make this much more professional looking.  

### Screenshots

![Screenshot 2024-10-08 174649](https://github.com/user-attachments/assets/adddf13e-33c0-45e4-bad0-f61bcb0225c4)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @shubhamjh15, As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
