### ISSUE TITLE
[Feat]MOUSE CURSOR TRAIL EFFECT

### ISSUE THREAD

**Issue by Priyanshi0112** [mdazfar2/Ezyshop#333]
### Description

This  effect will bring :

1.Enhanced User Engagement: The effect can increase user engagement and interaction with the website, making the user experience more enjoyable and memorable.

2.Visual Interest: The trail of colors or shapes can add visual interest to the website, making it more appealing and attention-grabbing.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @Priyanshi0112, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
