### ISSUE TITLE
[Feat]adding dark mode

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [mdazfar2/Ezyshop#335]
### Description

i want to add dark mode to this website and ill make sure it will look nice .

@mdazfar2 please assign me this issue.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @T-Rahul-prabhu-38, dark mode is a very good feature, but we have not decided to add the dark mode feature, we will let you know if it is needed in the future. Thank you for raising the issue.
- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
