### ISSUE TITLE
[Feat] adding backend logic to form and improving Ui

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [mdazfar2/Ezyshop#336]
### Description

i want to add backend logic using local storage and improve the UI of this form
<img width="1330" alt="Screenshot 2024-10-08 at 8 56 04 PM" src="https://github.com/user-attachments/assets/6c819276-05c7-4fa6-9af6-49a93d9cca28">

@mdazfar2 can you please assign me this task.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @T-Rahul-prabhu-38, we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
