### ISSUE TITLE
[Doc]: README file --> Enhancement in  Feature Descriptions

### ISSUE THREAD

**Issue by Poushmita** [mdazfar2/Ezyshop#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

We can enhance Feature Descriptions from the README file.

### Suggested Change

# Example 

### Current
Price Comparisons: Find the best deals by comparing prices across multiple stores.

### Improvement
Use our smart price comparison tool to automatically find the lowest prices on your favorite products from various stores. You can set up alerts for price drops, view historical price trends, and compare product ratings across stores for a smarter shopping experience.

### Rationale

By making these changes, we can help the README become more user-centric and informative, clearly showing how each feature benefits the users and providing a better understanding of how to use the platform.

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@Poushmita Thankyou for raising the issue but no such changes required . you can see some other issue i would be happy to assign you and make sure to star our [Repo](https://github.com/mdazfar2/Ezyshop).
