### ISSUE TITLE
[BUG] Discord Icon Render issue

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [mdazfar2/Ezyshop#338]
### Description

I want to update the logo of Twitter being used in your website and update in to the current X[Twitter] logo to remove ambiguity in the minds of the users.

### Screenshots

- Before

![image](https://github.com/user-attachments/assets/b9af0ab6-5e52-4351-8593-e99b3fc1065b)

- After

Will add the updated logo of X[Twitter]
![image](https://github.com/user-attachments/assets/3d0ca870-9c0f-4c4e-bebb-016146037f85)

### Any additional information?

I have not selected the browser since I am using the **Brave** browser. Since you have added a drop down for web browsers, you can add the following in it:

- Brave
- Opera/Opera GX

These are suggestions from my end since I have used them.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@rajdeepchakraborty-rc Make sure to change all symbols of twitter properly

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc Make sure to change all symbols of twitter properly

Sure. I will update you regarding the progress. I have one pending issue, after which I will start working on this issue.

**Comment by rajdeepchakraborty-rc** [comment]
@Kavita1928 Also please add the label of **hactoberfest-accepted** on the issue as it is checked for Hacktoberfest.
![image](https://github.com/user-attachments/assets/45be6e3e-d37b-4b62-9a64-e6dfa747a17b)

**Comment by rajdeepchakraborty-rc** [comment]
@Kavita1928 I noticed that the icons are not looking that attractive. I wanted to ask whether you want me to add a hover animation to your social icons. 
Reference video:

https://github.com/user-attachments/assets/704c84e6-60ba-47e6-8e6f-6d8b4a6a2669

Checkout the zoom animation on hover of the social icons.
If you do want me to add, then let me know add please add **level2** tag to the issue.

**Comment by rajdeepchakraborty-rc** [comment]
@mdazfar2 I had not started working on it. I felt like suggesting it while working on the icons. It is fine if you don't want me to add it. Thanks for letting me know. I will continue working on the icons. Hope you have a great day ahead.

**Comment by mdazfar2** [comment]
@rajdeepchakraborty-rc Thanks! Hope you have an amazing day too!"

- Don't forget to give our repository a star ⭐ and let me know once you've done it.

**Comment by mdazfar2** [comment]
@rajdeepchakraborty-rc Thanks! Hope you have an amazing day too!"

- Don't forget to give our repository a star ⭐ and let me know once you've done it.

**Comment by mdazfar2** [comment]
@rajdeepchakraborty-rc Thanks! Hope you have an amazing day too!

- Don't forget to give our repository a star ⭐ and let me know once you've done it.

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc Thanks! Hope you have an amazing day too!
> 
> * Don't forget to give our repository a star ⭐ and let me know once you've done it.

![image](https://github.com/user-attachments/assets/4c986964-c2bd-4b44-912a-0e7b50df0aea)
Already done sir. Otherwise I would not be able to keep track of the projects I am committing to 😂.

**Comment by rajdeepchakraborty-rc** [comment]
@mdazfar2 I wanted to ask something. I noticed that the icons are not responsive(do not redirect to the respective websites). Do you want me to add responsiveness to them?

**Comment by rajdeepchakraborty-rc** [comment]
> @mdazfar2 I wanted to ask something. I noticed that the icons are not responsive(do not redirect to the respective websites). Do you want me to add responsiveness to them since I am working on them?

@mdazfar2 Also please let me know about this too.

**Comment by mdazfar2** [comment]
Hello @rajdeepchakraborty-rc, sorry for the delay. Sometimes, some issues get overlooked while reviewing many.

- Actually, all icons are correct. Please check the deployed site, but on some pages like about and category, the Discord icon is not visible. Please correct only this and create a PR for it.

- Sync your fork and update it locally as well using the command below.

```bash
 git pull origin main
```

- Let me know if you need any help.

**Comment by rajdeepchakraborty-rc** [comment]
@mdazfar2 It seems you have merged someone's PR which will cause a conflict with my code.

**Comment by rajdeepchakraborty-rc** [comment]
@mdazfar2 Since I have lost all my progress, I am going with the current icons and adding responsiveness to the icons(if any)

**Comment by mdazfar2** [comment]
@rajdeepchakraborty-rc Sorry for the inconvenience, but we don't have an Instagram account. We will let you know if there's a need for it.

**Comment by rajdeepchakraborty-rc** [comment]
@mdazfar2 so for now I am just redirecting the Instagram icon to the home page of Instagram. You can add it later when you create one.

**Comment by rajdeepchakraborty-rc** [comment]
There is some issue with the CSS assigned to the pages. Please give me some time to resolve this issue:
![image](https://github.com/user-attachments/assets/5a9b7950-2347-4bc4-9a88-fd8862050504)

**Comment by mdazfar2** [comment]
But @rajdeepchakraborty-rc, we don't have an Instagram account, so it's not a good idea to redirect to the Instagram dashboard.

**Comment by rajdeepchakraborty-rc** [comment]
> But @rajdeepchakraborty-rc, we don't have an Instagram account, so it's not a good idea to redirect to the Instagram dashboard.

Ok I will remove it since that will create a problem for you.

**Comment by rajdeepchakraborty-rc** [comment]
@mdazfar2 Incase you have any other social, let me know. We can replace any one socials that you have with the Instagram. Otherwise we will keep that without a redirect.

**Comment by mdazfar2** [comment]
@rajdeepchakraborty-rc, right now we haven't created a Twitter account, and I don't have an Instagram account. I'll let you know if we create anything else instead of Instagram.

**Comment by rajdeepchakraborty-rc** [comment]
Ok thanks for the update. I am keeping the Instagram without a redirect.
Also wanted to let you know that I have finally identified the CSS bug that was causing the logo render issue. I am working on resolving it and will soon update you about it.

**Comment by mdazfar2** [comment]
@rajdeepchakraborty-rc Sure.

**Comment by rajdeepchakraborty-rc** [comment]
![image](https://github.com/user-attachments/assets/64a92c7f-1913-4cbe-b8fd-0174239edc2c)
Yup it is working. I will add the modifications to the other pages and let you know.

**Comment by rajdeepchakraborty-rc** [comment]
@mdazfar2 Here is the final outcome:

https://github.com/user-attachments/assets/ff3f42b1-2e07-4e85-b0b8-78ecfd4c7bcb

Let me know if the changes are fine. I would really appreciate if you assign this a **level3**, since I had to start working from scratch and also on a different issue.

**Comment by mdazfar2** [comment]
@rajdeepchakraborty-rc ok raise PR and update sync fork as well

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc ok raise PR and update sync fork as well

Please check PR #382

**Comment by rajdeepchakraborty-rc** [comment]
@mdazfar2 Really sorry to disturb you after the review, but could you please update the level on the issue to **level3**?

**Comment by rajdeepchakraborty-rc** [comment]
Thanks a lot!
