### ISSUE TITLE
set up backend and add an api to use the contact form 

### ISSUE THREAD

**Issue by AyushSharma72** [mdazfar2/Ezyshop#339]
### Description

i want to set up backend and add an api which lets the user to send messages via email to the project admin 

### Screenshots

![image](https://github.com/user-attachments/assets/f2395212-9d8a-4740-9a77-1908c54f2211)

please assign this issue to me @md

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @AyushSharma72, we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
