### ISSUE TITLE
[Feat]separate  login and Signup button, Create Sign Up Page

### ISSUE THREAD

**Issue by coderrrx-Brijesh** [mdazfar2/Ezyshop#34]
### Description

login/signup button seems to very basic want to separate them with same design. Also I want to create a complete signup page.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @coderrrx-Brijesh,

- You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)

- Please ⭐ our repo

**Comment by coderrrx-Brijesh** [comment]
OK GOT IT, I WILL KEEP THIS IN MIND.
