### ISSUE TITLE
[Feat] Add a responsive password strength meter during sign-up.

### ISSUE THREAD

**Issue by PavanTeja2005** [mdazfar2/Ezyshop#340]
### Description

I want to add a responsive password strength level meter which can display user's password strength when they are signing up.

It does.,
Display password strength to users as they create their passwords.
Improve user privacy by encouraging stronger passwords.
Enhance user experience with real-time feedback.

I'm working in gssoc extended. Please provide me suitable lab

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@PavanTeja2005 assigned

**Comment by PavanTeja2005** [comment]
I wanted to add this kind of meter during sign up.

![image](https://github.com/user-attachments/assets/8e47af7d-fb3a-4f52-aa34-d8f7a8f21418)

**Comment by PavanTeja2005** [comment]
Please assign me with a suitable level
