### ISSUE TITLE
[Feat] Height of cards in customer reviews are not same 

### ISSUE THREAD

**Issue by meghanakn473** [mdazfar2/Ezyshop#341]
### Description

maintaining same height of all card enhances the look of page, especially user checks and focus customer reviews before they proceed.

### Screenshots

![image](https://github.com/user-attachments/assets/e89be78a-defd-455e-a3bf-9f4891da61ab)

@mdazfar2 please assign me this issue

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@meghanakn473 you are assigned

**Comment by mdazfar2** [comment]
@meghanakn473 Don't forget to give our repository a star and let me know once you've done it.

**Comment by sayiamarora** [comment]
Hi @mdazfar2, I noticed that the heights of the cards in the Customer Reviews section are not uniform, which affects the visual consistency of the layout. I would like to implement a solution to ensure that all review cards have the same height, improving the overall aesthetics and user experience. Please let me know if I can proceed with this improvement

**Comment by sunidhi3** [comment]
assigned me this issue

**Comment by Kavita1928** [comment]
As no response from previous assignee @sayiamarora assigned

**Comment by mdazfar2** [comment]
I apologize, but I need to close this issue for now. Please don't be discouraged!
