### ISSUE TITLE
[Feat] Hovering effects on properties of website

### ISSUE THREAD

**Issue by meghanakn473** [mdazfar2/Ezyshop#343]
### Description

Adding hovering effects gives better look to website and highlights the properties.

### Screenshots

![image](https://github.com/user-attachments/assets/b8a3afd7-125b-4cbc-b2ed-2d488d9a7c06)

@mdazfar2 please assign me this issue

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @meghanakn473 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
