### ISSUE TITLE
[Feat] Dark Mode Button

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [mdazfar2/Ezyshop#345]
### Description

Dark mode toggle button feature can be added to improve UI

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by jangirvipin** [comment]
please assign me this issue

**Comment by Kavita1928** [comment]
@Arghya-Chakraborty0812 thanks for raising this issuHope you star our [Repo](https://github.com/mdazfar2/Ezyshop).e but for 
and star our [Repo](https://github.com/mdazfar2/Ezyshop).
