### ISSUE TITLE
[Feat]We can enhance or make sign in page more better

### ISSUE THREAD

**Issue by shruti9935** [mdazfar2/Ezyshop#348]
### Description

pop up type or a good background
assign the task to me

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@shruti9935 can u provide a screenshot of that page after modification for better clarification

**Comment by shruti9935** [comment]
Currently, I am unable to see your EzyShop front page. I don’t know if it’s due to some glitch, but what I’m thinking is to add an animation where a shopping cart comes in, and as it moves, a sign-in page pops up.
![Screenshot 2024-10-09 012046](https://github.com/user-attachments/assets/3e7e955c-afcd-495f-8deb-3c13c9fb1543)
or can add this type of background not this slighlty better than this .

**Comment by mdazfar2** [comment]
Hey @shruti9935, please don't mind, but according to our website's concept, it doesn't match. Thanks for raising the issue.

- Don't forget to give our repository a star and let me know once you've done it.
