### ISSUE TITLE
[BUG] Unresponsive Login and signup feature & the header in Contact where home/ contact us is present those are not taking us back to home page 

### ISSUE THREAD

**Issue by MrityunjaySingh09** [mdazfar2/Ezyshop#35]
### Description

The signup/login button is not accepting responses so i would like to work on it and make it better working  as well as the home and contact us anchor tag is not responsive as i could redirect to home page on  clicking onto it. I would like to solve this issue under  gssoc'24 EXTENDED and hacktoberfest

### Screenshots

![Screenshot 2024-10-02 094419](https://github.com/user-attachments/assets/06911765-74cf-40aa-b658-5609e5fd971d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by thakuratul2** [comment]
@MrityunjaySingh09 assigned

**Comment by MrityunjaySingh09** [comment]
Okay Thanks completing it asap

**Comment by rutikakengal** [comment]
i like to improve signup and login page and Contact us page and give responsiveness to webpage

**Comment by mdazfar2** [comment]
Hey @MrityunjaySingh09, please let me know when you create the PR. Otherwise, unfortunately, I will have to assign this issue to someone else.

**Comment by MrityunjaySingh09** [comment]
I already did yesterday only..isn't showing?

**Comment by mdazfar2** [comment]
nope @MrityunjaySingh09

**Comment by rutikakengal** [comment]
I like to work on it

**Comment by mdazfar2** [comment]
Okay! @rutikakengal I you want and create PR quick you are going to be assigned

**Comment by MrityunjaySingh09** [comment]
But i already did the work

**Comment by mdazfar2** [comment]
where @MrityunjaySingh09?

**Comment by MrityunjaySingh09** [comment]
Just 5 min wait updating

**Comment by mdazfar2** [comment]
no response yet closing issue for now
