### ISSUE TITLE
[Feat] Adding github icon in footer for quick navigation to the repo

### ISSUE THREAD

**Issue by devxMani** [mdazfar2/Ezyshop#353]
### Description

adding icon and link 

### Screenshots
![image](https://github.com/user-attachments/assets/dacdcc70-d7ee-4094-a06c-277c3a27f4b2)

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @devxMani, as we don't plan to add this feature, can you please work on another issue which I’d be happy to assign to you?

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
