### ISSUE TITLE
[Feat]Add  Recently Viewed Products option

### ISSUE THREAD

**Issue by a-kkuuu** [mdazfar2/Ezyshop#356]
### Description

I want to add this issue so that  users  can track products that they have recently viewed and display them on a “Recently Viewed” section for easy access. can you assign this issue to me?

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @a-kkuuu, actually we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
