### ISSUE TITLE
cursor style

### ISSUE THREAD

**Issue by abhi200446** [mdazfar2/Ezyshop#357]
### Description

i want to change the cursor style in website there we are using a normal cursor  I added screenshots.if you  don't like the cursor style which I chosen I will modify according to your wish please give label hacktoberfest and gssoc ext 

### Screenshots

from 

https://github.com/user-attachments/assets/bafb93a0-f2e7-42e7-ae12-9dc073f712df
to

https://github.com/user-attachments/assets/611323f6-925f-45d9-b744-20e45e1c6d17

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @abhi200446, this is a very good feature, but according to our website, it will not look good. Try to find any other bugs or features, which I am happy to assign to you. **Thank you!**

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.

**Comment by abhi200446** [comment]
Hey, I just starred the repository

**Comment by abhi200446** [comment]
if u wish i want to add discord at the social media section please assign me to do my first contribution @pr
![image](https://github.com/user-attachments/assets/440de9b7-f7d1-4b5b-804f-8ffb9597f0a1)
