### ISSUE TITLE
Not Fitting in Screen

### ISSUE THREAD

**Issue by Kavish-Paraswar** [mdazfar2/Ezyshop#358]
The last box of the link adn social media icons is not fitting with the screen 
![image](https://github.com/user-attachments/assets/38828eb1-2b01-4fef-9184-58c464770266)
Please assign me this under , GSOC'24 extended and level 1 atleast.

**Comment by mdazfar2** [comment]
hello @Kavish-Paraswar you are assigned and create PR as soon as possible and update sync fork if you already forked our repository.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.

**Comment by sunidhi3** [comment]
assigned this issue

**Comment by Kavish-Paraswar** [comment]
This issue is resolved

**Comment by mdazfar2** [comment]
@Kavish-Paraswar @sunidhi3 @arpit74170 

Guys, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
