### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by abhi200446** [mdazfar2/Ezyshop#359]
### Description

 if u wish i want to add discord at the social media section please assign me to do my first contribution @pr

### Screenshots

![image](https://github.com/user-attachments/assets/440de9b7-f7d1-4b5b-804f-8ffb9597f0a1)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @abhi200446, one of the contributors emailed me about working on this footer's icon. Please don't feel discouraged, but I have to close this issue for now. Please find any other bugs or good issues, or features, which I'm happy to assign to you.
