### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by mayu-z** [mdazfar2/Ezyshop#36]
### Description

Heyy,

 So I was thinking of adding a carousel automated so the idea is that:

1. It'll automatically change on it's own every few seconds.
2. It will also have buttons to switch from right to left and left to right. 
3. I would start by adding the services you provide on each window and there will be links in button so the user can click on it and read the specifics. 
4. It'd give the user a bit idea about what the website is offering primarily. 

I have attached a sample screenshot 

Since you  know first impressions are really important I would like to work on that.

Thank you

### Screenshots

![Screenshot 2024-10-02 113135](https://github.com/user-attachments/assets/814e5de1-bad1-426e-82b3-c70f5f7832c2)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by thakuratul2** [comment]
@mayu-z assigned
