### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by abhi200446** [mdazfar2/Ezyshop#361]
### Description

if you wish i want to add getstarted button in navbar beside the login please assign me @pr

### Screenshots

![image](https://github.com/user-attachments/assets/9000a86c-04ef-4389-be33-7ef93f051600)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hello @abhi200446, As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
