### ISSUE TITLE
[BUG] Enhance "Start Shopping" Button

### ISSUE THREAD

**Issue by neeru24** [mdazfar2/Ezyshop#363]
### Description

The "Start Shopping" button on the homepage is small and merely text, making it difficult for users to locate. I propose redesigning it to create a more prominent button with improved UI and engaging hover effects.

This enhancement will make the button more visible and user-friendly.

Could you please assign me this issue? I’m excited to implement these changes and will submit a PR shortly after completing the enhancements.

Thank you!

### Screenshots

![image](https://github.com/user-attachments/assets/ae07478f-7c37-4ba2-8542-89155872e687)
![image](https://github.com/user-attachments/assets/6fdfda65-b177-4404-a8d7-9caa9d3e9d43)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@neeru24 issue has been alreay assigned to someone make sure not to raise duplicate issues
and star our [Repo](https://github.com/mdazfar2/Ezyshop).
