### ISSUE TITLE
[Feat] Add Hover Effect on Homepage Cards

### ISSUE THREAD

**Issue by neeru24** [mdazfar2/Ezyshop#364]
### Description

The cards on the homepage currently lack hover effects. I would like to implement a subtle hover effect on these cards to enhance user interaction and visual appeal.

**Benefit:**
Adding hover effects will improve the user experience by providing visual feedback, making the cards more engaging and encouraging users to explore the content.

Could you please assign me this issue? I would love to work on this enhancement and submit a PR once it's completed.

Thank you!

### Screenshots

![image](https://github.com/user-attachments/assets/5ed00ae2-e478-44d2-bf72-0e299d7d282e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @neeru24, as we are not decided to add any hover effect to our website, we will let you know if there's any work related to it. You can search for other issues/bugs and raise an issue accordingly. Thank you for raising the issue.
- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
