### ISSUE TITLE
[BUG] OTP sign-up issue

### ISSUE THREAD

**Issue by gouravi19** [mdazfar2/Ezyshop#365]
### Description

OTP is not being sent successfully. The error message displayed is 'Error sending OTP. Please try again.' I'm attaching a screenshot of the error for your reference. I'd like to investigate this issue further and propose potential solutions. Would you be available to discuss this and provide guidance?

### Screenshots

<img width="1440" alt="Screenshot 2024-10-09 at 2 17 26 PM" src="https://github.com/user-attachments/assets/19838de2-1cbf-4953-9a6f-e3ca2dc39691">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Ankitha2130** [comment]
I can work on this issue please assign this issue to me.

**Comment by mdazfar2** [comment]
Hey @gouravi19 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Don't forget to give our repository a star and let me know once you've done it.
