### ISSUE TITLE
[Feat]Add more slides in Home section

### ISSUE THREAD

**Issue by mansi066** [mdazfar2/Ezyshop#368]
### Description

I can add more slides

Enhanced Visual Appeal: More slides can make your website look more dynamic and visually interesting, capturing visitors' attention.

Improved Content Organization: They allow you to break up content into digestible sections, making it easier for users to navigate through your information.

Interactivity: Slides add an element of interactivity, encouraging users to engage with the content by clicking through different sections.

### Screenshots

![Screenshot 2024-10-09 154200](https://github.com/user-attachments/assets/c978ceb8-bd1a-4efd-ad8c-52eef710b3bb)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mansi066** [comment]
Please assign me I want to work on this issue

**Comment by mdazfar2** [comment]
Hello @mansi066, as of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
