### ISSUE TITLE
[Login/SignUp popup]

### ISSUE THREAD

**Issue by Abhishek2634** [mdazfar2/Ezyshop#37]
### Description

when clicking on login signup button nothing happens i want to add a login signup popup where users can add email and their name if thet want to login and email, name password if thet want to signup.

### Screenshots

<img width="238" alt="Screenshot 2024-10-02 at 11 35 42 AM" src="https://github.com/user-attachments/assets/507102cd-119d-488f-9500-738ba5350f86">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Abhishek2634** [comment]
@mdazfar2  please assign this issue to me.

**Comment by mdazfar2** [comment]
@Abhishek2634 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Don't forget to join our official [Discord server](https://discord.gg/SEzpxqQG).
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
- And please ⭐ our repo
