### ISSUE TITLE
[Feat]

### ISSUE THREAD

**Issue by rahulkumarparida** [mdazfar2/Ezyshop#377]
### Description

# added a dark mode for your site
 which will help in mor adaptive loos to the website
**small request can you give me the labels for gssoc level 2 and hacktoberfest accepted**
it took so much long as i have to read almost 10000 code of css in you file please

### Screenshots

![Screenshot 2024-10-09 193018](https://github.com/user-attachments/assets/6309f772-fd16-4c85-bff4-fe551e0d3d81)
please check my pull request

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @rahulkumarparida, dark mode is a very good feature, but we have not decided to add the dark mode feature, we will let you know if it is needed in the future. Thank you for raising the issue.
- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
