### ISSUE TITLE
[Feat] Enhance hover effect of the home page

### ISSUE THREAD

**Issue by Ankitha2130** [mdazfar2/Ezyshop#379]
### Description

I will work on hover effect of the home page when the cursor is pointed to it.
Please assign it to me under gssoc-ext, hacktoberfest, and a suitable level label.

### Screenshots

![image](https://github.com/user-attachments/assets/f2b4f185-f4e5-4360-9257-688432f40f74)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Ankitha2130, as we are not decided to add any hover effect to our website, we will let you know if there's any work related to it. You can search for other issues/bugs and raise an issue accordingly. Thank you for raising the issue.
- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
