### ISSUE TITLE
[Feat] OTP Not Being Sent in Registration Process

### ISSUE THREAD

**Issue by kavya410004** [mdazfar2/Ezyshop#380]
### Description

The current registration process relies on sending an OTP to the user's email for verification, but OTP emails are not being sent as expected. This prevents users from completing the registration, impacting the overall user experience. To resolve this issue and simplify the registration flow, I propose adding a new register section that eliminates the OTP step and instead requires users to set a username, new password, and confirm password fields directly on the signup page.

**Proposed Solution:**
- Create a new register section on the signup page with the following fields:
   1. Username
   2. New Password
   3. Confirm Password
- Ensure that users can register directly by providing these details without requiring email OTP verification.
- Add validation to ensure that password and Confirm Password fields match.

### Screenshots

![image](https://github.com/user-attachments/assets/1c0fd58e-843a-4eb8-b92b-1f08da5d233f)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@kavya410004 go ahead.
