### ISSUE TITLE
[Feat] Add to Cart Option Unavailable

### ISSUE THREAD

**Issue by shrashti-19** [mdazfar2/Ezyshop#383]
### Description

The "Add to Card" feature is unavailable on the website. Users are unable to add items to their shopping cart, which affects the overall user experience.
Please assign this task to me @mdazfar2 .

### Screenshots

![Screenshot 2024-10-09 222423](https://github.com/user-attachments/assets/9d16ab4a-e225-48cc-a6da-afc60c6c303d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by shrashti-19** [comment]
discord server link not valid

**Comment by mdazfar2** [comment]
hey @shrashti-19 join our discord server from this [link](https://discord.gg/Rg8T5gtE) Thank you for letting me know

**Comment by mdazfar2** [comment]
Hello @shrashti-19, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.

**Comment by shrashti-19** [comment]
Yes, I have given your repository a star.
Thank you
