### ISSUE TITLE
POP UP MESSAGE

### ISSUE THREAD

**Issue by Codewithmeowmeow** [mdazfar2/Ezyshop#384]
### Description

Just like in websites like myntra and other we get a pop up message when we open website i want to create that kindly assign it to me.

### Screenshots

![popup](https://github.com/user-attachments/assets/e347d825-e5dd-46e4-ad00-00409fb8edce)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @Codewithmeowmeow, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
