### ISSUE TITLE
[Feat]: Add forgot password to login page

### ISSUE THREAD

**Issue by SalehaTabassum** [mdazfar2/Ezyshop#385]
### Description

In login page i would like to add forgot password option,which will lead to a form that will help in login.
@mdazfar2 assign this issue to gssoc ext and hackatoberfest
![Screenshot 2024-10-09 232823](https://github.com/user-attachments/assets/d5b54189-f197-476c-adac-1c124cab1592)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @SalehaTabassum, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
