### ISSUE TITLE
 i want to change review section and make attrative

### ISSUE THREAD

**Issue by ragineedarade** [mdazfar2/Ezyshop#395]
![{AC5A3291-ED85-4D2A-9470-B927D3E0B393}](https://github.com/user-attachments/assets/d4a77df5-fea5-4256-8f43-cde74e024ae4)

**Comment by Kavita1928** [comment]
@ragineedarade  assigned , make sure it match with website theme

**Comment by ragineedarade** [comment]
can you add gssoc level it will help me for incress my rank

**Comment by ragineedarade** [comment]
![{5E0FD256-B1D5-44E7-A764-A39C256D8ACE}](https://github.com/user-attachments/assets/d8ad3e7a-fc04-40d8-b270-2af81a2b0e81)

i completely complete and made some attrative also add star to look like someone give review

**Comment by mdazfar2** [comment]
Hey @ragineedarade, for now, I will close this issue. Please don't feel discouraged. I will make sure to assign you new issues, bugs, or features that are really needed for our website. Thank you.



- Raginee, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by ragineedarade** [comment]
no
