### ISSUE TITLE
i want to add  whatsup  in right  communication  will become eassy

### ISSUE THREAD

**Issue by ragineedarade** [mdazfar2/Ezyshop#397]

**Comment by Kavita1928** [comment]
@ragineedarade thanyou for raising the issue but this feature not required for now ,You can work work on other issue 
and firstly make sure to star our [Repo](https://github.com/mdazfar2/Ezyshop).  and Join our [Discord Server](https://discord.gg/Rg8T5gtE) to collaborate and discuss further.
