### ISSUE TITLE
[BUG] Issues in blog.html

### ISSUE THREAD

**Issue by Deeptig9138** [mdazfar2/Ezyshop#4]
### Description

Empty Links: Several <a> tags have empty href attributes; these should point to relevant pages.
Accessibility: Improve button text for clarity and provide descriptive alt text for images.
Duplicate Content: Ensure blog articles are unique; avoid duplicate entries.
Redundant CSS: Simplify CSS classes to avoid repetition.
JavaScript Libraries: Verify that all libraries used are the latest stable versions for security and features.
Semantic HTML: Use more semantic elements (like <header>, <main>, <footer>) for better structure.
Image Attributes: Ensure all images have meaningful alt attributes for better accessibility.

Please assign this to me @

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Deeptig9138 Isse acknowledged! You are going to be assigned.

**Comment by uzefaqureshi06** [comment]
can you assign me in your project

**Comment by mdazfar2** [comment]
Hey @uzefaqureshi06 it is already assigned to @Deeptig9138

**Comment by mdazfar2** [comment]
hey @Deeptig9138 I hope you are doing well!

- It has been 2 days and you haven't responded to anything. Unfortunately, I have to close this issue because there are many duplicate issues raised. Please don't be discouraged. Thank you.
