### ISSUE TITLE
[Doc]: Add content to CONTRIBUTING.md 

### ISSUE THREAD

**Issue by Devaki01** [mdazfar2/Ezyshop#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Contributing.md file is empty right now.

### Suggested Change

I would love to contribute by adding relevant content  to CONTRIBUTING.md which includes guidelines for reporting issues, making feature requests, setting up project, committing changes, submitting code, updating documentation, and following the pull request process.

### Rationale

A well-structured CONTRIBUTING.md would ensure consistency in code quality and collaboration and help beginners contribute better. 

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Devaki01, go ahead and create an attractive contributing guideline. I will give you a sample that I created for another repo. You can check it out [here](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).

**Comment by mdazfar2** [comment]
@Devaki01 
- Don't forget to join our official [Discord server](https://discord.gg/SEzpxqQG).
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
- And please ⭐ our repo

**Comment by mdazfar2** [comment]
Hey @Devaki01, please let me know when you create the PR. Otherwise, unfortunately, I will have to assign this issue to someone else.

**Comment by mdazfar2** [comment]
Hey @Devaki01, please let me know when you create the PR. Otherwise, unfortunately, I will have to assign this issue to someone else. ***thank you***.

**Comment by Devaki01** [comment]
Yes, I will complete it by today.
