### ISSUE TITLE
Change the Button to other colour due to low contrast

### ISSUE THREAD

**Issue by aryanadla** [mdazfar2/Ezyshop#402]
"Start Shopping" button  is not clearly visible due to low contrast.

![Screenshot 2024-10-10 143826](https://github.com/user-attachments/assets/45989104-996f-4405-8abd-cb1b74722808)

Please Assign me this issue with labels @mdazfar2 , Thank you!

**Comment by mdazfar2** [comment]
@aryanadla You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
