### ISSUE TITLE
Start Shopping button not working

### ISSUE THREAD

**Issue by sakshamsaraf23** [mdazfar2/Ezyshop#403]
### Description

when we click on start shopping button it should divert us to the sign up page but instead it's not responding.

### Screenshots

https://github.com/user-attachments/assets/9d5ab621-fe90-4a2f-9c0e-91adbcc5953b

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by tushar-agarwal7** [comment]
@mdazfar2  can u assign this issue to me

**Comment by mdazfar2** [comment]
Hello @sakshamsaraf23, that's good for shopping button, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.

**Comment by sakshamsaraf23** [comment]
Done

**Comment by Kuldeepcoder2006** [comment]
@mdazfar2 can u assign this issue to me

**Comment by mdazfar2** [comment]
@tushar-agarwal7 @Kuldeepcoder2006 Can you please give star ⭐to our repository

**Comment by Kuldeepcoder2006** [comment]
@mdazfar2 can u assign this issue to me
