### ISSUE TITLE
An alignment issue

### ISSUE THREAD

**Issue by vansh-m012** [mdazfar2/Ezyshop#404]
### Description

![Screenshot 2024-10-10 150234](https://github.com/user-attachments/assets/2ae17317-c31b-4cf4-bf88-3d8fd47270a9)

 
The images on the left and right sides are not visually aligned.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @vansh-m012, this is not an alignment issue or bug; this is how we want it. It's not a bug, but our intended design. Thank you for raising the issue though.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
