### ISSUE TITLE
[Feat]: Make the Navbar Glasomorphic

### ISSUE THREAD

**Issue by ayyush08** [mdazfar2/Ezyshop#409]
### Description

Hey, Would you like to make the navbar appear glasomorphic?
If yes, please assign this issue to me.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by tushar-agarwal7** [comment]
@mdazfar2 can u assign this issue to me

**Comment by ayyush08** [comment]
@tushar-agarwal7 I created the issue to be assigned for myself bro🤡

**Comment by ayyush08** [comment]
Ok, I'll try to find out and reopen another issue then
