### ISSUE TITLE
DARK THEME FUNCTIONALITY TOGGLE SWITCH

### ISSUE THREAD

**Issue by STDYGIT** [mdazfar2/Ezyshop#41]
### Description

I would like to implement a comprehensive dark theme for your website, recognizing the growing number of users who prefer this aesthetic for their daily tasks. I can customize the design using an appropriate color palette to enhance user experience and accessibility.

below are the switch toggle have a look

### Screenshots

![Screenshot 2024-10-02 at 12 44 31 PM](https://github.com/user-attachments/assets/3b300a2e-e02c-4e74-8d0d-f27ec9ea8615)
![Screenshot 2024-10-02 at 12 44 47 PM](https://github.com/user-attachments/assets/e71e5e66-15f9-49a6-b1a7-65bfb8152693)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by STDYGIT** [comment]
Sir, I would like to work on this feature and would appreciate it if you could assign it to me for Hacktoberfest and GGSOC '24. I believe this is a level 2 task, as it requires a complete overhaul of the page styles. Thank you!

**Comment by mdazfar2** [comment]
hey @STDYGIT As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
- And please ⭐ our repo
