### ISSUE TITLE
[BUG] Logout button not correct

### ISSUE THREAD

**Issue by Asjdnnc** [mdazfar2/Ezyshop#410]
### Description

Username is currently displayed on the LOGOUT button, which may lead to confusion for users regarding its function.

### Screenshots

<img width="1690" alt="Screenshot 2024-10-10 at 4 32 23 PM" src="https://github.com/user-attachments/assets/e22687cf-928f-4de0-8119-34525334f114">

### Any additional information?

The username should be displayed next to the logout button, and the logout button should be clearly visible.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Asjdnnc** [comment]
@mdazfar2 Pls assign me under label gssoc-ext, hacktoberfest-accepted

**Comment by mdazfar2** [comment]
Hey @Asjdnnc As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
