### ISSUE TITLE
Enhancing Email Validation and User Experience on EzyShop

### ISSUE THREAD

**Issue by gouravi19** [mdazfar2/Ezyshop#411]
### Description

Key Changes:
Correct Email Validation: Implement a robust email validation mechanism that accurately checks for the presence of the @ symbol and other essential components of a valid email address.
User-Friendly Error Messages: Provide clear and informative error messages when users enter invalid email addresses, guiding them towards correct input.
Real-time Validation: Validate email addresses in real-time as users type, providing immediate feedback and preventing submission of invalid data.
Optional Email Field: Consider making the email field optional if it's not strictly necessary for the core functionality of the website.
Expected Benefits:
Improved user experience by preventing errors and providing clear guidance.
Increased data accuracy and reduced manual corrections.
Enhanced website credibility and professionalism.
Potential increase in user conversions and engagement.
By addressing this email validation issue, you can contribute to a more user-friendly and reliable EzyShop website.
![Change the logo (2)](https://github.com/user-attachments/assets/e1147559-1f24-46c0-981f-95ed943288fd)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @gouravi19 great issue found! You are going to be assigned.

- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md).

- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
- And please ⭐ our [repo](https://github.com/mdazfar2/ezyshop) and let me know that you starred.

**Comment by gouravi19** [comment]
I've completed the assignment, and I would appreciate your guidance on the
correct process to submit it via Git. Could you please let me know the
steps I should follow or any specific instructions for the submission?

**Comment by mdazfar2** [comment]
Hey @gouravi19, no worries! It is very easy to contribute to open source via git. I will provide you with the guidelines below:

- Firstly, you have to fork our [repo](https://github.com/mdazfar2/ezyshop).

- Then create an [issue](https://github.com/mdazfar2/ezyshop/issue/) which you already raised.

- Clone your forked repository, set it up on your local machine, and open the terminal in the directory where you want to work. See the command below:

    ```bash
    git clone https://github.com/gouravi19/ezyshop.git
    ```

- The Ezyshop project code will be cloned to your local machine.

- Make changes in VS Code, and after completing the changes, open the terminal and run the following commands:

    ```bash
    git status
    ```

    ```bash
    git add .
    ```

    ```bash
    git commit -m "write your commit message here"
    ```

    ```bash
    git push origin main
    ```

- That's all good! Now open your forked GitHub repository of `Ezyshop`.

- Click on the `Contribute` button.

- Click on `Create new pull request`.

- Write the description and title, scroll down, and finally click `Create pull request`.

- Congrats! 🥳 You've made your first pull request to this project repo.

---

Hope you understand! If you get stuck anywhere, feel free to reach out to me on [Discord](https://discordapp.com/users/877531143610708028) or [LinkedIn](https://linkedin.com/in/md-azfar-alam/).

**Comment by gouravi19** [comment]
Thank you so much for your guidance

It's done sir you can check it

**Comment by gouravi19** [comment]
#411 i have created a pull request

**Comment by gouravi19** [comment]
sir i have created a pull request can you please check it once i have completed it #527

**Comment by gouravi19** [comment]
sir i have created a pull request can you please check it once i have completed it https://github.com/mdazfar2/Ezyshop/pull/527  DO LET ME KNOW IF ANY CHANGES REQUIRED
