### ISSUE TITLE
Improve Visual Contrast in Header Buttons

### ISSUE THREAD

**Issue by Kamini8707** [mdazfar2/Ezyshop#413]
### Description

The "Start Shopping" and "Explore Stores" buttons in the header section of the website have low visual contrast, making them difficult to read, especially for users with visual impairments.

Proposed Solution:

Increase Contrast:
Update the button colors to ensure the text stands out clearly against the background. For example, use a darker background color (e.g., dark blue #0056b3) with white text to create a contrast ratio that meets WCAG guidelines.
Hover Effects:
Implement distinct hover states for the buttons. For example, change the background color slightly when a user hovers over the buttons, to provide clearer visual feedback.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @username, this is a very good feature, but according to our website, it will not look good. Try to find any other bugs or features, which I am happy to assign to you. **Thank you!**

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
