### ISSUE TITLE
[Feat]Add More Categories for Greater Variety

### ISSUE THREAD

**Issue by rishika105** [mdazfar2/Ezyshop#414]
### Description

 Currently, the project includes only three categories, limiting the variety of products that can be offered. I propose adding additional categories to enhance the platform's diversity and allow users to browse a broader range of products. This update will improve the user experience by providing more options and better aligning with a scalable e-commerce platform. I'd like to contribute by implementing this feature to extend the platform's functionality.

Please assign me.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@rishika105 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
