### ISSUE TITLE
[Feat]Want to implement Password restriction criterias in signup/login

### ISSUE THREAD

**Issue by Antik004** [mdazfar2/Ezyshop#417]
### Description

Hi, I want to work on the implementation some password restrictions/criterias like 8 character or more length, inclusion of special characters etc. in the login or signup. Otherwise its taking even simple passwords such as 'abcd' or no. sequences as passwords which is a security issue. Please assign me this issue.

### Checklist

- [x] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Antik004 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
