### ISSUE TITLE
[BUG] Want to add favicon

### ISSUE THREAD

**Issue by Suvadip-sana** [mdazfar2/Ezyshop#42]
### Description

Hi! I am Suvadip, want to work on this project.
**ISSUE**
There is no Favicon icon except Home page. I think all pages have to be a Favicon.

I want to add same favicon that present on home page in all other pages. 

I would be grateful  if you assign me that issue. 

### Screenshots

![image](https://github.com/user-attachments/assets/ad03fac1-a799-4878-8b3c-db0b9da109ec)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by thakuratul2** [comment]
@Suvadip-sana Great and assigned

**Comment by Suvadip-sana** [comment]
Thank You
