### ISSUE TITLE
[BUG] Footer Link not working

### ISSUE THREAD

**Issue by rupeshv2121** [mdazfar2/Ezyshop#420]
### Description

Footer links not working 

pls assign me under label gssoc-ext, hacktoberfest-accepted
@mdazfar2 

### Screenshots

![Link](https://github.com/user-attachments/assets/42bf8cc9-ede2-4cb6-902f-bb83e259314d)

### What browser are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@rupeshv2121 I have been observing for some time. You are raising issues again and again. That's not a good way to work on open source. Why don't you raise and describe everything in a single issue?
