### ISSUE TITLE
Issue Title: "Add Relevant Banners to Each Navbar Category"

### ISSUE THREAD

**Issue by AswaniBolisetti** [mdazfar2/Ezyshop#421]
@mdazfar2 
![banner](https://github.com/user-attachments/assets/90e627e2-d732-4799-89ee-967ad749fad9)

Issue Description: I would like to add a relevant banner to each category in the navbar. This will provide visual cues and context for each category, enhancing user experience and making navigation more intuitive and engaging.

could you please assign this issue to me under level2, hacktoberfest-accepted, gssoc-ext

**Comment by mdazfar2** [comment]
Hello @AswaniBolisetti, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue. ***Thank you!***

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.

**Comment by AswaniBolisetti** [comment]
Thank you
I have given a star already
