### ISSUE TITLE
[Feat]Show a message in the Categories section after submitting the Contact Us form and validate input entries.

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [mdazfar2/Ezyshop#422]
### Description

Display a confirmation message in the Categories section after form submission.
Validate input formats to ensure correct user entries.

### Screenshots

![Screenshot 2024-10-10 210206](https://github.com/user-attachments/assets/e9c31dac-30d8-4f9a-a94f-9588913d72a7)

The Name input field accepts invalid characters, allowing entries that are not alphabets.
The Email input field accepts capital letters and entries starting with numbers, which do not comply with proper email formatting.
Input validation needs to be implemented to restrict both fields to their respective valid formats.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by NIKITABARANWAL890** [comment]
@mdazfar2 sir, Kindly assign me this issue under GSSOC'24 ext. I'm eager to contribute actively.

**Comment by mdazfar2** [comment]
@NIKITABARANWAL890 Thank you for raising the issue.

As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.

**Comment by NIKITABARANWAL890** [comment]
> @NIKITABARANWAL890 Thank you for raising the issue.
> 
> As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
> 
> * Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.

Okay sir
