### ISSUE TITLE
[BUG] Comment Cards are not aligned properly.

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [mdazfar2/Ezyshop#423]
### Screenshots

![Screenshot 2024-10-10 212322](https://github.com/user-attachments/assets/38bb4ce0-e0fd-41cd-8652-354393136f82)

It could be improved to be more visually appealing.

### Any additional information?

@mdazfar2 Sir, kindly assign me this issue. I am eager to contribute effectively.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@NIKITABARANWAL890 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
