### ISSUE TITLE
[Feat]: prize comparion tool

### ISSUE THREAD

**Issue by anjany06** [mdazfar2/Ezyshop#426]
### Description

The Price Comparison Tool enables users to effortlessly compare product prices across various local stores. By displaying real-time pricing information, users can quickly identify the best deals and make informed purchasing decisions. This feature enhances transparency and saves customers time and money while shopping. With an intuitive interface, users can easily navigate through different product categories, ensuring they find the best value for their needs.
plz assign to me sir @mdazfar2 under labels gssoc-exd and hactoberfest

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Actually, @anjany06, we don't have any store right now. We are working on that, and the store manager will add their respective shop. As shoppers, we can view and order products according to our requirements. So as of now, I don't think we need this, but in the future, we will let you know if needed.

- Starred our repository we are very close to reach 100 
***Thank you!***
