### ISSUE TITLE
[Feat]: Delievery Time slot selection

### ISSUE THREAD

**Issue by anjany06** [mdazfar2/Ezyshop#428]
### Description

The Delivery Time Slot Selection feature allows users to choose their preferred delivery times when placing orders. By offering flexible time slots, this feature enhances customer convenience, ensuring that deliveries arrive at times that suit their schedules. Users can select from available options, making the shopping experience more personalized and efficient. This capability can lead to increased customer satisfaction and loyalty, as it accommodates individual needs and reduces the likelihood of missed deliveries.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @anjany06, can you please describe more about your issue? I cannot understand exactly what you are trying to say.

**Comment by anjany06** [comment]
Sir actually I want to add a feature in your web "Delievery slot time
selection" Where users can choose the desirable time to take delievery of
their product

**Comment by mdazfar2** [comment]
User for what? Did you read the README.md file? We have two dashboards, one for the store manager and the other for the shopper.

**Comment by Kavita1928** [comment]
@anjany06 I am closiing this issue as no response
