### ISSUE TITLE
"Add to cart" and "wishlist" buttons are missing

### ISSUE THREAD

**Issue by prakruthiprasad20** [mdazfar2/Ezyshop#429]
#Adding the "Add to cart" and "wishlist" buttons will improves user experience, saves time and encourages impulse buying.
Adding couple moe categories like 
i. Stationery items
ii. Sports equipments
iii. Medicines

Adding new categories to your shop improves navigation, making it easier for customers to find what they’re looking for. It enhances the shopping experience by exposing users to new products and tailored recommendations. This organization encourages return visits and higher customer satisfaction. Overall, it helps attract diverse customer segments and can boost sales by catering to various interests.

**Comment by mdazfar2** [comment]
Hey @prakruthiprasad20, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
