### ISSUE TITLE
[Feat] Building home page in next.js

### ISSUE THREAD

**Issue by Bhum-ika** [mdazfar2/Ezyshop#430]
### Description

I will convert the code in next.js and will build the exact replica.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Thank you @Bhum-ika for raising the issue. You are assigned to it.
