### ISSUE TITLE
[Feat]Adding Dark mode and its adaptability 

### ISSUE THREAD

**Issue by abhishekpanthee** [mdazfar2/Ezyshop#431]
### Description

I want to work on adding dark mode toggle button and adpatinion to dark mode

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @abhishekpanthee, dark mode is a very good feature, but we have not decided to add the dark mode feature, we will let you know if it is needed in the future. Thank you for raising the issue.
- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
