### ISSUE TITLE
[Feat] Blog display Page in NextJS version of website

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#436]
### Description

there is no Blog display Page page in Nextjs version of the website

![image](https://github.com/user-attachments/assets/d0113a88-0434-4feb-8bf3-4f39fe6ec247)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays you are assigned.
