### ISSUE TITLE
[Feat] there is no Contact page in Nextjs version of the website

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#437]
### Description

there is no Contact Page page in Nextjs version of the website

![image](https://github.com/user-attachments/assets/24356d22-440c-4a4b-9bea-003834fb16d4)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Go ahead @ShivanshPlays
