### ISSUE TITLE
[Feat] Add individual blog display page.

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#438]
### Description

 Linked to the list of blogs page, I will create a full blog display page where the full blog is displayed

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays Also add the option of `My order`,  `Cart`, and `whist list` as shown in the below screen record in new issue it can make 1 level label.

<br>

https://github.com/user-attachments/assets/82326aa3-f0be-4b2e-b1fe-ebe15fc407cf

**Comment by ShivanshPlays** [comment]
okay
