### ISSUE TITLE
To create login / signup feature and navigating to that particular page in header.

### ISSUE THREAD

**Issue by clownfish1805** [mdazfar2/Ezyshop#44]
### Description

To develop a Login and Signup feature and ensure proper navigation from the header to these respective pages.

**Login/Signup Pages:**

1. Create separate pages for Login and Signup with fields such as **Email/Username and Password.**
2. Include **form validation for inputs** and appropriate error handling (e.g., incorrect login credentials or weak passwords).
3. Display **error messages** for failed login attempts or incomplete signup information.
4. Ensure the **design of these pages follows** the website’s branding, color scheme, and overall layout.

I could handle the frontend part, including HTML, CSS, and JavaScript.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @clownfish1805 thank you for raising the issue.

As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Don't forget to join our official [Discord server](https://discord.gg/SEzpxqQG).
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
- And please ⭐ our repo
