### ISSUE TITLE
Feature Addition of ChatBot

### ISSUE THREAD

**Issue by UTkARsh-RaJ01** [mdazfar2/Ezyshop#440]
### Description

Addition of chatbot feature will help the user as it will answer queries related to the website.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [x] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@UTkARsh-RaJ01  assigned

**Comment by PulkitShubham** [comment]
@Kavita1928 I would like to work on this project ........kindly assign it to me
