### ISSUE TITLE
[Feat] adding My order, Cart, and wish list in navbar 

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#442]
### Description

Adding the above options in the navbar

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays you are assigned.
