### ISSUE TITLE
[BUG] The CategoriesPage of the NEXTJS version of the website is not responsive on smaller screen sizes

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#445]
### Description

I will add appropriate Tailwind classes and restructuring to make it responsive for small screen sizes.

Kindly assign me this issue! :)

### Screenshots

![image](https://github.com/user-attachments/assets/df776c24-99fc-4ee8-8b3d-ecaca2346d89)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays you are assigned.
