### ISSUE TITLE
[BUG] I would like to create form validation for "Leave a comment" in Blog Details page

### ISSUE THREAD

**Issue by clownfish1805** [mdazfar2/Ezyshop#45]
### Description

I would like to work on implementing form validation for the "**Leave a Comment**" form. Here’s my approach:

**Field Validation:**

1. Ensure the "Name" and "Comment" fields are not left empty before submission.
2. Validate the "Email" field to ensure the input follows a proper email format (e.g., name@example.com).
3. Set a character limit for the "Comment" field to avoid excessively long comments (e.g., 500 characters).

**Error Messages:**

1. Provide clear error messages below the fields if validation fails (e.g., "Please enter your name" or "Invalid email address").
2. Highlight fields with errors by using red borders or labels to make it easy for users to identify the problem.

**Submit button** :
Submit button will only work when all the required fields are filled and follows validation.

### Screenshots

![image](https://github.com/user-attachments/assets/d638817a-036a-4a55-be4b-2df0d491d806)
![image](https://github.com/user-attachments/assets/fd47626f-ff1b-460c-a121-13758908595d)

### Any additional information?

The form is submitted eventhough the mandatory fields are not filled.
The email id is not checked properly it just shows @ and anyother character after that. It doesn't properly checks the email id.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by clownfish1805** [comment]
@mdazfar2 I would like to work on this issue. Please assign me this issue.

**Comment by thakuratul2** [comment]
@clownfish1805 assigned

**Comment by clownfish1805** [comment]
@mdazfar2 
I have raised PR for this issue. Please check.
