### ISSUE TITLE
Description of some of the People are in Lorem Ipsum

### ISSUE THREAD

**Issue by ThunderShadows** [mdazfar2/Ezyshop#451]
The John Doe and description details of the website is vague and not relevant to the website.

@mdazfar2 

I shall make the content of the website as well the description of the website Ezyshop throughout the website proper by making sure it delivers then right content to the users. Not the example content.

![image](https://github.com/user-attachments/assets/746575fb-54e3-4fbc-bafa-724dff0c63a8)

**Comment by Kavita1928** [comment]
@ThunderShadows  assigned

**Comment by Kavita1928** [comment]
@ThunderShadows any update ?

**Comment by mdazfar2** [comment]
@ThunderShadows, sorry, I apologize, but I need to close your issue. It's been a long time, and you haven't responded. Thank you.
