### ISSUE TITLE
[BUG] Login / Sign up button text not visible

### ISSUE THREAD

**Issue by PATILYASHH** [mdazfar2/Ezyshop#452]
### Description

[BUG] Login / Sign up button text not visible while hovering it . the color is mixing with the background color .

### Screenshots

![image](https://github.com/user-attachments/assets/778444b0-38d6-47c5-bd86-db199cba7dc1)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
Hey @PATILYASHH  thanks for raising the issue but issue has been already resolved
