### ISSUE TITLE
[BUG] Icons is not visible

### ISSUE THREAD

**Issue by PATILYASHH** [mdazfar2/Ezyshop#453]
### Description

Discord icon is not rendering in multiple pages 

- About page
- Categories page
- Blog Grid 
- Blog Detail
- Contact us 

### Screenshots

![image](https://github.com/user-attachments/assets/419c11d5-b6ef-416c-8063-3d8e8b318a72)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kuldeepcoder2006** [comment]
assign it to me I  can fix this bug

**Comment by mdazfar2** [comment]
Hey @Kuldeepcoder2006 You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)



- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐
