### ISSUE TITLE
ISSUE RELATED TO HOVERING EFFECT OF CARDS

### ISSUE THREAD

**Issue by HarshVardhanSalve** [mdazfar2/Ezyshop#454]
### Description

THERE IS NO ANY HOVERING EFFECT OF CARDS IN "OUR FACILITY" SECTION

### Screenshots

![Screenshot 2024-10-11 124502](https://github.com/user-attachments/assets/1c93fb81-67d5-4f11-a7e0-a67767d0a301)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@HarshVardhanSalve As those are facilities so we don't need hover effect there ,You can raise someother issue and firstly make sure to star our [Repo](https://github.com/mdazfar2/Ezyshop).
