### ISSUE TITLE
[Feat]The front view of each navigation section could be enhanced.

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [mdazfar2/Ezyshop#455]
### Description

![Screenshot 2024-10-11 135909](https://github.com/user-attachments/assets/0b1ca45e-1940-4d02-a882-bfa6d930c2a5)

I can enhance the visual appeal of each navigation link pages.

@mdazfar2 kindly assign me this issue.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@NIKITABARANWAL890 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
