### ISSUE TITLE
[Feat] About Page Responsiveness & Favicon Update

### ISSUE THREAD

**Issue by kavya410004** [mdazfar2/Ezyshop#456]
### Description

1. **Responsiveness Issue:**
   - The **About** page in the current Next.js version is not fully responsive across different screen sizes (mobile, tablet, desktop). 
   - On smaller screens (e.g., mobile), certain elements like text blocks, images, and layout components are not adjusting as expected, resulting in a poor user experience. The layout may break or require excessive scrolling.
   - The goal is to ensure that the page adapts seamlessly across all devices using responsive design techniques 

2. **Favicon Update:**
   - The **favicon** currently in place is the default Next.js icon. We need to update this to the correct favicon that represents Ezyshop.

**Proposed Solution:**
   - **Responsiveness:** I can work on improving the About page’s responsiveness using CSS media queries and adjusting the layout for smaller screen sizes.
   - **Favicon:** I will also update the favicon to reflect the correct branding.

**Question:**

- Are there any specific guidelines or aspects I should be aware of while working on this issue? Any particular design or functionality considerations to keep in mind?

### Screenshots

![Screenshot 2024-10-11 140642](https://github.com/user-attachments/assets/dd1196bf-7b86-43e6-92dc-bbea60fde4a5)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @kavya410004, please make sure that it is fully responsive, especially for mobile. I mean, check it on the iPhone 12 Pro since the iPhone 12 size is widely used nowadays. Hope you understand.

**Comment by mdazfar2** [comment]
hey @kavya410004 It's been 2 days and you didn't respond anything please let us know.

**Comment by kavya410004** [comment]
> hey @kavya410004 It's been 2 days and you didn't respond anything please let us know.
 I have finished working on it, I will be raising a pr soon
