### ISSUE TITLE
[Doc]: "Shop now" cards are poorly designed.

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [mdazfar2/Ezyshop#460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

![Screenshot 2024-10-11 163113](https://github.com/user-attachments/assets/b8901e20-243b-4471-af26-a2590e2645cd)

All the images are blur.
Card are seems to be coming out of the screen
Not visually appealing

@mdazfar2  sir kindly assign me this issue, i will definitely make it a worthy contribution.

### Suggested Change

Images should be improved
Hover effect to change the image 
Proper styling and alignment
Wishlist(heart) button can be added

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by Diya-Saha2005** [comment]
Hello admin! What I would like to contribute to this project is for the enhancement and adding more shop now cards option .
The pictures selected for visual representation could be improved.
I would like you to please assign me the issue to solve it. https://github.com/mdazfar2/Ezyshop an early reply/assignment of the task will be appreciated.
![Screenshot (366)](https://github.com/user-attachments/assets/2be1e8b3-c81d-4374-a638-558445ea8822)

**Comment by Kavita1928** [comment]
@NIKITABARANWAL890  assigned

**Comment by Kavita1928** [comment]
@Diya-Saha2005 generate your own issue you .This is not correct way to work on open source

**Comment by NIKITABARANWAL890** [comment]
Hey @mdazfar2, ig you've merged the PR but didn't close it here?

**Comment by mdazfar2** [comment]
@NIKITABARANWAL890, please mention your PR issue number so that the issue automatically closes after merging your PR. See below; if you create a PR again, don't forget to do it like this:

closes #issue_number


That's how the issue automatically closes after merging the PR. Hope you understand.
