### ISSUE TITLE
[Feat] ADD mor cards in categories

### ISSUE THREAD

**Issue by isimarjitsingh** [mdazfar2/Ezyshop#461]
### Description

As i am seeing categories page have only 3 cards in it , we need to add some  more cards in  the form of carousel ,i add cards like sports accessories, makeup accessories , grocery ,garments and many more , this will helps to improve user experience.

### Screenshots

![Screenshot 2024-10-11 182710](https://github.com/user-attachments/assets/a471df28-3954-46a2-9ab6-28002d6fc4bb)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Diya-Saha2005** [comment]
Hello admin! there's some lack of shoping cards . I would like to add more cards to it for example- makeup and beauty essentials, skincare essentials, bakery items etc. Please assign me this issue to be solved and an early reply from you will be appretiated @mdazfar2 
![Uploading Screenshot (366).png…]()

**Comment by mdazfar2** [comment]
Hello @isimarjitsingh, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐
