### ISSUE TITLE
[Feat]: Adding Privacy Policy & Terms of Services to the website

### ISSUE THREAD

**Issue by Priyank00007** [mdazfar2/Ezyshop#462]
### Description

I will create 2 pages which will be for privacy policy and terms of services which will make the website more real world

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @Priyank00007, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐

**Comment by Priyank00007** [comment]
@mdazfar2 for sure sir
