### ISSUE TITLE
[BUG] when we click on add to cart button below the items it shows item is added , but there is not cart in nav bar where user can see their added items

### ISSUE THREAD

**Issue by Siddhant432** [mdazfar2/Ezyshop#463]
### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@Siddhant432 this issue has been already raised by other.Don't raise duplicate issue ,find a new issue and make sure to star our [Repo](https://github.com/mdazfar2/Ezyshop).
