### ISSUE TITLE
[Feat]Terms page for the website.

### ISSUE THREAD

**Issue by Vaishh18** [mdazfar2/Ezyshop#464]
### Description

We need to implement a "Terms" page for the website to ensure users are informed about our terms of service and policies. This page will detail the terms and conditions for using the site, including usage rights, legal disclaimers, and data privacy agreements.

Proposed Solution:
Create a dedicated "Terms" page that can be easily accessed from the website footer. This page should:

Display the terms of service in a clear and organized manner.
Include sections for:
General terms and conditions
User responsibilities

### Screenshots

![Screenshot 2024-10-11 203500](https://github.com/user-attachments/assets/4fcc8399-5de7-4dd0-9df7-147203419cc4)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @Vaishh18, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐
