### ISSUE TITLE
[Feat] I want to implement search functionality and Notifications feature to the website.

### ISSUE THREAD

**Issue by JahnavikaGopalbvrith** [mdazfar2/Ezyshop#466]
### Description

search functionality -Helps users quickly find products or content on the website.
Notifications-Sends timely updates to users, keeping them engaged and informed even when they’re not on the site.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@JahnavikaGopalbvrith go for it

**Comment by JahnavikaGopalbvrith** [comment]
@Kavita1928 thank you for assigning me. I will let you know the update soon.

**Comment by JahnavikaGopalbvrith** [comment]
@Kavita1928, I sent you a PR 3 days ago. Please review and let me know if any changes are required.
