### ISSUE TITLE
[BUG] Alignment in Contact Us Page

### ISSUE THREAD

**Issue by Roshn1** [mdazfar2/Ezyshop#467]
### Description

In Contact Us For Any Query , there is no proper alignment of the icons i.e no equal gap in between 

### Screenshots

![Screenshot 2024-10-11 220936](https://github.com/user-attachments/assets/c804fac5-a06a-443a-af75-2bddc8052595)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by FarhanBijapur** [comment]
Hi, could you please assign this issue to me under GSSoC-EXT and Hacktoberfest? I'd love to work on it. Thanks!

**Comment by Kavita1928** [comment]
@Roshn1 show me a screenshot after modifying it for better understanding

**Comment by mdazfar2** [comment]
@Roshn1 I apologize, but I need to close this issue for now. Please don't be discouraged!
