### ISSUE TITLE
[Feat]Mouse Cursor Trail Effect

### ISSUE THREAD

**Issue by Priyanshi0112** [mdazfar2/Ezyshop#469]
### Description

: The mouse cursor trail effect is a visual effect that creates a trail of light behind the mouse cursor as it moves across the screen.

The effect is achieved by creating a custom cursor element and using CSS to style it with a neon-like glow. JavaScript is used to track the mouse movement and update the cursor's position accordingly.

The mouse cursor trail effect enhances user experience, adds visual interest, and reinforces branding. It provides a sense of interactivity, dynamism, and energy to the website. The trail effect can be customized to match the website's brand and identity.

Thank You

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@Priyanshi0112 assigned

**Comment by Kuldeepcoder2006** [comment]
can u assign it to me

**Comment by mdazfar2** [comment]
Hey @Priyanshi0112, please don't mind, but the mouse cursor movement effect doesn't look good according to our website. We have an E-commerce website, and have you seen any E-commerce website with a mouse movement effect? I apologize, Priyanshi, but I need to close your issue.

Please search for any other issue that we really need. I'll be sure to assign it to you with a good label.




- Priyanshi, Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐
