### ISSUE TITLE
[Feat] Adding input validations 

### ISSUE THREAD

**Issue by Gauravtb2253** [mdazfar2/Ezyshop#470]
### Description

Hello I would like to add proper input form validations to the login and signup pages
Pls assign this to me

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@Gauravtb2253  Can you explain your issue properly .

**Comment by Gauravtb2253** [comment]
> @Gauravtb2253 Can you explain your issue properly .

I will add proper validation checks for the form fields ensuring they are in the correct format and not empty

**Comment by mdazfar2** [comment]
@Gauravtb2253 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
