### ISSUE TITLE
Home Page Improvement

### ISSUE THREAD

**Issue by Abbas7120** [mdazfar2/Ezyshop#471]
![image](https://github.com/user-attachments/assets/5e9cb467-5e71-4178-81d1-a86eec3fd4fb)
 As you see Start Shopping is not visible and EzyShop heading is also not appealing .Please assign this issue to me with level 1 gssoc-extd hacktoberfest labels

**Comment by Kavita1928** [comment]
Hey @Abbas7120  thanks for raising the issue but issue has been already resolved

**Comment by Abbas7120** [comment]
I dont think so as Ezyshop is too small and is not appealing I will add ezyshop logo with its name their now you can assign this to me with level 1 hacktoberfest gssoc

**Comment by Abbas7120** [comment]
Its not completed till now !
