### ISSUE TITLE
Sign up page link not clickable 

### ISSUE THREAD

**Issue by HS202022** [mdazfar2/Ezyshop#472]
### Description

 could not access sign up page

### Screenshots

https://github.com/user-attachments/assets/2b811db1-9e29-42dc-b78b-163205a31c14

### Any additional information?

I want to work on this

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@HS202022 assigned

**Comment by HS202022** [comment]
@Kavita1928 can i change the ui?

**Comment by mdazfar2** [comment]
No, @HS202022, please don't change the UI. Implement this on the current UI.



- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐

**Comment by mdazfar2** [comment]
Hey @HS202022 Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by HS202022** [comment]
> Hey @HS202022 Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

I can help
