### ISSUE TITLE
[BUG] Password visibility button

### ISSUE THREAD

**Issue by Devanshu1603** [mdazfar2/Ezyshop#474]
### Description

There must be a password visibility button on login and sign-up page to let user know whether he/she is entering the correct one.

### Screenshots

![Screenshot 2024-10-12 032056](https://github.com/user-attachments/assets/af0052a0-2473-4f46-a495-3a1d82e9ecb4)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Devanshu1603** [comment]
@ShivanshPlays  please assign me this issue under gssoc-extended , hacktober fest accepted and with appropriate levels.

**Comment by Bhaveshbade10** [comment]
i want to work on this issue assign the label hacktober fest

**Comment by mdazfar2** [comment]
Hey @Devanshu1603 You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐
