### ISSUE TITLE
[BUG] Wrong Content Render after clearing searchbar

### ISSUE THREAD

**Issue by shreysachani** [mdazfar2/Ezyshop#479]
### Description

Issue: When using the search bar in the Electronics or Groceries section, after clearing the search input, the content for the Fashion category is incorrectly rendered instead of the respective section's content.

Steps to Reproduce
Navigate to the Groceries section.
Search for "apples" in the search bar.
Clear the search input.
Observe that content for Fashion is rendered instead of Groceries.

Alternatively:

Navigate to the Electronics section.
Search for "laptop" in the search bar.
Clear the search input and search again.
Observe that content for Fashion is rendered instead of Electronics.

Expected Behavior
When the search input is cleared in the Electronics or Groceries sections, the corresponding section's content should be rendered (either Electronics or Groceries, depending on the section).

Actual Behavior
After clearing the search input, the content for the Fashion section is displayed instead of the correct category's content.

Additional Context
Please refer to the attached video demonstrating the bug.

https://github.com/user-attachments/assets/57e93fe5-ae8e-44f3-bd0c-da2d71d7953d

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by shreysachani** [comment]
Please assign this issue to me under hacktoberfest

**Comment by mdazfar2** [comment]
Great issue found, @shreysachani. Do it so that when a user searches, the product will instantly show without clicking the search icon. For example, if we type the letter "A," all products starting with "A" should be visible. I want it like this.

- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐

**Comment by shreysachani** [comment]
Started working on this issue.

**Comment by mdazfar2** [comment]
Solved
