### ISSUE TITLE
I want to add a sticky navbar.

### ISSUE THREAD

**Issue by Kratika-Solanki** [mdazfar2/Ezyshop#48]
### Description

As I checked the navbar is not sticky so when we scrolls down to the site, we do not get an option for selecting the other menus of navbar. We have to go again to to the home page for selecting the menus again. If the navbar will be sticky so the user can select the options at any part of the website.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by thakuratul2** [comment]
@Kratika-Solanki assigned

**Comment by Pranith-Kantamneni** [comment]
@thakuratul2  @mdazfar2  The issue of sticky navbar still exists so if it is open I can work upon it.
can you please assign this to me .

**Comment by Kratika-Solanki** [comment]
@mdazfar2 by mistakenly the PR has been deleted by me, can I still work on this issue?

**Comment by Ishajain0** [comment]
Please assign this task to me I would like to work on it ....

**Comment by mdazfar2** [comment]
Sure @Ishajain0 @Kratika-Solanki, you guys can work together and create a PR with Co-authored commits. If you want to know more about Co-authored commits, please visit [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors).
