### ISSUE TITLE
[BUG] Issues like footer alignment, social media logo, hover effect to the login / signup page,etc.

### ISSUE THREAD

**Issue by rupeshv2121** [mdazfar2/Ezyshop#481]
### Description

I want to make changes in the footer alignment in Category Section as well as social media logo not visible , I want to increase font size in the navbar elements so that i looks good, In home page alignment of our facilties title is not centered, Learn about us is written two times.

pls assign me under label gssoc-ext, hacktoberfest-accepted, level 2 at least

@mdazfar2 @Kavita1928 

### Screenshots

![Screenshot 2024-10-12 085513](https://github.com/user-attachments/assets/c9d5d3f2-ea4d-47dc-835a-17bd56e13c17)
![Screenshot 2024-10-12 085554](https://github.com/user-attachments/assets/635d402b-abed-4ccb-aa25-701c13b43394)
![Screenshot 2024-10-12 085622](https://github.com/user-attachments/assets/d9f0a846-9cac-48ae-a9cb-461abbb6d36e)
![Screenshot 2024-10-12 085424](https://github.com/user-attachments/assets/885e94f3-bed2-4e44-bc71-323f967bd6ad)

### What browser are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @rupeshv2121 You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)

- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐

**Comment by rupeshv2121** [comment]
@mdazfar2 sir I check before raising the issue at that time one raise the issue but after that someone raise and assigned so that my issues get duplicate so what I can do ?
