### ISSUE TITLE
[BUG] Align the headings in center

### ISSUE THREAD

**Issue by Abankita** [mdazfar2/Ezyshop#483]
### Description

Some of the headings in the home page are left aligned while some are center aligned. I will align all of them in center to give a uniform look. 

### Screenshots

![Screenshot (78)](https://github.com/user-attachments/assets/99f3698d-ea7f-4db3-8f53-a60faddb790a)
![Screenshot (79)](https://github.com/user-attachments/assets/b82fe7f6-93ce-4478-abdb-eb12ffd8f23a)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Abankita, thank you for noticing this. Actually, this is not a fault; this is exactly what we want. Can you please look at any other issues/bugs or features that I'm happy to assign to you?


- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐
