### ISSUE TITLE
[BUG] The logo of Discord is wrong in Contact Us Page

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [mdazfar2/Ezyshop#484]
### Description

The discord logo in the footer section of the contact us page looks wrong.

### Screenshots

<img width="1431" alt="Screenshot 2024-10-12 at 11 07 34 AM" src="https://github.com/user-attachments/assets/1db9ad96-bd35-43ea-b349-463dff814658">

### Any additional information?

Please assign me this issue under GSSOC level1.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Arghya-Chakraborty0812 you are assigned.

- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐

**Comment by Arghya-Chakraborty0812** [comment]
Pls can you assign me hacktober-fest as well
