### ISSUE TITLE
[Feat] : Scroll to top button 

### ISSUE THREAD

**Issue by YasirKhan231** [mdazfar2/Ezyshop#485]
### Description

Add an scroll to top button by which user can go directly tot he top of the website  smoothly 

### Screenshots

![Screenshot 2024-10-11 183334](https://github.com/user-attachments/assets/05ada787-4956-438e-b02a-14fe9e87a1bc)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @YasirKhan231, thank you for raising the issue, but our website already has a scroll-to-top button. Please take a look at another issue, which I'm happy to assign to you.



- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐
