### ISSUE TITLE
[Feat] Adding dark mode 

### ISSUE THREAD

**Issue by Ashish-Patnaik** [mdazfar2/Ezyshop#486]
### Description

I want to add dark mode in this website to make it more better, so please assign me

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Ashish-Patnaik, dark mode is a very good feature, but we have not decided to add the dark mode feature, we will let you know if it is needed in the future. Thank you for raising the issue.
- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐

**Comment by Ashish-Patnaik** [comment]
Ok sir and here is my star
