### ISSUE TITLE
[Feat]: Cart page

### ISSUE THREAD

**Issue by ArchanRD** [mdazfar2/Ezyshop#487]
### Description

Add cart page to website. The addition of cart page will unlock following feature:
- View or edit items in cart
- Can order the items ( future scope )
This page will can scale the website features. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @ArchanRD You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)

- please give a star ⭐ to our repo.
