### ISSUE TITLE
[Feat]: Firebase integration

### ISSUE THREAD

**Issue by ArchanRD** [mdazfar2/Ezyshop#488]
### Description

Currently the user credentials are stored in localStorage, which is not suitable when scaling the application. I would like to offer a feature - firebase integration. It is very simple to use. It is fast and can help us with scaling web app when integrating cart, orders, user dashboard and many more functionalities.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @ArchanRD, actually we don’t plan to integrate with Firebase right now. We will let you know if there is any need in the future, and also we will do the backend after the conversion to the Next.js version.

- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐
