### ISSUE TITLE
ISSUE : ADDING A IMAGE SLIDER 

### ISSUE THREAD

**Issue by HarshVardhanSalve** [mdazfar2/Ezyshop#489]
### Description

WE CAN ADD AN INTERACTIVE IMAGE SLIDER ON THE MAIN PAGE.

### Screenshots

![Screenshot (75)](https://github.com/user-attachments/assets/90a0da4c-9f0c-40cf-9ec1-318f4963638b)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @HarshVardhanSalve, this is a very good feature, but according to our website, it will not look good. Try to find any other bugs or features, which I am happy to assign to you. ***Thank you!***

- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐
