### ISSUE TITLE
I want to add a mail to link at the footer section on email address.

### ISSUE THREAD

**Issue by Kratika-Solanki** [mdazfar2/Ezyshop#49]
### Description

I want to add mail to link on the email address so the user can directly get an option for dropping an email. This will make them easy to contact with us. And I want to make the footer more interactive

### Screenshots

![image](https://github.com/user-attachments/assets/d5ac94eb-bb12-4c12-a80e-cfa2a32adcbd)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by thakuratul2** [comment]
@Kratika-Solanki assigned

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me
