### ISSUE TITLE
[Feat]  Add Location Selection Feature to the Website

### ISSUE THREAD

**Issue by 09viv** [mdazfar2/Ezyshop#490]
### Description

Implement a location selection feature that allows users to choose their location. This feature will enhance user experience. Users should be able to either manually enter their location or option of use current location.

Expected Benefits:
Improved user engagement by providing relevant content based on location.
Enhanced functionality for services requiring location inputs, such as delivery options or local events.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @09viv, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
