### ISSUE TITLE
[BUG] Images Not Displaying on the "About Us" Page in Next.js

### ISSUE THREAD

**Issue by kavya410004** [mdazfar2/Ezyshop#493]
### Description

The images on the "About Us" page are currently not being displayed in the Next.js version of the project. This issue needs to be addressed to ensure that all images load correctly and are visible to users on the "About Us" page.

**Proposed Solution:**

I would like to take on this issue and work on fixing the image display problem. This would involve:

- Debugging the image import paths or sources.
- Ensuring images are correctly optimized and rendered in the Next.js environment.
- Testing the solution across various devices to ensure consistency.

### Screenshots

![image](https://github.com/user-attachments/assets/9881af3a-630f-4984-a202-0d160deea4c3)
![image](https://github.com/user-attachments/assets/e68affc5-f87b-4244-8d3c-b4a73fd47da1)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@kavya410004 you are assigned.
