### ISSUE TITLE
[Feat]Explore Store button working

### ISSUE THREAD

**Issue by KrHimanshu18** [mdazfar2/Ezyshop#495]
### Description

Change the "Explore Store" button to redirect to the login page instead of only showing an alert message

### Screenshots

https://github.com/user-attachments/assets/6f0ef3b8-2f1c-437c-aa49-df5050e67928

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@KrHimanshu18  assigned
