### ISSUE TITLE
Updating the vertical scrollbar.

### ISSUE THREAD

**Issue by Tanushree084** [mdazfar2/Ezyshop#498]
### Description

Hey @mdazfar2 ,

I want to add transition effect to the vertical scrollbar.
currently it is :
<img width="26" alt="image" src="https://github.com/user-attachments/assets/93b14059-0bb7-4455-8de2-c14cfd0400b2">

Can you  please assign me this issue?

### Screenshots

<img width="26" alt="image" src="https://github.com/user-attachments/assets/a1fcb7f7-b3ba-4482-90db-b1d4d626fd3c">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Tanushree084 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
