### ISSUE TITLE
Adding Contributors page

### ISSUE THREAD

**Issue by TBorundia** [mdazfar2/Ezyshop#499]
### Description

I can add the option to navigate contributor page.
I will show the github profile of all the contributors worked for the project.
I will ensure to make the page UI similar to the theme and also responsive for all screens.
It will directly fetch the data from the repository.

It will show,
Transparency: It shows transparency in the project's development and highlights the collaborative effort behind it.
Engagement: It helps build a community by encouraging more people to contribute and get involved.
Networking: It provides an opportunity for users to connect with contributors, potentially leading to more collaboration and support.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @TBorundia As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
