### ISSUE TITLE
[Feat]: Adding Animations  on the product and article picture

### ISSUE THREAD

**Issue by Kcode15** [mdazfar2/Ezyshop#5]
### Description

Adding animations to the photos under 'Shop Your Favourite Product' and 'Latest Article from Blog' will enhance the UI, making it more interactive and visually appealing.
![image](https://github.com/user-attachments/assets/d2de017c-fc94-4ca0-a627-d2bda053586c)
![image](https://github.com/user-attachments/assets/37145d5c-34e0-42fe-bab7-929958b340ab)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hey @Kcode15 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

**Comment by Kcode15** [comment]
okk, Thank you.

**Comment by mdazfar2** [comment]
Hey @Kcode15, I will reopen the issue and mention you if there is a need in the future.
