### ISSUE TITLE
[BUG] Logged in user's username not showing in pages other than **home** page, not showing logout prompt on clicking.

### ISSUE THREAD

**Issue by muhafiz5814** [mdazfar2/Ezyshop#50]
### Description

Not rendering the signup/login pages when clicking the button from pages other than **Home** page.
After logging in, only home page's login/signup button on header is changing to user's username.  
All other main pages such as about, contacts and other pages still showing only the login/signup button.  
Also when clicking the username button on home page while already logged in, it's asking to logout. It's not asking in any other page.  
I want to fix the issue.  

### Screenshots

Home page
![Ezyshoping home page](https://github.com/user-attachments/assets/1ccf9fe9-37ba-4d6c-81ef-2270e6a13bfc)
![Ezyshoping home page logout prompt](https://github.com/user-attachments/assets/032c6a5d-3758-459f-b990-f72b7d0b51a1)

Other pages
![Ezyshoping about page](https://github.com/user-attachments/assets/51563002-c632-4868-88bb-806875b1c0be)
![Ezyshoping contacts page](https://github.com/user-attachments/assets/d3bb552e-d131-4b33-b74b-55f2a4458a8c)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by muhafiz5814** [comment]
Hey @mdazfar2 I would like get assigned this issue.

**Comment by mdazfar2** [comment]
@muhafiz5814 issue acknowledged! you are assigned.
