### ISSUE TITLE
[BUG] Discord logo not visible in several pages

### ISSUE THREAD

**Issue by varshapandiann** [mdazfar2/Ezyshop#501]
### Description

Discord logo is not visible in the following pages
1. About
2. Categories
3. Blog Grid
4. Blog Detail

### Screenshots

![image](https://github.com/user-attachments/assets/c31b6cd7-4976-4edd-b438-6a2a423dd296)
![Screenshot 2024-10-12 162927](https://github.com/user-attachments/assets/c03d4bed-3ffd-43f0-9dbb-b7e3c93fafe5)
![image](https://github.com/user-attachments/assets/3883793f-209b-4614-851a-84e6d7d334bf)
![image](https://github.com/user-attachments/assets/ec324601-a539-4a8d-8ebc-36f3c751d962)

### Any additional information?

Can you please assign me this issue?

### What browser are you seeing the problem on?

Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @varshapandiann You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)


- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by varshapandiann** [comment]
The previous issue only covered the **Contact Us** page. I have raised issue for the other pages, excluding that one.

> Hey @varshapandiann You have raised a duplicate issue; it was already raised by someone else.
> 
> * Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
> * This is not the way to work on open source :)
> * Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
