### ISSUE TITLE
text written twice

### ISSUE THREAD

**Issue by Kajalmehta29** [mdazfar2/Ezyshop#502]
<img width="900" alt="Screenshot 2024-10-12 at 5 04 29 PM" src="https://github.com/user-attachments/assets/5fa2d676-64b5-44d6-8255-981ad992fcdd">

Here "learn about us" is written twice which is not looking nice. I want to fix this issue.

Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by Kavita1928** [comment]
heyy @Kajalmehta29  the issue has been resolved , you can work on someother issue and make sure to star our [Repo](https://github.com/mdazfar2/Ezyshop).
