### ISSUE TITLE
[BUG] in the home page , it's written two times learn about us instead of one time

### ISSUE THREAD

**Issue by ekta1810** [mdazfar2/Ezyshop#503]
### Description

In the home page , it's written two times learn about us instead of one time.

### Screenshots

![Screenshot (144)](https://github.com/user-attachments/assets/3c983477-6203-4cf3-b771-acbcc0e9abac)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
heyy @ekta1810 the issue has been resolved , you can work on someother issue  and make sure to star our [Repo](https://github.com/mdazfar2/Ezyshop).
