### ISSUE TITLE
[Feat]Load More button is not working

### ISSUE THREAD

**Issue by KrHimanshu18** [mdazfar2/Ezyshop#506]
### Description

Load More button should render remaining row-section which is not working

### Screenshots

https://github.com/user-attachments/assets/dc34ae98-9907-44b0-ab8f-6ebd257b6679

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @KrHimanshu18, it should work, but I don't know why it's not. Please try to improve it and create a PR as soon as possible.

**Comment by KrHimanshu18** [comment]
@mdazfar2  Previously, the link between category.html and loadMore.js was removed, which caused functionality issues. It took considerable effort to identify the missing link since all functions were implemented correctly. Given the complexity of troubleshooting and resolving this issue, I believe this task justifies a Level 2 assignment

**Comment by mdazfar2** [comment]
Solved
