### ISSUE TITLE
alignment of text

### ISSUE THREAD

**Issue by Kajalmehta29** [mdazfar2/Ezyshop#507]
<img width="1215" alt="Screenshot 2024-10-12 at 5 42 24 PM" src="https://github.com/user-attachments/assets/122e2363-518a-45c9-91f4-0e243bf11df7">

Our facilities text should be centrally aligned. I want to fix this issue
Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by Kavita1928** [comment]
@Kajalmehta29 It's alignment is absolutely correct. The division is further divided into two division and the text is aligned with the text of 2nd division. I appriciate your effort but try to find some other issues.
