### ISSUE TITLE
want to add dark and light mode toggle 

### ISSUE THREAD

**Issue by sv410** [mdazfar2/Ezyshop#509]
### Description

Is your feature request related to a problem? Please describe. I'm always frustrated when browsing websites or applications without the option to switch between dark and light modes. The lack of this feature often leads to eye strain, especially in low-light environments, and reduces the overall user experience.

Describe the solution you'd like I propose implementing a dark and light mode toggle on our website. This feature would allow users to easily switch between dark and light themes based on their preference or environment. It enhances the user experience by providing a comfortable viewing option in different lighting conditions.

Describe alternatives you've considered

Manual CSS Switch: Manually change the CSS files for dark and light modes, but this approach is cumbersome and not user-friendly.

Browser Extensions: Relying on browser extensions for dark mode, but this isn't consistent across all users and browsers.

JavaScript Libraries: Use a third-party JavaScript library for theme switching, but this can be overkill for a simple feature.

Additional context Implementing a dark and light mode toggle using HTML and CSS will significantly improve the usability of our website

### Screenshots

![WhatsApp Image 2024-10-12 at 6 03 50 PM](https://github.com/user-attachments/assets/8fc63a37-417c-4d47-be85-f9c551ccab77)
![WhatsApp Image 2024-10-12 at 6 02 58 PM](https://github.com/user-attachments/assets/1d89fee5-5757-4401-8024-3699875a97e6)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @sv410, dark mode is a very good feature, but we have not decided to add the dark mode feature, we will let you know if it is needed in the future. Thank you for raising the issue.


- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by mdazfar2** [comment]
Hey @sv410, dark mode is a very good feature, but we have not decided to add the dark mode feature, we will let you know if it is needed in the future. Thank you for raising the issue.


- Srivani, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by sv410** [comment]
@mdazfar2 yeah sure, but can i add any background animation atleast to get me level up to level 1 or 2?

**Comment by mdazfar2** [comment]
Hey @sv410, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.

**Comment by mdazfar2** [comment]
@sv410, now the issue has been closed, so it doesn't matter if I add a label to your issues. The points will be added to the GSSoC-Ext leaderboard when your Pull Request is merged, not when issues are closed. Hope you understand.
