### ISSUE TITLE
[BUG] Update twitter icon to "X"

### ISSUE THREAD

**Issue by Vishwajeet594** [mdazfar2/Ezyshop#51]
### Description: 
**The Twitter icon on the website is outdated, incorrect, or inconsistent with the current branding of Twitter. We need to update the icon to the latest version to ensure brand alignment and a modern appearance across the site.**

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me
