### ISSUE TITLE
[Feat] Enhance Responsiveness of Shops Section on Home Page (Next JS)

### ISSUE THREAD

**Issue by kavya410004** [mdazfar2/Ezyshop#510]
### Description

The shops section on the home page is not responsive for smaller screen sizes, particularly on mobile devices. The card layout does not adjust appropriately, making it difficult for users to interact with the content. Additionally, the hover effect applied to the cards causes them to enlarge on hover, which is not user-friendly on mobile screens.

**Steps to Reproduce**
- Open the home page on a mobile device or resize the browser to a smaller width.
- Observe the layout of the shops section.
- Hover over the cards to see the enlarging effect.

**Expected Behavior**

- The shops section should display cards that are properly fitted to smaller screen sizes.
- The hover effect should be disabled on mobile devices to prevent awkward enlarging of cards.

### Screenshots

https://github.com/user-attachments/assets/8d135cde-1b50-47b8-9028-afd024bed2b1

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@kavya410004 It's been 2 days and you didn't reply anything now
