### ISSUE TITLE
[Feat]Add a FAQ Section to the Website

### ISSUE THREAD

**Issue by Vishwajeet594** [mdazfar2/Ezyshop#52]
### Summary:
**We would like to implement a Frequently Asked Questions (FAQ) section to improve user experience by providing clear answers to common questions.**

### Details:
Reason for Request:

**1. Users frequently ask similar questions, leading to repetitive support inquiries.
2. A FAQ section will help reduce the number of basic inquiries to customer support.
3. It will provide a self-service option for users, improving overall site usability and satisfaction.**
### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me

**Comment by mdazfar2** [comment]
@Vishwajeet594 Thank you for raising the issue.

As of now, we do not need it. We will let you know in the future if there is a need.

**Comment by mdazfar2** [comment]
Hey @lakshyeahh,

I noticed that you are replying to every issue for work. I appreciate your enthusiasm! Actually, I am looking for a developer to help convert the code to Next.js, so please let me know if you're interested. You can also ping me on [Discord](https://discordapp.com/users/877531143610708028) or [LinkedIn](https://linkedin.com/in/md-azfar-alam/). Thank you.

**Comment by lakshyeahh** [comment]
sure sir. just give me some time to familiarize with your environment. ill let u know soon. 

thank you.
