### ISSUE TITLE
[Feat]: Integration of MongoDB for User Signup and Login

### ISSUE THREAD

**Issue by shreyash3087** [mdazfar2/Ezyshop#522]
### Description

Currently the user signup page uses localstorage to store the user's name and password while signing up, and while logging in it matches the password with the data stored in localstorage which is not the best way to authenticate user as this method will fail if a user switches his browser since the localstorage's data will not be stored in all the browsers.

I propose the Integration of MongoDB for User authentication to make it more secure reliable and better 

### Screenshots

![screencapture-ezyshopz-vercel-app-RegisterPages-register-html-2024-10-12-23_38_41](https://github.com/user-attachments/assets/2f9f0833-78a0-42b3-8515-33e44071efd6)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by shreyash3087** [comment]
@mdazfar2 Kindly assign me this issue

**Comment by mdazfar2** [comment]
Hello @shreyash3087, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by shreyash3087** [comment]
Sure @mdazfar2

**Comment by mdazfar2** [comment]
Hello @shreyash3087, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- checkout the Benzamin folder 

- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
