### ISSUE TITLE
Fix Layout Alignment and Spacing Issues in "About Us" and "Get in Touch" Sections of Ezyshop Website

### ISSUE THREAD

**Issue by gurramkarthiknetha** [mdazfar2/Ezyshop#529]
Center the "About Us" Heading: In the current layout, the "About Us" heading is not centered properly within the section. This update ensures the heading is horizontally aligned at the center for a cleaner and more professional look.
![image](https://github.com/user-attachments/assets/d81bf5ed-21c0-42c6-bfff-6ef0865ca6ce)

Fix Overlap Between "Ezyshop" Logo and "Get in Touch" Section: The "Get in Touch" text is currently overlapping with the "Ezyshop" logo, which diminishes readability. This fix separates the two sections with appropriate padding or margin to prevent overlap.
![image](https://github.com/user-attachments/assets/62099267-142e-4739-98fd-1b521a6166e8)

Adjust Button Width in Newsletter Section: The "Submit Now" button in the newsletter form is too wide, impacting the visual balance of the page. This change reduces the button width to a more standard size, improving the form's aesthetics and user experience.
![image](https://github.com/user-attachments/assets/feeb9349-a773-43c3-acda-b3361c41ac54)
please assign the issue to me i will fix this

**Comment by mdazfar2** [comment]
@gurramkarthiknetha This is not our fault; this is exactly what we want. Please search for another issue, and I will be happy to assign it to you. Thank you.


- Gurram Karthik bro, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
