### ISSUE TITLE
[Feat] Review Carousel Speed Issue

### ISSUE THREAD

**Issue by abhivyakti2** [mdazfar2/Ezyshop#531]
### Description

The reviews move too quickly in the carousel, making it difficult to read and comprehend the feedback. The fast-paced movement disrupts the user experience.

I would like to contribute by adding an option to adjust the speed of the review carousel, or better yet, include manual controls that allow users to switch between reviews at their own pace.

An alternative could be adding a "pause" button, giving users time to read each review without rushing. Additionally, you could extend the time each review stays visible before switching.

@mdazfar2  Kindly assign me this issue and add labels : hacktoberfest-accepted, gssoc-ext, any level label suitable

### Screenshots

![image](https://github.com/user-attachments/assets/49e35db0-e911-4114-a364-787d6104b4b6)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@abhivyakti2 make sure send demo video while creating PR.

- Abhivyakti, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
