### ISSUE TITLE
[Feat] I want to add 'Add to Cart' and 'Saved Items' buttons on navbar, along with their respective pages.

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [mdazfar2/Ezyshop#533]
### Description

Here are some features that can be added:

- **Add to Cart Button**:
  - Allows users to add products to their cart.
  - Displays a confirmation message or notification upon adding.
  
- **Saved Items Button**:
  - Enables users to save products for future purchases.
   - Displays a confirmation message or notification upon saving.

- **Cart Page**:
  - Displays all the items added to the cart.
  - Includes features like quantity adjustment, removal, and total price calculation.

- **Saved Items Page**:
  - Lists all the products saved by the user for later.
  - Provides options to move items to the cart or remove them from the saved list.

@mdazfar2  @Kavita1928 
kindly assign me this issue, i will definitely make it a worthy contribution.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @NIKITABARANWAL890, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.
