### ISSUE TITLE
[Feat]dark and light toggle mode 

### ISSUE THREAD

**Issue by sv410** [mdazfar2/Ezyshop#534]
### Description

to add a  toggle of dark and light for customers view of seeing 

### Screenshots

![WhatsApp Image 2024-10-12 at 11 20 20 PM (1)](https://github.com/user-attachments/assets/ce94a113-a591-4993-9fb1-8ff4fc822403)
![WhatsApp Image 2024-10-12 at 11 19 35 PM (1)](https://github.com/user-attachments/assets/245a99f1-7fa0-4e90-9823-d591d0eda756)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
hey @sv410 thanku for raising this issue but for now we don't need night mode .You can find someother issue and make sure to 
star our [Repo](https://github.com/mdazfar2/Ezyshop).
