### ISSUE TITLE
[Doc]: Adding security.md file in the repo

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/Ezyshop#535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Adding security.md file in the repo

### Suggested Change

Adding security.md file in the repo

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by RamakrushnaBiswal** [comment]
@mdazfar2 assign this issue to me

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal you are assigned.
