### ISSUE TITLE
[BUG] Discord Icon Not Visible

### ISSUE THREAD

**Issue by ShobhitPatra** [mdazfar2/Ezyshop#537]
### Description

The Discord icon is not visible in the footer.

### Screenshots

![Untitled design](https://github.com/user-attachments/assets/28606bc0-b7cc-4cdc-9fee-722813eec1ac)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShobhitPatra Great issue found, you are going to be assigned.


- Shobhit, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by ShobhitPatra** [comment]
@mdazfar2 Thanks. Starred : -)
