### ISSUE TITLE
[Feat]I want to add 'Add to Cart' and 'Saved Items' buttons on navbar, along with their respective pages.

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [mdazfar2/Ezyshop#538]
### Description

Here are some features that can be added:

- **Add to Cart Button**:
  - Allows users to add products to their cart.
  - Displays a confirmation message or notification upon adding.
  
- **Saved Items Button**:
  - Enables users to save products for future purchases.
  - Displays a confirmation message or notification upon adding.

- **Cart Page**:
  - Displays all the items added to the cart.
  - Includes features like quantity adjustment, removal, and total price calculation.

- **Saved Items Page**:
  - Lists all the products saved by the user for later.
  - Provides options to move items to the cart or remove them from the saved list.

@mdazfar2 @Kavita1928 
Kindly assign me this issue, i'll surely make it a worthy contribution.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by NIKITABARANWAL890** [comment]
@mdazfar2
Since you merged my PR for the 'SHOP NOW' cards section, I aim to enhance this website by improving the functionality of the 'Add to Cart' and 'Save for Later' buttons, and by creating separate pages for items added to the cart and those saved for later.


:-)

**Comment by mdazfar2** [comment]
@NIKITABARANWAL890 you are assigned.

**Comment by NIKITABARANWAL890** [comment]
@mdazfar2 
Kindly review once, so that i can proceed further.

I've added the User, Cart, and Wishlist buttons for now. If everything goes well, I will proceed to their respective functional pages.

https://github.com/user-attachments/assets/4515ffc6-8e34-450c-902b-8d9f2e3cc5f5

**Comment by NIKITABARANWAL890** [comment]
@mdazfar2 @Kavita1928 
If I have raised an issue and it is assigned to me, but the same issue is also raised by others, whose PR will be accepted? If the issue is labeled as level 3, it may take 1-2 days to fix. Does this mean my PR will not be considered if the other raises their PR before mine?


I'm genuinely concerned about this, as it takes a lot of time to make the changes.

**Comment by mdazfar2** [comment]
solved
