### ISSUE TITLE
[BUG] : Enhancing Founder Section....

### ISSUE THREAD

**Issue by tech-dhawal-03** [mdazfar2/Ezyshop#54]
### Description

Needs proper alignment of element under founder section. Can have detailed descripion of the founder beside element with active social links which are now unactive..Overall, the page can be enhanced...

### Screenshots

<img width="1440" alt="Screenshot 2024-10-02 at 4 37 40 PM" src="https://github.com/user-attachments/assets/ad1e588e-a962-4afe-b742-d309240d203c">

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@tech-dhawal-03 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Don't forget to join our official [Discord server](https://discord.gg/SEzpxqQG).
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
- And please ⭐ our repo
