### ISSUE TITLE
[Doc]: Some products in the shops section lack images.

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [mdazfar2/Ezyshop#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Here are the key points for the description:

- **Missing Images**: Some products in the shops section do not have associated images.
- **Impact on Presentation**: This absence affects the visual appeal and user experience of the product listings.
- **Action Item**: Consider updating these products with appropriate images to enhance the overall shop experience.

![Screenshot 2024-10-13 114251](https://github.com/user-attachments/assets/4dc0b8f7-1487-4c50-9d5a-ee42e54b98a6)
![Screenshot 2024-10-13 114303](https://github.com/user-attachments/assets/349f5115-a18b-4297-978b-5c00fd1758b8)

@mdazfar2 @Kavita1928 
kindly assign me this issue under GSSOC'24 ext. with a label.

### Suggested Change

Add images to all the incomplete shop now pages.

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@NIKITABARANWAL890 go ahead and add image accordingly.

**Comment by NIKITABARANWAL890** [comment]
Sure

**Comment by NIKITABARANWAL890** [comment]
Hey @mdazfar2, ig you've merged the PR but didn't close it here?
