### ISSUE TITLE
[Feat] Update Contact page

### ISSUE THREAD

**Issue by SaumyaSubham** [mdazfar2/Ezyshop#547]
### Description

I want to redesign the contact page. As you see, there are some conflict between the text and the icons, Personally I suggest that It will be great if we keep only email, phone and opening hours because the website can be access from anywhere and See We're keeping Address in the footer so no need to keep address in the contact page.
Kindly assign me this issue under hacktoberfest 2024

### Screenshots

![Screenshot 2024-10-13 115522](https://github.com/user-attachments/assets/95186d45-7fd5-4ac4-bac3-c3d4487973cd)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@SaumyaSubham, how did you update the contact page? Did you change the UI or just the alignment? Please let me know.

- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by SaumyaSubham** [comment]
Hi @mdazfar2 
Nope I didn't updated that, I just add a issue of your website and You can see this issue in your website also.
So, I suggest that I can update your contact page and Kindly assign it to me under hacktoberfest 2024
