### ISSUE TITLE
[Feat] adding of shopping cart at the top section

### ISSUE THREAD

**Issue by swethapadmavathimukku** [mdazfar2/Ezyshop#548]
### Description

adding the shopping cart section at the top bar for easy access of items 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@swethapadmavathimukku As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by swethapadmavathimukku** [comment]
okay
