### ISSUE TITLE
[Feat] Redirect user into Home page after succesfully Logged in .

### ISSUE THREAD

**Issue by sahiljarngal** [mdazfar2/Ezyshop#552]
### Description

Right now, app shows just pop- up after login but not redirect to the Home page .
Please assign me this issue I will fix this issue.

### Screenshots

![image](https://github.com/user-attachments/assets/d1a92fac-9bcb-41e2-97c9-a70c1260e373)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@sahiljarngal As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
