### ISSUE TITLE
[Feat]Add a Chatbot Feature to Enhance User Interaction

### ISSUE THREAD

**Issue by amanver45** [mdazfar2/Ezyshop#553]
### Description

 I would like to propose the addition of a chatbot to the EZYSHOP platform to enhance user support and streamline the shopping experience. This chatbot can assist users in real-time by answering common queries, guiding them through the shopping process, and providing personalized recommendations.

Proposed Features:

User Queries: The chatbot can answer frequently asked questions related to pricing, delivery times, and product availability.
Personalized Recommendations: Based on user preferences and purchase history, the chatbot can suggest products or deals available in local stores.
Order Tracking: Users can inquire about their order status and receive updates directly through the chatbot.
Feedback Collection: The chatbot can prompt users for feedback after purchases to improve services.
Technical Considerations:

The chatbot can be implemented using a library like react-chat-widget for the front-end.
For the back-end, we can utilize an AI model (such as OpenAI's GPT) or a rule-based system to handle user interactions effectively.
Appwrite could be used to manage user sessions and store conversation history if necessary.
Benefits:

Improves user engagement and satisfaction by providing instant support.
Reduces the workload on customer service teams by handling routine queries.
Enhances the overall shopping experience on the platform.

### Screenshots

N/A

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @amanver45, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Aman, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by amanver45** [comment]
@mdazfar2 ok
