### ISSUE TITLE
[Feat]: Want to add contributor page 

### ISSUE THREAD

**Issue by sanikamandale17** [mdazfar2/Ezyshop#554]
### Description

"I would like the Contributor page to showcase individual profiles with specific sections for their contributions, bio, and social links. It could also include filters to categorize by role or type of contribution."
Plz assign this task to me @mdazfar2 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @sanikamandale17, this is a very good feature, but according to our website, it will not look good. Try to find any other bugs or features, which I am happy to assign to you. ***Thank you!***

 - Sanika, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
