### ISSUE TITLE
Add a Myorder , Cart option at navbar

### ISSUE THREAD

**Issue by pallaviii21** [mdazfar2/Ezyshop#557]
Want to add a Myorder and cart option 
![Screenshot 2024-10-13 155527](https://github.com/user-attachments/assets/408f88eb-d523-42c7-92e6-ae194b2031dc)

**Comment by mdazfar2** [comment]
@pallaviii21 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
