### ISSUE TITLE
[BUG] There is an alignment issue in the category footer section, while the other sections are correctly aligned.

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [mdazfar2/Ezyshop#559]
**Please have a look at the vertical whitespace at left hand side in 3rd Screenshot**  

**Other sections:**
![Screenshot 2024-10-13 153748](https://github.com/user-attachments/assets/9d24f940-1e2f-4f91-b277-a1f68d60e030)

![Screenshot 2024-10-13 153801](https://github.com/user-attachments/assets/46f5d0a6-35fc-43b2-8496-05cb6b3b6038)

**Whereas Category section is taking extra padding somehow**:

![Screenshot 2024-10-13 153814](https://github.com/user-attachments/assets/a5d92464-8529-4587-90c0-da79c7dd471b)

@mdazfar2 @Kavita1928 
Kindly assign me this issue under GSSOC'24 ext., i'll try to fix this ASAP.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@NIKITABARANWAL890 go ahead

**Comment by NIKITABARANWAL890** [comment]
hey @mdazfar2 i guess you merged the PR but forgot to close it here
