### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Divyansh2992** [mdazfar2/Ezyshop#56]
### Description

The height of footer is too large.

### Screenshots

![footer](https://github.com/user-attachments/assets/42a187a7-673a-4202-ae4d-020b60b45b92)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me

**Comment by mdazfar2** [comment]
@Divyansh2992 go ahead

**Comment by Divyansh2992** [comment]
I have updated the footer. Inform me if there is any fault.

**Comment by prisha-sh** [comment]
@mdazfar2 I'd like to work on it, I'll share my solution as soon as you assign it !!

**Comment by mdazfar2** [comment]
no response closing issue for now
