### ISSUE TITLE
[Feat]Learn about us should be on homepage 

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#563]
### Description

Learn about us should be on homepage and should be connected with the shops page

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
