### ISSUE TITLE
[Feat] Implement Search Bar 

### ISSUE THREAD

**Issue by Anwishta** [mdazfar2/Ezyshop#569]
### Description

I propose adding a Search Bar feature to enhance user experience by allowing users to search for specific content, products, or information on the platform. This feature will streamline the navigation process and make it easier for users to find what they are looking for efficiently.

### Screenshots

![image](https://github.com/user-attachments/assets/0709832b-1521-46f7-8825-2195b870f84f)
The search Bar will be implemented in this navbar.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
Heyy @Anwishta search bar will not fit properly in navbar  you can work on some other issue and make sure to star our [Repo](https://github.com/mdazfar2/Ezyshop).
