### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by Divyansh2992** [mdazfar2/Ezyshop#57]
### Description

improve the appearance of about us and footer section, also add the login signup form.

### Screenshots

https://github.com/user-attachments/assets/6c6909be-b48b-4892-a995-167944ba6f0f

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me

**Comment by mdazfar2** [comment]
@AbhinabPalei kindly reply here that's I can assign this issue to you.

**Comment by lakshyeahh** [comment]
This seems easy, i can also contribute if you want. Ill send the pr within few hours

**Comment by mdazfar2** [comment]
sorry @lakshyeahh PR #84 already raised by someone but he didn't comment here I think he is new in open source.
