### ISSUE TITLE
[Feat]adding chabot✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [mdazfar2/Ezyshop#573]
### Description

Add chat to the website, which will be fine tuned for this website and answer for user queries. Can I work on this issue?.
@mdazfar2 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by T-Rahul-prabhu-38** [comment]
@mdazfar2 can i work on this.

**Comment by T-Rahul-prabhu-38** [comment]
@mdazfar2 can i work on this.

**Comment by mdazfar2** [comment]
@T-Rahul-prabhu-38 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
