### ISSUE TITLE
create a dark mode buttton and make a dark mode

### ISSUE THREAD

**Issue by Arisha2902** [mdazfar2/Ezyshop#585]
### Description

i will make a "darkmode" option avilable for this website.The darkmode will be with hover ,box-shadow effect.

### Screenshots

[
![Screenshot (1)](https://github.com/user-attachments/assets/4e8a3e10-c580-44b7-9fb2-72b95895b297)
](url)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@Arisha2902 thankyou for raising this issue But for now this feature is not required will let u know if required in future and make sure to star our [Repo](https://github.com/mdazfar2/Ezyshop).
