### ISSUE TITLE
[Feat] add character validation to message and subject field in contact us form

### ISSUE THREAD

**Issue by ananyag309** [mdazfar2/Ezyshop#588]
### Description

Implement character length validation for the "Subject" and "Message" fields in the Contact Us form. The "Subject" field should allow a minimum of 5 characters and a maximum of 50 characters, while the "Message" field must have at least 10 characters. This will help ensure that users provide meaningful input and enhance the quality of submitted information.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@ananyag309 assigned and make sure to first star our [Repo](https://github.com/mdazfar2/Ezyshop).
