### ISSUE TITLE
[Doc]: Enhancing Each Section's Front for Maximum Appeal

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [mdazfar2/Ezyshop#589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I can add a customized blurred background for each section while maintaining the website's color theme to enhance its overall beauty.

**Before:**
![Screenshot 2024-10-13 151328](https://github.com/user-attachments/assets/500d9775-3823-4f7c-91c5-0edd6612984b)

**After:**
![Screenshot 2024-10-13 151258](https://github.com/user-attachments/assets/767a1076-e825-4a80-8697-4276e9c0faa8)

@mdazfar2 @Kavita1928 
Kindly assign me this issue under GSSOC'24 and with some level label to it i'll surely make it a worthy change.

### Suggested Change

This can be acheived by:

1.Custom Blurred Backgrounds
2.Gradient Overlays on it

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@NIKITABARANWAL890 go for it

**Comment by mdazfar2** [comment]
Hey @NIKITABARANWAL890, hope you are doing well. Please don't be discouraged, I will be closing all your issues. As you may know, we have successfully converted our code to Next.js and Tailwind CSS for easier backend integration. Thank you for your contributions; you are one of the best developers and contributors I've ever seen. You're most welcome to contribute in the future or share any tips regarding Ezyshops. Thank you so much, and feel free to message me on LinkedIn as well.
