### ISSUE TITLE
[BUG] adding favicon in the website

### ISSUE THREAD

**Issue by Ayush215mb** [mdazfar2/Ezyshop#59]
### Description

It looks unprofessional not to add a favicon in the website, i can add the logo to favicon, please assign this to me

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by shbhmexe** [comment]
hey assign me this issue ,, i want to solve this and have potential skils to solve this

**Comment by mdazfar2** [comment]
@Ayush215mb the favicon is show please look the below screenshot:

![{C90BBCEE-F7B4-4741-A4E8-63B7DC2532A8}](https://github.com/user-attachments/assets/f2c39ea9-f9e5-4c19-94ae-aba32c098512)
