### ISSUE TITLE
[Feat] Add Wishlist Feature to the EzyShop Website

### ISSUE THREAD

**Issue by 13Sharad** [mdazfar2/Ezyshop#590]
### Description

🔴 Tech stack:

HTML
CSS
JavaScript
(Optional: Backend technology for persistent storage, e.g., Node.js, MongoDB)

🔴 Objective:

Enhance the user experience by allowing users to create a wishlist of products they are interested in. This feature will help customers keep track of items they wish to purchase later, improving customer engagement and increasing the chances of conversion.

🔴 Summary:

The wishlist feature will enable users to save products for later viewing. Users can easily add items to their wishlist with a simple click and access them anytime. This feature can include functionalities such as sharing the wishlist with friends, receiving notifications when items go on sale, or reminders for items in the wishlist.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @13Sharad, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.


- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
