### ISSUE TITLE
[Feat] Add table and pagination to the my orders page over scrollable orders view

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#593]
### Description

In the current orders page, the user has to scroll down which will create bad UI when the orders will increase, a paginated table would be a better choice in this case.

### Screenshots

somthing like this, i will ensure it is consistent with the current ui
![image](https://github.com/user-attachments/assets/af89504e-4b71-4097-8b86-434903849e04)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@ShivanshPlays there is no orders page for now so the issue is not invalid

**Comment by ShivanshPlays** [comment]
There is in the nextjs version that we are working to roll out
