### ISSUE TITLE
[Feat] add scrollable order details page

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#594]
### Description

In this page, the orders should be scrollable and searchable for better ui

### Screenshots

![image](https://github.com/user-attachments/assets/0020411e-d27f-4c2f-92d7-23a9e0424375)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@ShivanshPlays you are assigned make sure to star our [Repo](https://github.com/mdazfar2/Ezyshop).
