### ISSUE TITLE
[Feat] add language translator 

### ISSUE THREAD

**Issue by ananyag309** [mdazfar2/Ezyshop#596]
### Description

To add a language translator to your website, you can use the Google Translate widget or similar APIs. This allows dynamic translation of content, enhancing accessibility for users speaking different languages.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@ananyag309 this issue has been already raised by someone please make sure not to raise duplicate issue 

Hope you star our Repo.
