### ISSUE TITLE
[Feat] Hover effect on each nav lists.

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [mdazfar2/Ezyshop#598]
### Description

https://github.com/user-attachments/assets/c720b57b-b2bf-4560-8596-4b77d4110a66

**i want to add the same hover feature on EZYSHOP's nav lists.** to make it look more functional

@Kavita1928 @mdazfar2 
kindly assign me this issue under GSSOC'24 ext.. I'll make it a worthy contribution.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@NIKITABARANWAL890 provide a preview of changes in this website

**Comment by NIKITABARANWAL890** [comment]
> @NIKITABARANWAL890 provide a preview of changes in this website

Ma'am ig you're asking for the changes after this effect in this website?

Before:
![Screenshot 2024-10-14 131859](https://github.com/user-attachments/assets/50edf642-3e58-4bba-a11f-cbb4586ee0b6)


After hover:
![Screenshot 2024-10-14 131852](https://github.com/user-attachments/assets/ffd4be0d-d726-4def-b87d-8064ce97dd47)


**Feature Explanation**
**Hover Effect:** This is a UI interaction where visual feedback is provided when a user moves the cursor over an interactive element (like a link).
**Pop-up Insights:** The pop-up typically contains information such as:
Subcategories related to the main category (e.g., different types of jewelry under "WOMEN").
Special promotions or featured products.
Additional links to related pages for easier navigation.

**Comment by NIKITABARANWAL890** [comment]
> > @NIKITABARANWAL890 provide a preview of changes in this website
> 
> Ma'am ig you're asking for the changes after this effect in this website? (Actually this is my self designed website) Before: ![Screenshot 2024-10-14 132609](https://private-user-images.githubusercontent.com/130988803/376149935-8f6f4dae-6ac6-40b8-8240-49191d46ed6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTM0OTMsIm5iZiI6MTcyODg5MzE5MywicGF0aCI6Ii8xMzA5ODg4MDMvMzc2MTQ5OTM1LThmNmY0ZGFlLTZhYzYtNDBiOC04MjQwLTQ5MTkxZDQ2ZWQ2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwODA2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmI3OTkwZWY0MmY1YTUxMzQ4NGM5YjkzZDY2YmU0ODVhZGU3YTM3NmRlNDZhNTBkMTkxY2MwZWVjMTZlMDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zxpkgHfsxQ26zRSEgBawrfoGFCsVG3FLL-tfG_S3A4Y)
> 
> After hover: ![Screenshot 2024-10-14 132627](https://private-user-images.githubusercontent.com/130988803/376150046-10e16ae9-7694-4e78-89f5-babc0d470b97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTM0OTMsIm5iZiI6MTcyODg5MzE5MywicGF0aCI6Ii8xMzA5ODg4MDMvMzc2MTUwMDQ2LTEwZTE2YWU5LTc2OTQtNGU3OC04OWY1LWJhYmMwZDQ3MGI5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwODA2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDVmMzI4YzgwODJmNzQwNzQyMzdmNGJlN2FlOTUxMjQ1YmE5OWQ1Zjc0YWNlOGRlZjIxZDU3MjEwODRhZjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SNUMCvshdgs76Rp4I0K8eRm5Fl-2UeqtBYIbIL91cao)
> 
> **Feature Explanation** **Hover Effect:** This is a UI interaction where visual feedback is provided when a user moves the cursor over an interactive element (like a link). **Pop-up Insights:** The pop-up typically contains information such as: Subcategories related to the main category (e.g., different types of jewelry under "WOMEN"). Special promotions or featured products. Additional links to related pages for easier navigation.


![Screenshot 2024-10-14 133722](https://github.com/user-attachments/assets/1a681e44-17d5-4b31-8964-364b2d6b38a5)
**the drop down appearance will be improved by adding this pop-up also.**

**Comment by NIKITABARANWAL890** [comment]
> > > @NIKITABARANWAL890 provide a preview of changes in this website
> > 
> > 
> > Ma'am ig you're asking for the changes after this effect in this website? (Actually this is my self designed website) Before: ![Screenshot 2024-10-14 132609](https://private-user-images.githubusercontent.com/130988803/376149935-8f6f4dae-6ac6-40b8-8240-49191d46ed6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTM0OTMsIm5iZiI6MTcyODg5MzE5MywicGF0aCI6Ii8xMzA5ODg4MDMvMzc2MTQ5OTM1LThmNmY0ZGFlLTZhYzYtNDBiOC04MjQwLTQ5MTkxZDQ2ZWQ2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwODA2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmI3OTkwZWY0MmY1YTUxMzQ4NGM5YjkzZDY2YmU0ODVhZGU3YTM3NmRlNDZhNTBkMTkxY2MwZWVjMTZlMDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zxpkgHfsxQ26zRSEgBawrfoGFCsVG3FLL-tfG_S3A4Y)
> > After hover: ![Screenshot 2024-10-14 132627](https://private-user-images.githubusercontent.com/130988803/376150046-10e16ae9-7694-4e78-89f5-babc0d470b97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTM0OTMsIm5iZiI6MTcyODg5MzE5MywicGF0aCI6Ii8xMzA5ODg4MDMvMzc2MTUwMDQ2LTEwZTE2YWU5LTc2OTQtNGU3OC04OWY1LWJhYmMwZDQ3MGI5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwODA2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDVmMzI4YzgwODJmNzQwNzQyMzdmNGJlN2FlOTUxMjQ1YmE5OWQ1Zjc0YWNlOGRlZjIxZDU3MjEwODRhZjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SNUMCvshdgs76Rp4I0K8eRm5Fl-2UeqtBYIbIL91cao)



> > **Feature Explanation** **Hover Effect:** This is a UI interaction where visual feedback is provided when a user moves the cursor over an interactive element (like a link). **Pop-up Insights:** The pop-up typically contains information such as: Subcategories related to the main category (e.g., different types of jewelry under "WOMEN"). Special promotions or featured products. Additional links to related pages for easier navigation.



> 
> ![Screenshot 2024-10-14 133722](https://private-user-images.githubusercontent.com/130988803/376154265-1a681e44-17d5-4b31-8964-364b2d6b38a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTM2MTUsIm5iZiI6MTcyODg5MzMxNSwicGF0aCI6Ii8xMzA5ODg4MDMvMzc2MTU0MjY1LTFhNjgxZTQ0LTE3ZDUtNGIzMS04OTY0LTM2NGIyZDZiMzhhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwODA4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDVjYWE5MmQ3ZDk1NmVhYTJlOTA2NzM3ZmFlNGU1MGQ4NjcwYTliNTc0ODhlMTQ4YTQwNWRhNjM2YThjNDA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RrVcQj8hUPxcbV7XfZES6XoV4v_8u7ktPMFTrkFfCN4) **the drop down appearance will be improved by adding this pop-up also.**
