### ISSUE TITLE
[Feat]Missing Sign-Up and Login Pages on Website.

### ISSUE THREAD

**Issue by grasyPatel** [mdazfar2/Ezyshop#6]
### Issue Description:
The website currently does not display sign-up and login pages. These pages are crucial for user registration and authentication.

### Proposed Solution:
I would like to design responsive, user-friendly sign-up and login pages that align with the existing design of the website. 

Please assign me to this issue so I can start working on it.

### Screenshots

<img width="595" alt="Screenshot 2024-10-01 at 8 15 38 PM" src="https://github.com/user-attachments/assets/402c97da-67e5-4f94-94fc-4eb4b2124320">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Charul00** [comment]
can i work on this

**Comment by mdazfar2** [comment]
@grasyPatel Thank you for raising the issue. You are assigned.

- It would be great if you could also try to implement the functionality of the login/signup page.

**Comment by grasyPatel** [comment]
Thank you for assigning me to this issue! I appreciate the opportunity, and I will get started on implementing the functionality for the login and signup pages. If you have any specific requirements or preferences, please let me know.

Looking forward to contributing!

**Comment by rohitsharma2610** [comment]
hey, i created may login/sign-up pages and i have experience so can you assign me?

**Comment by mdazfar2** [comment]
> hey, i created may login/sign-up pages and i have experience so can you assign me?

Hey @grasyPatel, I appreciate your enthusiasm, but this issue is already assigned to @grasyPatel.
