### ISSUE TITLE
[BUG] clicking on the logo in navbar doesn't go to the homepage

### ISSUE THREAD

**Issue by Ayush215mb** [mdazfar2/Ezyshop#60]
### Description

On clicking the logo in the navbar, the website should go to "/' link but this is isn't working, so please assign this to me and i will solve the issue and create a PR in 2-3 hours.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Ayush215mb you are assigned.

**Comment by rutikakengal** [comment]
I like to add header and footer to the webpage and also work on header items . Assign me i like to work on it @mdazfar2

**Comment by mdazfar2** [comment]
Hey @rutikakengal, it is already assigned to someone. Can you please check another issue if available, or I'll ping you if we need your help? Thank you.

**Comment by Ayush215mb** [comment]
@rutikakengal i have created a PR with the changes(added logo as favicon and added index.html in all the empty href tags). Please review it.
