### ISSUE TITLE
[Feat] ADD TRANSLATOR FEATURE 

### ISSUE THREAD

**Issue by HS202022** [mdazfar2/Ezyshop#600]
### Description

ADD A TRANSLATOR IN THE WEBSITE TO MAKE THE USER EXPERIENCE GOOD IT WILL BE HELPFUL FOR THE PEOPLE WHO ARE MORE COMFORTABLE TO THEIR NATIVE LANGUAGES 
![Screenshot 2024-10-14 110922](https://github.com/user-attachments/assets/a5076a0f-b8e8-4d12-99f5-3f37bd6f2286)
I can work on this 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@HS202022 You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)


- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
