### ISSUE TITLE
want to add hovering effects in login page

### ISSUE THREAD

**Issue by Ronnit44** [mdazfar2/Ezyshop#605]
### Description

I would like to add hover effect to the login button and also underline hover effects to the forgot password and sign up link

### Screenshots

![image](https://github.com/user-attachments/assets/0b61b6d8-d011-46b3-8b7c-4ffb9e7b8bb9)
Kindly assign me this issue.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Ronnit44, as we are not decided to add any hover effect to our website, we will let you know if there's any work related to it. You can search for other issues/bugs and raise an issue accordingly. Thank you for raising the issue.


- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
