### ISSUE TITLE
[Feat] Twitter handle

### ISSUE THREAD

**Issue by Mayanksaininh** [mdazfar2/Ezyshop#610]
### Description

I want to add twitter handle at place where discord, GitHub, linked in or Instagram.  

### Screenshots

![Screenshot (28)](https://github.com/user-attachments/assets/a434bf96-58d7-45f0-aba5-b94c4a4389f9)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Mayanksaininh, we don't have a Twitter account, so I think there is no need to add the icon. Thank you for raising the issue.



- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
