### ISSUE TITLE
Implement Read More Feature with Authentication Redirect

### ISSUE THREAD

**Issue by ananyag309** [mdazfar2/Ezyshop#611]
### Description

implement a feature that redirects users to the signup/login page when they click on the "Read More" button on a blog post. Only logged-in users should be able to access the full content. If the user is already logged in, they will be directed to the full article seamlessly. This feature ensures that the blog content is restricted to authenticated users, enhancing user engagement and security

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @ananyag309, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Ananya, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by ananyag309** [comment]
@mdazfar2 yes sure
