### ISSUE TITLE
add functionality to start shopping button

### ISSUE THREAD

**Issue by bhavanireddy57** [mdazfar2/Ezyshop#613]
### Description

I would like to add a functionality to  start shopping button so that it enhances website.so please assign me this task

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by bhavanireddy57** [comment]
https://github.com/user-attachments/assets/f190e585-cf1e-450a-8bdb-230d9e19ff43

It's just work as shown above so can u assign me this

**Comment by mdazfar2** [comment]
Hello @bhavanireddy57, this is a very good feature, but we are converting the entire code into the Next.js framework for easier backend integration. Once the Next.js conversion is complete, I will let you know so you can work on that issue.

- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
