### ISSUE TITLE
[Feat]: Adding copyright in Footer

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/Ezyshop#614]
### Description

Adding copyright in Footer

### Screenshots

![image](https://github.com/user-attachments/assets/c61c7fc8-12ef-473f-ad43-2384367deac8)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal go ahead
