### ISSUE TITLE
Ui enhancement : Scroll reveal 

### ISSUE THREAD

**Issue by aditya07389** [mdazfar2/Ezyshop#616]
hey @mdazfar2  I would like to add scroll reveal effect to your (every tab if it looks good to you)

ex for scroll reveal effect : https://www.nmit.ac.in/ checkout this for ex

Kindly assign the labels gssoc extd , hacktoberfest and level 2 
Thankyou

**Comment by mdazfar2** [comment]
@aditya07389 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.


- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
