### ISSUE TITLE
[Feat]: The website lack dark mode feature.

### ISSUE THREAD

**Issue by ChampGupta** [mdazfar2/Ezyshop#617]
### Description

The dark mode feature look cool and enhance the look of website. Please assign me this under gssoc-ext and hactoberfest-accepted.
Regards

### Screenshots

<img width="1470" alt="Screenshot 2024-10-14 at 6 18 05 PM" src="https://github.com/user-attachments/assets/def95e16-2c00-407b-b4a6-7dd546e5baee">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @ChampGupta, dark mode is a very good feature, but we have not decided to add the dark mode feature, we will let you know if it is needed in the future. Thank you for raising the issue.


- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by ChampGupta** [comment]
I have starred it.
