### ISSUE TITLE
[BUG]  UI Alignment Issue in Customer Review Section

### ISSUE THREAD

**Issue by Chayandev** [mdazfar2/Ezyshop#619]
### Description

The profile image, customer name, and bio text in the customer review section are not properly aligned, leading to an inconsistent visual appearance. As seen in the attached image, the elements (profile image, name, and bio) should be vertically centered and aligned, but currently, they appear slightly off, affecting the overall aesthetics.

### Screenshots

![image](https://github.com/user-attachments/assets/ebff6802-593a-4d1b-9e13-f405cb7d217e)

### Any additional information?

**Expected Behavior:** All elements (profile image, name, bio) should be aligned correctly, with the profile image centered relative to the name and bio text.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Chayandev now, correct the grammatical error in the following below sentence and give me the correct ones, provide only the correct sentence without any arguments:

**Comment by Chayandev** [comment]
What do you want to mean , first clearly mention it !
