### ISSUE TITLE
[BUG] Poorly aligned 'About us' facilities section

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [mdazfar2/Ezyshop#622]
### Description

**IN ABOUT SECTION**
![Screenshot 2024-10-14 002153](https://github.com/user-attachments/assets/569de0cb-f24e-437e-a4a3-5f73a646e814)

**IN HOME PAGE**
![Screenshot 2024-10-14 002205](https://github.com/user-attachments/assets/6594145c-ea4e-431c-af3a-0b76b8c11b68)

Same section but differently designed, no uniformity.

kIndly assign me this issue under GSSOC'24 ext. I'll happy to fix this bug.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
go ahead @NIKITABARANWAL890
