### ISSUE TITLE
[BUG] Alignment issue in Blog Detail Page

### ISSUE THREAD

**Issue by gnjayasekara** [mdazfar2/Ezyshop#626]
### Description

Slight alignment issue in the comment section of the blog detail page.
Need to align the bottom comment with the top two.

### Screenshots

![Screenshot 2024-10-14 210400](https://github.com/user-attachments/assets/e3974a6e-2912-4df7-a974-3fe425210aec)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by gnjayasekara** [comment]
@mdazfar2 I would like to start working on this issue, could you assign this to me?

**Comment by mdazfar2** [comment]
hey @gnjayasekara As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.


- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
