### ISSUE TITLE
Add social media icons in footer 

### ISSUE THREAD

**Issue by rutikakengal** [mdazfar2/Ezyshop#63]
this will allow users to connect fastly

**Comment by mdazfar2** [comment]
@rutikakengal It is already available in footer.

- Don't forget to join our official [Discord server](https://discord.gg/SEzpxqQG).
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
- And please ⭐ our repo

**Comment by shbhmexe** [comment]
Can you assign this work to me? And I will always contribute to any issue, cause it makes me think and grow further
