### ISSUE TITLE
[BUG] missing our shops

### ISSUE THREAD

**Issue by Prudhvi-232** [mdazfar2/Ezyshop#632]
### Description

In footer there is a missing of out shops link 
i would like to add the our shops like above the our blog and below the out teams

### Screenshots

https://github.com/user-attachments/assets/2953c0db-2a58-4a72-be70-5676e93beb41

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Prudhvi-232 There is no need to add to our shops.
