### ISSUE TITLE
[Feat] Scroll bar of your website is not suited and it is default.

### ISSUE THREAD

**Issue by VinayLodhi1712** [mdazfar2/Ezyshop#637]
### Description

Scroll bar of your website is not looking good and not suited so i can change it to dynamically scrollbar.

### Screenshots

![SCROLLbutton](https://github.com/user-attachments/assets/fe08952b-2394-40bf-a9d2-c7a77e4d87db)

https://github.com/user-attachments/assets/bfcfc801-df40-4a13-8bbb-4d6f3e9231cd

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @VinayLodhi1712 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Vinay bro, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
