### ISSUE TITLE
[Doc]: Sign up offer page goes OFF THEME

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [mdazfar2/Ezyshop#663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The sign-up page that pops up when opening the website does not match EZYSHOP's color theme, which seems inconsistent with the overall branding, and needs improvement to create a cohesive and visually appealing user experience.

![Screenshot 2024-10-15 184256](https://github.com/user-attachments/assets/af6a14f8-ceb6-4a40-a4d9-8f42c5a012b6)

**This page is in blue theme whereas the EZYSHOP'S theme is completely different**

@mdazfar2 @Kavita1928 
kindly assign me this issue under GSSOC'24 ext. I will surely make it a worthy contribution.

### Suggested Change

Color Palette Consistency: Update the sign-up page's background, button, and text colors to match the primary and accent colors used across the EZYSHOP website. This ensures visual harmony and reinforces brand identity throughout the user experience.

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by NIKITABARANWAL890** [comment]
@Kavita1928 @mdazfar2 kindly assign me this

**Comment by mdazfar2** [comment]
@NIKITABARANWAL890 I have been observing for some time that you raise issues repeatedly, and you raise 4 to 5 issues at once, which is not a good practice. We are human, and we need to handle many contributors. If you raise too many issues at once, it becomes irritating to assign issues to the same person repeatedly.

See the screenshot below of my phone's notification to see how it looks. I request you not to do that.

![Screenshot_2024_1015_235953.jpg](https://github.com/user-attachments/assets/ac465f8e-eb9d-4788-83a9-d31d363cf150)

 
_Thank you!_

**Comment by NIKITABARANWAL890** [comment]
> I have been observing for some time that you raise issues repeatedly, and you raise 4 to 5 issues at once, which is not a good practice. We are human, and we need to handle many contributors. If you raise too many issues at once, it becomes irritating to assign issues to the same person repeatedly.
> 
> See the screenshot below of my phone's notification to see how it looks. I request you not to do that.



Hey, I'm really sorry for raising so many issues at once. Someone advised me that maintaining a streak is important, and if the maintaner doesn't reply, I should tag them again. 
I realize now that it may have caused some inconvenience, and I didn't intend to overwhelm anyone. I'll definitely be more mindful going forward and make sure to keep things more balanced. 

Thanks for bringing it to my attention!
