### ISSUE TITLE
Proposal: Improve UI and Landing Page with Transition Effects and Cursor Pointer Fixes.

### ISSUE THREAD

**Issue by NitishKumar525** [mdazfar2/Ezyshop#665]
### Description

Description:
While exploring your project, I noticed that the landing page and various UI components could benefit from some subtle transition effects to enhance the overall user experience. Additionally, I observed that the cursor pointer is missing on some interactive elements, which may affect user interaction.

Suggested Changes:
1. **Add Transition Effects**:
   - Implement smooth transitions on hover for buttons, links, and other interactive elements to create a more dynamic and engaging experience for users.
   - Ensure that the transitions are subtle and align with the current design aesthetics, making the UI feel more polished.

2. **Fix Missing Cursor Pointer**:
   - Add the `cursor: pointer` style to interactive components where it's missing, ensuring that users get proper visual feedback when hovering over clickable elements.

Benefits:
- **Improves User Experience**: Transitions make interactions feel smoother and more intuitive, while the cursor pointer provides immediate feedback, enhancing usability.
- **Increases Engagement**: A more dynamic UI can encourage users to interact more with the elements on the page.
- **Refines the Design**: These small changes will elevate the overall look and feel of the project, giving it a more professional touch.

### Screenshots

![Screenshot 2024-10-15 184914](https://github.com/user-attachments/assets/d64eb614-e931-4427-83dd-d750887ea3fd)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Wow @Nitishkumar525, great issue found! You are going to be assigned.

- Hope you have read our [contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md).  
- If you need any guidance, you can mention any of the maintainers by using "@".
