### ISSUE TITLE
[BUG] Navbar Button not aligned properly.

### ISSUE THREAD

**Issue by AkshatGupta2005** [mdazfar2/Ezyshop#671]
### Description

Navbar Button not properly aligned to the window and doesn't have a left margin. Also when shifted to small screen size ( 320px ) the navbar button creates problems in home page.

### Screenshots

![image](https://github.com/user-attachments/assets/fed58244-8d23-4eb1-99e1-14f79fd2a041)
![Screenshot_2024-10-15-21-19-49-45_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/40c7e2f6-9a00-4cce-aeac-504ed5b6cc6c)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by SarangAhlawat** [comment]
I want to work on this issue and can make this responsive properly, please assign it to me under GSSoC'24 - Extd!
Also add gssoc-ext and level label.
