### ISSUE TITLE
Revamping the Navbar: Contributing to an Open-Source Project for a Sleek and Modern Design 

### ISSUE THREAD

**Issue by khurshed07** [mdazfar2/Ezyshop#681]
****************************************************************************************************************Before Changes*****
![Screenshot 2024-10-15 233123](https://github.com/user-attachments/assets/7530c0f5-80c4-43bf-ade2-38493188fe35)

****************************************************************************************************************After Changes*******
![Screenshot 2024-10-15 232228](https://github.com/user-attachments/assets/de60a054-f4f1-4574-8520-04d3982fcb2f)
![Screenshot 2024-10-15 232553](https://github.com/user-attachments/assets/097cbf9f-aa0e-4c36-8a3a-7b0fcf11e2f9)
![Screenshot 2024-10-15 232601](https://github.com/user-attachments/assets/04ba7d48-a149-4941-9051-2f586c4b672a)
![Screenshot 2024-10-15 232609](https://github.com/user-attachments/assets/ffa9b718-5477-47f6-aac7-98bde0508978)
![Screenshot 2024-10-15 232614](https://github.com/user-attachments/assets/c7bd6203-3c1f-4d39-9cd5-d37d77971d37)
![Screenshot 2024-10-15 232621](https://github.com/user-attachments/assets/b3a754b9-cfd0-4685-929e-dada58e1a28b)

Hi @mdazfar2

I recently updated the navbar for your project to make it more attractive and user-friendly. I've attached screenshots of the changes, and I'd love to contribute to this enhancement to improve the overall design.

Please assign me to this task. It would be a great opportunity to contribute while enhancing my skills.

I am looking forward to your response!

Best regards,
@khurshed07
https://github.com/khurshed07

**Comment by mdazfar2** [comment]
Hello @khurshed07, this is a very good feature, but according to our website, it will not look good. Try to find any other bugs or features, which I am happy to assign to you. ***Thank you!***

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
