### ISSUE TITLE
[Feat] Styling scrollbar as per the webpage

### ISSUE THREAD

**Issue by richa-k23** [mdazfar2/Ezyshop#683]
### Description

Right now, the web page's scrollbar is a default one which doesn't matches with the overall theme of it.
I would like to style the scrollbar so that it provides a great UI, and also is visually appealing.

**The changes I will make:**

- changing color of scollbar
- adding rounded edges
- adding hover effect 

### Screenshots

(The below snapshot is just an example. It is not the exact changes I will make in respect to color and hovering effects.)

https://github.com/user-attachments/assets/6b0a0ce4-45af-4ea2-8c51-d594c4e1f548

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hello @richa-k23, this is a very good feature, but according to our website, it will not look good. Try to find any other bugs or features, which I am happy to assign to you. ***Thank you!***

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
