### ISSUE TITLE
[Feat] Adding signup of users 

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#691]
### Description

This feature introduces a Signup functionality that allows users to create accounts by providing their email, name, password, and mobile number. The user data will be securely stored in the database, with the password hashed for safety. Upon successful signup, users can log in via NextAuth using their credentials. This will enhance user onboarding and session management.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by SarangAhlawat** [comment]
I want to work on this issue, please assign it to me under GSSoC'24 - Extd!
Also add gssoc-ext and level label.
