### ISSUE TITLE
[Feat]: Add Dark Theme Support

### ISSUE THREAD

**Issue by AnushkaChouhan25** [mdazfar2/Ezyshop#694]
### Description

The website currently lacks dark theme support, which could improve the user experience by reducing eye strain, especially in low-light environments. Adding a dark theme would also align with modern UI practices and provide users the option to switch between light and dark modes.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Harshrj1502** [comment]
I want to work on this issue
