### ISSUE TITLE
[BUG] missing links in the quick links section at footer

### ISSUE THREAD

**Issue by sruthi070** [mdazfar2/Ezyshop#7]
### Description

links to the respective pages were missing in quick links section at footer

### Screenshots

![image](https://github.com/user-attachments/assets/d10d6351-825b-47aa-9069-7ce2b55579de)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by yesahem** [comment]
I am also willing to work on this can I ?
And if i create a PR of this issue will it be merged on <strong>FirstComeFirstServe</strong> basis or on assigning basis?

**Comment by mdazfar2** [comment]
@sruthi070 go ahead.

**Comment by mdazfar2** [comment]
closed as complete
