### ISSUE TITLE
[BUG] Load more button is not working in 'Category' page.

### ISSUE THREAD

**Issue by Suvadip-sana** [mdazfar2/Ezyshop#728]
### Description

In Category page the 'load more' button is not working.
Though it was developed by me initially.  #64 PR
Where you merge this without add any label😓😓

Now this button did not work. I want to fix this. Please assign me this ISSUE.
@mdazfar2 

### Screenshots

![image](https://github.com/user-attachments/assets/db86d3b0-47a0-4a94-9fe9-7824186929a6)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Suvadip-sana, thanks for letting me know. Actually, I forgot to add a label to your pull request, but I have now added a label according to your pull request. Please check it out.

**Comment by Suvadip-sana** [comment]
@mdazfar2   You miss labels for points.

It's `label-3`  as per issue #28 

Please check i out and add this

**Comment by Suvadip-sana** [comment]
#64 here is PR   @mdazfar2

**Comment by mdazfar2** [comment]
Added @Suvadip-sana

**Comment by Suvadip-sana** [comment]
@mdazfar2    Thank you so much.  I hop this point is count on leader board.

**Comment by Suvadip-sana** [comment]
@mdazfar2 

Could you  assign me this issue for now?
It's not working for some reason for now.
