### ISSUE TITLE
[Feat] Missing 'Rate Us' functionality

### ISSUE THREAD

**Issue by Suvadip-sana** [mdazfar2/Ezyshop#729]
### Description

As a retailing platform there should be a 'Rate us' feature. It help to improve developer or company to improve their platform as well as services.   It's basically a 1 to 5 star based rating model along with comments.

For now it's only Frontend. That print a alert message after submitting the review form.
I attached A button "Rate Us" In footer. after clicking on it raise a pop up middle of the screen(background is scrollable)

Just like the attached video ->

### Screenshots

https://github.com/user-attachments/assets/022e326d-2cc1-41c1-afaa-2ca4971722fc

@mdazfar2   Please assign me this issue. I want to implement this new feature.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Suvadip-sana As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

**Comment by Suvadip-sana** [comment]
@mdazfar2 

Ok thank you.
