### ISSUE TITLE
[BUG] Nav bar is not sticky/fixed

### ISSUE THREAD

**Issue by Suvadip-sana** [mdazfar2/Ezyshop#730]
### Description

As of now the Navbar is not sticky, neither fixed.

For a website stickiness of navabr is a beet practice & UX also.

Please assign me this issue. @mdazfar2  Want to fix this.

### Screenshots

![image](https://github.com/user-attachments/assets/8cfc3beb-e4eb-4078-a5e7-4926d6a134b5)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Suvadip-sana Issue acknowledged! You are going to be assigned.

Hope you know that our website is fully converted to the Next.js and Tailwind CSS framework, so you have to work accordingly.

- Read our [Contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md] and make sure to contribute accordingly.


_Thank you_

**Comment by Suvadip-sana** [comment]
@mdazfar2   Ok i will try.

**Comment by Suvadip-sana** [comment]
I see that your code base is changed based on Next.js.
But my question is- is this reflect that you host in this link https://ezyshopz.vercel.app/   currently?

@mdazfar2  Clarify this?

**Comment by mdazfar2** [comment]
> I see that your code base is changed based on Next.js.
> But my question is- is this reflect that you host in this link https://ezyshopz.vercel.app/   currently?
> 
> @mdazfar2  Clarify this?



Yes.

**Comment by Suvadip-sana** [comment]
@mdazfar2  Why it's closed?  Please let me know the reason?

**Comment by lavanyabandari** [comment]
can you assign it to me please ..I will do it ...

**Comment by mdazfar2** [comment]
Sorry @lavanyabandari, please don't be discouraged, but this issue is already assigned to someone. Only one person can work on a single issue at a time. You can raise another issue, and I will be happy to assign it to you, but make sure that the issue you raise is valid and really needs to be addressed on our website; otherwise, invalid issues will be closed. ***Thank you!***
