### ISSUE TITLE
ADD: Customer Reviews: 

### ISSUE THREAD

**Issue by shubhagarwal1** [mdazfar2/Ezyshop#732]
A page where users can leave reviews and ratings for products and stores, helping others make informed decisions.

**Comment by mdazfar2** [comment]
@shubhagarwal1 customer reviews is not suitable for now. It would be great if the website is fully functional, then we can add this feature. Thank you.

**Comment by shubhagarwal1** [comment]
hey @mdazfar2 i understand the thing, as both of issues i raise are closed can you ell me anyhting specific to work on

**Comment by mdazfar2** [comment]
@shubhagarwal1 you should have to read [README.md](https://github.com/mdazfar2/Ezyshop/blob/main/README.md) for better understand that what should we have to do.

**Comment by shubhagarwal1** [comment]
@mdazfar2 most of the features are already implmented, i have checked out the website also there are not potential bugs to solve 
so can you guide me through spefic issue you are looking 
to work n

**Comment by mdazfar2** [comment]
What do you say, @shubhagarwal1? Is it really completed?

Is there any prompt option when users click on login/signup where two prompts will show: one for "Store Manager" and the second for "Shopper" (like us who buy products), and the "Store Manager" can add their respective store with the name and products with prices? Is this implemented?

Also, has the Razorpay integration for safe and secure payments been implemented? Shubha, tell me why you guys mention it without fully checking.

Tell me, @shubhagarwal1, is it really all implemented?

**Comment by shubhagarwal1** [comment]
> What do you say, @shubhagarwal1? Is it really completed?
> 
> Is there any prompt option when users click on login/signup where two prompts will show: one for "Store Manager" and the second for "Shopper" (like us who buy products), and the "Store Manager" can add their respective store with the name and products with prices? Is this implemented?
> 
> Also, has the Razorpay integration for safe and secure payments been implemented? Shubha, tell me why you guys mention it without fully checking.
> 
> Tell me, @shubhagarwal1, is it really all implemented?

@mdazfar2 I am really sorry if that means or reflects wrong, i searched for the issues on the website, 
as the feature you are saying is a new thing to be implemented, so that is the reason i did not mention that, 
else accordence to UI many things are completed and looks standard, although if anything from my side portrays wrong i appologise for the specific.
