### ISSUE TITLE
[Feat] Adding animation to trending deals

### ISSUE THREAD

**Issue by govindumeesala** [mdazfar2/Ezyshop#74]
### Description

No animations are there for trending deals 
woukd like animations to the trending deals 

### Screenshots

![image](https://github.com/user-attachments/assets/da637d40-0ff1-4357-8e5b-eeb6d8ba2353)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @govindumeesala,

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

-  And please ⭐ our repo
