### ISSUE TITLE
Add Testimonials section 

### ISSUE THREAD

**Issue by AnushkaChouhan25** [mdazfar2/Ezyshop#746]
### Description

Issue Title: Add Testimonials Section

Description:
The website currently lacks a dedicated Testimonials section to showcase user feedback and experiences. Adding this section will enhance credibility and trust among users by displaying positive reviews and testimonials. 
The section should feature multiple testimonials with profile images, names, and short feedback, cycling automatically every few seconds. Additionally, side arrows should be included to allow users to navigate manually between testimonials.

### Screenshots

![kissmetrics-quote-testimonials](https://github.com/user-attachments/assets/5a066bc0-9be5-4150-9215-765876b88764)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@AnushkaChouhan25, as our website is not functioning correctly, there is no need to add testimonials at this time, and I don't want to include fake testimonials. Hope you understand. We will let you know if this needs to be added in the future.
