### ISSUE TITLE
[Feat] UI enhancement of contact us page and adding redirect link to email of owner on clicking it

### ISSUE THREAD

**Issue by govindumeesala** [mdazfar2/Ezyshop#75]
### Description

Adding animations in contact us page to enhance user experience 
and adding redirect link to the email of owner to directly mail and contact

### Screenshots

![image](https://github.com/user-attachments/assets/51eeb582-c945-4e6d-ae3a-4ec8ddd1b6ad)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@govindumeesala we don't need any animation thing please don't create issue related animation. ***Thank you***.
