### ISSUE TITLE
**Add "Terms and Conditions" Page Link in Footer Section**

### ISSUE THREAD

**Issue by ansiace** [mdazfar2/Ezyshop#751]
### Description

The footer section currently lacks a link to the "Terms and Conditions" page, which is important for legal clarity and user experience. Adding this page will ensure better transparency and compliance with standard practices.

#### Expected Behavior:
- A link to the "Terms and Conditions" page should be added in the footer section, alongside other key links, to improve site usability and professionalism.

#### Current Behavior:
- The footer section does not include a "Terms and Conditions" link.

### Screenshots

![Screenshot 2024-10-18 112336(1)](https://github.com/user-attachments/assets/296b7ff9-c34b-43f8-888c-efebaff20b4e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ansiace assigned.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by ishivansmishra** [comment]
@ansiace Please assign me this issue
