### ISSUE TITLE
[Feat] Enhancing the store and product cards

### ISSUE THREAD

**Issue by HemantBatra873** [mdazfar2/Ezyshop#752]
### Description

The card layout and design on the store and products page is not in line with the vibe of the rest of the website . The main theme of the website is blue so I want to first update the colors from green to the blue on the rest of the website . Then I want to update the card layout itself to make it look more professional like the sample I have added in the screenshots . 

**Please assign me this task under gssoc-ext and hacktoberfest-accepted . **

### Screenshots

**Screen Shots**

![EZYSHOP ISSUE 1](https://github.com/user-attachments/assets/3369240e-08a8-40da-b988-512f7f64d8e6)

![ISSUE 2 EZYSHOP](https://github.com/user-attachments/assets/e7f23471-5b74-41c0-b3c9-439a7068dc9c)

![EZYSHOP ISSUE 3](https://github.com/user-attachments/assets/56b99b21-75bd-409f-b309-4ece63c8063e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@HemantBatra873 You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
