### ISSUE TITLE
[Feat] ADDING USER INPUT SANITATION FROM XSS AND SQL INJECTION

### ISSUE THREAD

**Issue by anishka25** [mdazfar2/Ezyshop#753]
### Description

Right now there is no validation in place to prevent against xss injection or rare cases of sql injection. Proper sanitation would be added in the pr following this issue.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by karandevhub** [comment]
\assign
