### ISSUE TITLE
**Add "Privacy and Policy" Page Link in Footer Section**

### ISSUE THREAD

**Issue by ansiace** [mdazfar2/Ezyshop#754]
### Description

The footer section currently lacks a link to the "Privacy and Policy" page, which is crucial for legal compliance and user trust. Adding this page will ensure that users have easy access to the site's privacy policy, enhancing transparency.

#### Current Behavior:
- The footer section does not include a "Privacy and Policy" link.

#### Expected Behavior:
- A link to the "Privacy and Policy" page should be added in the footer section to provide users with important information about data protection and privacy practices.

### Screenshots

![Screenshot 2024-10-18 143045(1)](https://github.com/user-attachments/assets/b1da22e6-6984-4187-8d95-6aaa86ac066d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ansiace you are assigned.
