### ISSUE TITLE
[Typo]: Spelling of rajasthan is incorrect ,  

### ISSUE THREAD

**Issue by Jashwanth-rit** [mdazfar2/Ezyshop#755]
### Description

spelling of Rajasthan is written as Rajisthan in entry page , that should be corrected as Rajasthan

### Screenshots

![Screenshot 2024-10-18 150338](https://github.com/user-attachments/assets/603ae95c-ba92-4b88-b476-3584d22c26c1)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Jashwanth-rit you are assigned.

**Comment by amiya-cyber** [comment]
i want to fix this issue, kindly assign it to me me with the tag hacktoberfest and gssoc-extd

**Comment by mdazfar2** [comment]
Hey @Jashwanth-rit You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)

**Comment by Jashwanth-rit** [comment]
ok fine.
