### ISSUE TITLE
[Feat] Inserting translation tool on landing page

### ISSUE THREAD

**Issue by PrAyAg9** [mdazfar2/Ezyshop#757]
### Description

Adding a translation tool can offer several advantages:
- Accessibility: It helps break language barriers, making content accessible to a wider audience.
- Global Reach: Businesses can expand their market by reaching non-English speaking customers.
- Improved Communication: Facilitates better communication in multilingual environments, whether in business or social contexts.
- User Engagement: Engaging users in their native language can enhance their experience and increase retention.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@PrAyAg9 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
