### ISSUE TITLE
[BUG] Improve Hover and Shadow Effects for Feature Cards & Logo

### ISSUE THREAD

**Issue by Sunilkumarchavhan9** [mdazfar2/Ezyshop#76]
### Description

The feature cards and the website logo currently lack interactivity and visual depth, leading to a flat design. To improve the user experience and create a more modern and engaging interface, we need to implement hover and shadow effects for both the feature cards and the logo. This will provide better visual feedback for users and improve the overall design aesthetic.

### Screenshots

![Screenshot 2024-10-02 213921](https://github.com/user-attachments/assets/1a060a30-f5fe-4ce5-a781-d7e5cc7fe12a)

### Any additional information?

No breaking changes expected: These hover and shadow effects are purely CSS-based and shouldn’t interfere with any functionality of the website. There is no expected impact on backend processes or page performance.

Browser compatibility: The CSS properties used (e.g., box-shadow, transform, transition) are widely supported across all modern browsers, including Chrome, Firefox, Safari, and Edge. However, it might be good to double-check that the design looks consistent across older browsers if we support them (e.g., Internet Explorer 11).

Performance considerations: While these effects are lightweight and not expected to cause any performance issues, it’s important to test the effects on mobile devices as hover animations are not as intuitive on touchscreens. On mobile, the design should still look clean without hover effects.

Responsive design: The hover and shadow effects should be carefully tested on different screen sizes to ensure the lift effect or any changes in size or shadow don't break the layout or appear too exaggerated on smaller screens. We’ll need to ensure the transitions still look smooth on both desktop and mobile.

Design consistency: To maintain a cohesive visual design, ensure that similar effects are applied to other interactive elements on the page where necessary, such as buttons or links, so the user experience remains consistent throughout the platform.

Testing: Thorough testing on both desktop and mobile devices is recommended to verify that the animations perform as expected without lag or flicker.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [x] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Sunilkumarchavhan9, thank you for raising the issue.

- As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- please ⭐ our repo

- Don't forget to join our official [Discord server](https://discord.gg/SEzpxqQG).
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
