### ISSUE TITLE
Change of images

### ISSUE THREAD

**Issue by CharVaibhav** [mdazfar2/Ezyshop#760]
### Description

Hello there, as i was going through your website i noticed, that the landing page contains ai generated images which look more sketchy and unpleasing. I would like to change them to realistic images which are more pleasing and attractive.

### Screenshots

**Here is an example of the change of delivery boy image in the landing page would look like, ill be ready with many more options.**

![freepik__candid-image-photography-natural-textures-highly-r__34330](https://github.com/user-attachments/assets/77e3c7cd-a2c5-427e-bccd-a43e38a2d2d6)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@CharVaibhav You are assigned, but make sure the image is in .webp format.
