### ISSUE TITLE
[Feat]: dark and light toggle mode 

### ISSUE THREAD

**Issue by sv410** [mdazfar2/Ezyshop#762]
### Description

light and dark mode 

### Screenshots

![light](https://github.com/user-attachments/assets/da4e9ce6-3839-4de9-baba-073a63f824ed)
![night](https://github.com/user-attachments/assets/5aa40879-1ac4-4131-a5d4-15055d224c63)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@sv410, it is a very good toggle, but according to our website, the current dark/light mode icons look good, so I don't think there is a need for it on our website. Thank you.
