### ISSUE TITLE
[BUG] Change of Font colour in contact section

### ISSUE THREAD

**Issue by PulkitShubham** [mdazfar2/Ezyshop#764]
### Description

The text colour is very light in light theme................that's why it is not evident

### Screenshots

![image](https://github.com/user-attachments/assets/8d6d0ce3-d3e2-4f4e-94e3-83bc47878543)

### What browser are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@PulkitShubham As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
