### ISSUE TITLE
[BUG] Inconsistent Category Card Images and Load More Functionality Misplacement

### ISSUE THREAD

**Issue by kavya410004** [mdazfar2/Ezyshop#765]
### Description

I have observed two issues with the current implementation of the category cards on the homepage:

- **Category Card Images:** The images used for the category cards are different from those in the HTML, CSS, JS version of the site. The new images are disproportional, leading to an uneven and inconsistent user interface.
- **Categories Details**: The category titles and details are replaced with the shop names. The actual categories are missing from the web app.
- **Load More Functionality on Home Page:** The "Load More" functionality for categories is currently available on the homepage, which should not be the case. This feature should be exclusive to the category page for better navigation and user experience.
### Proposed Solution:
- **Image Replacement:** Replace the current category images with the older ones from the HTML, CSS, JS version, as they are more suitable and maintain a consistent proportion, thus improving the visual appeal of the category cards.
- **Add Category Details**: Replace the current shop details with the correct category details from the older version.
- **Component Separation:** Separate the categories component from the "Load More" button and its functionality into two distinct components. This will ensure that the "Load More" feature is only available on the category page, providing a cleaner homepage experience.

### Benefits:
- **Improves UI Consistency:** Using the original images will restore the proportionality of category cards, enhancing the overall aesthetic appeal.
- **Enhances User Experience:** By limiting the "Load More" functionality to the category page, users will have a more intuitive and focused browsing experience.

Please let me know if there are any guidelines or preferences I should follow while working on these changes.

### Screenshots
**Current category cards (uneven look):** The category card titles are shop names
![image](https://github.com/user-attachments/assets/3e7b81ea-9e2e-4484-9926-3fa05ceab35e)

**Old category cards (even look):** The actual categories
![image](https://github.com/user-attachments/assets/64edca8c-f8d5-4e55-a2a2-b448922ab786)

**Show more button in home page:**
![image](https://github.com/user-attachments/assets/c2c1ada9-5407-434c-9a7b-aaa4b7f4b365)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@kavya410004 you are assigned.
