### ISSUE TITLE
[Feat] Adding Search Bar in Shop Categories Page

### ISSUE THREAD

**Issue by J-B-Mugundh** [mdazfar2/Ezyshop#767]
### Description

Adding Search Bar in Shop Categories Page

### Screenshots

![image](https://github.com/user-attachments/assets/d3961d4d-ade2-4382-aebd-5d61f364a60b)
Currently, we dont have a search bar

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by J-B-Mugundh** [comment]
@mdazfar2 Could u please assign this issue?

**Comment by J-B-Mugundh** [comment]
@mdazfar2 May I please know why it's closed? I'm adding a feature which is not present + I've searched that this issue isn't there. Atleast, you could add the reason for closing this issue.

**Comment by mdazfar2** [comment]
Hey @J-B-Mugundh, sorry for the inconvenience. As of now, there is no need. We will let you know if anything is needed in the future. Please raise another issue, and I'll be happy to assign it to you.
