### ISSUE TITLE
[BUG] Login/signup link not working in navbar 

### ISSUE THREAD

**Issue by govindumeesala** [mdazfar2/Ezyshop#78]
### Description

[BUG] Login/signup link working only when currently we are in home page 
else if we are in any other page login/register link is not working 

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by myselfvipul** [comment]
I have checked the existing issues
 I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
 I'm a GSSoC'24-Extd contributor
 I'm a Hacktoberfest'24 contributor
 I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Go ahead @govindumeesala

**Comment by muhafiz5814** [comment]
Hey @mdazfar2 ,
I have raised the similar issue #50 earlier,
I think you have not read it,
I would also like to work on the issue #50 which also has some extra bug fix. Please look at it once.
Thank you.

**Comment by mdazfar2** [comment]
Thank you for letting me know @muhafiz5814, I'll close this issue.
