### ISSUE TITLE
[Feat]Want to add animation in the text- 'Revolutionizing How You Shop' and add effects on boxes.

### ISSUE THREAD

**Issue by itishacodes** [mdazfar2/Ezyshop#79]
### Description

I want to add 2 things to make this website more interactive: 

1. Adding a text animation on the landing page.
2. Adding shadow effects on the boxes, which comes on scrolling the landing page.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @itishacodes, right now we don't need any animations. Currently, we are working on dummy shops and products, which we will place on a new page. We will let you know if we need anything related to that. ***Thank you***.

- please ⭐ our repo

- Don't forget to join our official [Discord server](https://discord.gg/SEzpxqQG).
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
