### ISSUE TITLE
[BUG] Problem in 'Cart' page with mobile navbar 

### ISSUE THREAD

**Issue by Suvadip-sana** [mdazfar2/Ezyshop#791]
### Description

![Screenshot_2024-10-19-18-51-32-193_com android chrome](https://github.com/user-attachments/assets/9d3bf46e-3d4c-49f2-9415-f2b6924f005c)
Here as you can see there is a z-index problem with the cart page and it's mobile navbar. 
Which is not looking good at all. Need to fix it. 

### Any additional information?

@mdazfar2 
Please assign me this ISSU, I want to work on it. 
Thank you. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Suvadip-sana go ahead

**Comment by mdazfar2** [comment]
@Suvadip-sana Issue acknowledged! You are going to be assigned.

Hope you know that our website is fully converted to the Next.js and Tailwind CSS framework, so you have to work accordingly.

- Read our [Contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md] and make sure to contribute accordingly.


_Thank you_

**Comment by Suvadip-sana** [comment]
![image](https://github.com/user-attachments/assets/2f5b104b-db5e-4d93-9438-698e86789fc5)
This page is not found as usual. @mdazfar2

**Comment by ShivanshPlays** [comment]
https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md

**Comment by Suvadip-sana** [comment]
@ShivanshPlays Thanks

**Comment by Suvadip-sana** [comment]
@mdazfar2  Why this is closed?  Please let me know the reason?
