### ISSUE TITLE
[Feat] Add feature of adding category to the seller dashboard

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#797]
### Description

This is a necessary feature as the categories created in the dashboard by the seller will eventually display in the shop page in the main EZYSHOP website.

### steps I will follow for implementation of this feature:

1. Modify schema to accommodate categories in in addition to the user seller and billboard models in the current schema, a foreign key relation of category with the seller and the billboard so that each category is linked with a billboard and a category.
2. Add navbar link for redirection to category managing page
3. add category management page, the frontend for displaying the existing categories by querying the db on page mount.
4. add a form to add a new category.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mehul-m-prajapati** [comment]
@mdazfar2 : something is wrong here, only one guy is getting assignments for almost all issues.
