### ISSUE TITLE
[Feat] Add a button for scrolling up.

### ISSUE THREAD

**Issue by sanikamandale17** [mdazfar2/Ezyshop#816]
### Description

I want to add a "Scroll Up" button to the website this button will appear when users scroll down and allow them to quickly return to the top it is  easy to use and works well on all devices

### Screenshots

n/a

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by sanikamandale17** [comment]
plz assign me !! @mdazfar2

**Comment by mdazfar2** [comment]
hey @sanikamandale17 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
