### ISSUE TITLE
[Feat]:Login/Signup page is not responsive

### ISSUE THREAD

**Issue by RaviP9973** [mdazfar2/Ezyshop#817]
### Description

Login page is not responsive 
The "Welcome to Eazy shop " Card's texts are not clearly visible in smaller device

Also the hamburger menu do not close when login/signup button is clicked

I can fix this issue, kindly assign me this issue @mdazfar2 

### Screenshots

![image](https://github.com/user-attachments/assets/9cc4cd77-dbae-479c-8d9e-d0dfc9e87ffe)
![image](https://github.com/user-attachments/assets/541d7916-642d-4787-8e00-60be53177f9a)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [x] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by RaviP9973** [comment]
kindly assign this issue to me @mdazfar2

**Comment by harshita2303** [comment]
@mdazfar2  Please assign this issue to me

**Comment by mdazfar2** [comment]
@RaviP9973 Issue acknowledged! You are going to be assigned.

Hope you know that our website is fully converted to the Next.js and Tailwind CSS framework, so you have to work accordingly.

- Read our [Contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md] and make sure to contribute accordingly.


_Thank you_

**Comment by lavanyabandari** [comment]
can you please assign these issue to me..

**Comment by mdazfar2** [comment]
@RaviP9973 You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)

**Comment by RaviP9973** [comment]
But I already have completed most of the work
