### ISSUE TITLE
[ NEW ] : Add Links to Privacy Policy and Terms of Service on Login/Signup Pages

### ISSUE THREAD

**Issue by KAUSHIKRM-36** [mdazfar2/Ezyshop#818]
![image](https://github.com/user-attachments/assets/488f2ad4-54b3-47fe-9b73-ab82d8529208)
the current login signup page does not contain any link to privacy policy or terms of service

This issue proposes the inclusion of clear links to the Privacy Policy and Terms of Service on the login and signup pages. Providing these links ensures users can easily access important information regarding their data and usage rights before creating an account or logging in, enhancing transparency and compliance with privacy regulations.

@mdazfar2 please assign me this task under 
GSSOC extd 24 
Hacktoberfest 24

**Comment by KAUSHIKRM-36** [comment]
@mdazfar2 please assign me this task , i really want to contribute to this project .

**Comment by mdazfar2** [comment]
Hey @KAUSHIKRM-36, the Terms and Conditions and Privacy page are already on our website. Please check again and raise the issue accordingly. Thank you.

**Comment by KAUSHIKRM-36** [comment]
@mdazfar2 i meant there is no direct link provided on the sign up page , its a standard practice

**Comment by KAUSHIKRM-36** [comment]
![Screenshot 2024-10-20 171808](https://github.com/user-attachments/assets/4488b754-311d-41bc-92e1-c114df078a64)
this section could contain a link like 
![Screenshot 2024-10-21 210111](https://github.com/user-attachments/assets/9448ea9e-b770-41d9-a1e8-bfb925abf38f)


please assign me this task @mdazfar2

**Comment by mdazfar2** [comment]
@KAUSHIKRM-36, I cannot understand. Please share a screen recording or any relevant screenshot so I can understand.

**Comment by mdazfar2** [comment]
> ![Screenshot 2024-10-20 171808](https://github.com/user-attachments/assets/4488b754-311d-41bc-92e1-c114df078a64)
> this section could contain a link like 
> ![Screenshot 2024-10-21 210111](https://github.com/user-attachments/assets/9448ea9e-b770-41d9-a1e8-bfb925abf38f)
> 
> 
> please assign me this task @mdazfar2 


When both options are already available in the footer, why is it necessary to keep them there? Please ignore this issue for now.

**Comment by KAUSHIKRM-36** [comment]
> > ![Screenshot 2024-10-20 171808](https://private-user-images.githubusercontent.com/182990598/378494037-4488b754-311d-41bc-92e1-c114df078a64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjUzMTEsIm5iZiI6MTcyOTUyNTAxMSwicGF0aCI6Ii8xODI5OTA1OTgvMzc4NDk0MDM3LTQ0ODhiNzU0LTMxMWQtNDFiYy05MmUxLWMxMTRkZjA3OGE2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQxNTM2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODhmOGE2ZTYyNmI0Nzk2Y2E3OTRiOTNkNDkxZjc1ZWJkYmIzZjI0MjBkNGNjZmMyYTQwMjcwMDc1ZTQ5YTA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.W_GrIcRhoi7UmeHgtvpD2TFl8s68rhv-tBOSQhZRXkg)
> > this section could contain a link like
> > ![Screenshot 2024-10-21 210111](https://private-user-images.githubusercontent.com/182990598/378494730-9448ea9e-b770-41d9-a1e8-bfb925abf38f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjUzMTEsIm5iZiI6MTcyOTUyNTAxMSwicGF0aCI6Ii8xODI5OTA1OTgvMzc4NDk0NzMwLTk0NDhlYTllLWI3NzAtNDFkOS1hMWU4LWJmYjkyNWFiZjM4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQxNTM2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmE1YjNjYzE2OGVhYzYxNmVjNGI3NTE3NGJlZTM1M2NkNWVmZjEzYzU1NDQ0MDFlMzQwZDE4MmY0ZDA4OTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GdztDgEn64d-zwMQnpHy3gWqMP9UX1JJArEt9GXQSq4)
> > please assign me this task @mdazfar2
> 
> When both options are already available in the footer, why is it necessary to keep them there? Please ignore this issue for now.

okay fine
