### ISSUE TITLE
Add table of contents to the readme file

### ISSUE THREAD

**Issue by T-Fathima** [mdazfar2/Ezyshop#819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I would like to add table of contents to the readme file for better navigation and user experience.

### Suggested Change

Add sections accordingly and navigate to them.

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hey @T-Fathima As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
