### ISSUE TITLE
[Feat] Improve Customer Reviews Section

### ISSUE THREAD

**Issue by SurajSG23** [mdazfar2/Ezyshop#82]
### Description

Hey i would like to make the top reviews section to move dynamically, i.e,

![image](https://github.com/user-attachments/assets/d34bd4b8-6672-49bc-a13d-b52edcde9524)

instead of clicking on the small dot to see the next review, the reviews can be made to move (linear transition) which makes the user to see all the reviews easily and thus enhances the UX and UI.

The transition will be stopped once the mouse hovers on the review list.
Please do assign me this issue, I am willing to fix it under gssoc and hacktober fest

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@SurajSG23 can you please send me the demo video.

**Comment by SurajSG23** [comment]
> @SurajSG23 can you please send me the demo video.

Sure, here it is

https://github.com/user-attachments/assets/28ebb056-86d2-430f-95c1-99fe7f515357

like this example, the images and moving from right to left, i wanna make the reviews move in the same manner, instead of clicking on the dot to see the next review. once the mouse hovers the animation will be stopped.

I am willing to do it under gssoc and hacktober fest

**Comment by mdazfar2** [comment]
@SurajSG23 Issue acknowledged! You are going to be assigned.

**Comment by Divyansh2992** [comment]
i want to contribute.Please assign it to me
