### ISSUE TITLE
[Feat] add contributor or team page at footer

### ISSUE THREAD

**Issue by ananyag309** [mdazfar2/Ezyshop#820]
### Description

add contributor or team page at footer will look more proeffesional

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @ananyag309 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

**Comment by BhavikaPachauri** [comment]
please assign this issue

**Comment by mdazfar2** [comment]
Hey @ananyag309 @BhavikaPachauri, if you see this, please let me know if you can do something like this. I’ll explain below.

I am also mentioning the top contributors on the GSSoC leaderboard as they asked me. Please let me know if there’s a need to contribute and also I'm mentioning who are genuinely working and have already created good pull requests merged on Ezyshop.

- @shubhagarwal1
- @ShivanshPlays 
- @inkerton
- @kavya410004 
- @Bhum-ika 
- @Shariq2003
- @IkkiOcean
- @Subhajit-2023-44
- @Sawan-Kushwah
- @priyanshuverma-dev
- @mehul-m-prajapati

Actually, we already have a contributor page in the footer, and it’s already implemented. Check out the implemented contributor page:

![{CE8E232A-4382-459F-BFCA-F41D32588704}](https://github.com/user-attachments/assets/96036f08-b29d-4334-a885-314db1d59b2e)

<br>


**But I’m thinking of changing the UI and design of the contributor page. I have a design for the updated contributor page; please let me know if you can work on it. Below, I will attach the image of that design:** 👇

<br>

![Copy of Meet Our Contributors](https://github.com/user-attachments/assets/d44f3ad8-1aca-4e82-8e85-f3690077524e)

<br>


> [!NOTE]
> You will receive a level 3 label for the GSSoC-Ext leaderboard points after the pull request for this issue is merged. However, please try to implement this within 1 to 2 days; otherwise, I will assign it to someone else and provide other opportunities according to the guidelines.

<br>

> [!NOTE] 2
> Don't add my profile. I mean, remove my profile from the contributor page. What I mean is, even though my profile will appear as the top contributor based on my commits, don’t include it—remove my profile and don’t fetch it from the GitHub contributors. Hope you understand.

<br>


- Let me know if anyone is interested in working on this. It is on a **first-come, first-served** basis.

<br>



**Thank you!**

**Comment by IkkiOcean** [comment]
@mdazfar2 I can work on this. Assign me

**Comment by ananyag309** [comment]
@mdazfar2 I am also interested

**Comment by Shariq2003** [comment]
@mdazfar2 sir, assign this to me

**Comment by Sawan-Kushwah** [comment]
@mdazfar2 i am interested

**Comment by mdazfar2** [comment]
Alright @IkkiOcean you are going to be assigned. 

Make sure to implement the exact design I shared above; otherwise, if there is any issue with the UI or fetching, the PR will be closed.

Read our [Contrubuting guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md) and contribute accordingly.

Try to create PR as soon as possible.

**Comment by BhavikaPachauri** [comment]
okk i start work on it

**Comment by mehul-m-prajapati** [comment]
@mdazfar2 : thanks for tagging me.
Everyone can design this page, and then you can pick the best one for a grand total of 45 points!

**Comment by mdazfar2** [comment]
No @mehul-m-prajapati, it’s not a good approach as it wastes other contributors' time for only one best PR, which isn’t ideal. Hope you understand.

**Comment by mdazfar2** [comment]
> @mdazfar2 Ah! I am late. Let me know if their is any other issue



@priyanshuverma-dev check the issue #978

**Comment by mdazfar2** [comment]
> @mdazfar2 Ah! I am late. Let me know if their is any other issue



@priyanshuverma-dev check the issue #978
