### ISSUE TITLE
[Feat] Add a new page to display all contributors ✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [mdazfar2/Ezyshop#827]
### Description

I want to add a page to showcase all the contributors of this website..

@mdazfar2 PA please assign me this task.

![Screenshot 2024-10-20 211104](https://github.com/user-attachments/assets/c50dd242-828e-4182-a31c-e4ccd8b3d12f)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Subhajit-2023-44, yes, we are considering adding a contributor page, and we already have a page on the navbar called `/Team`. When you click on `/Team`, you'll see the prompt for it. Actually, I want to update the contributor section on the team page to make it look more special, so I need some time for that. I will let you know if there are any updates for the team page. _Thank you!_
