### ISSUE TITLE
[BUG] Navbar is congested

### ISSUE THREAD

**Issue by pbln** [mdazfar2/Ezyshop#828]
### Description

I think the project is real cool , but if the navbar contents are spaced in a bit better way , the ui will definately improve . 

### Screenshots

![image](https://github.com/user-attachments/assets/8fc7f18e-ca52-4ed4-a99e-98e7b6c15806)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@pbln As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
