### ISSUE TITLE
[BUG] The Signup page white text

### ISSUE THREAD

**Issue by pbln** [mdazfar2/Ezyshop#829]
### Description

The white text on the signup page has merged with the background which needs to be fixed .

### Screenshots

![image](https://github.com/user-attachments/assets/8bf905b1-be5a-492a-87ee-0eeb1e46537e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@pbln, it looks correct on my side. Please check the website again and make sure to raise valid issues or bugs that are actually needed for our website. I’ll be happy to assign such issues. _Thank you!_
