### ISSUE TITLE
[BUG] Footer's Get in touch Cursor isn't appropriate

### ISSUE THREAD

**Issue by foreshubham** [mdazfar2/Ezyshop#83]
### Description

In footer section --> Get in touch we can do cursor pointer and add clickable functionality to directly call by clicking on mobile no. and also for email. 

### Screenshots

![image](https://github.com/user-attachments/assets/0625bdd4-f283-4f45-bf51-19c5d66728f5)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@foreshubham As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- please ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
