### ISSUE TITLE
[BUG] Footer part Esyshop typo!

### ISSUE THREAD

**Issue by pbln** [mdazfar2/Ezyshop#830]
### Description

Esyshop should be EsyShop in the footer part . 

### Screenshots

![image](https://github.com/user-attachments/assets/1bdcdf92-78ba-4dad-90e1-aa540180c9e7)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@pbln That's not Typo actually this is our email for ezyshop.
