### ISSUE TITLE
[BUG] A UI enhancement in the light theme.

### ISSUE THREAD

**Issue by pbln** [mdazfar2/Ezyshop#831]
### Description

The dark theme gradient looks real cool , but the light mode is a bit simpler and plain , I wish to add a gradient in light mode that match the essence and vibe of the website . Thank you .

### Screenshots

![image](https://github.com/user-attachments/assets/19869527-1110-4a16-9178-81597a5dd7e7)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @pbln, that's a great idea, but I'm not sure which type of gradient we should add in light mode. It would be helpful if you could show me the gradient color by taking a screenshot or making changes to the code and then sending the updated screenshot of the gradient color in light mode. This will help me understand better and assign the issue more easily. _Thank you!_

**Comment by LavishaMhjn1910** [comment]
assign it to me and plz label it

**Comment by mdazfar2** [comment]
> assign it to me and plz label it 


@LavishaMhjn1910 It would be helpful if you could show me the gradient color by taking a screenshot or making changes to the code and then sending the updated screenshot of the gradient color in light mode. This will help me understand better and assign the issue more easily. _Thank you!_

**Comment by BhavikaPachauri** [comment]
please assign the issue
