### ISSUE TITLE
[Feat] : Implement Contact Us Page Via E-Mail.

### ISSUE THREAD

**Issue by PriyanshuValiya** [mdazfar2/Ezyshop#834]
### Description

From this feature user will can mail you for any inquiry.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by harshita2303** [comment]
@mdazfar2 Please assign this issue to me

**Comment by mdazfar2** [comment]
@harshita2303 @PriyanshuValiya As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
