### ISSUE TITLE
[Feat]:The links in. the footer sections hover can be enhanced.

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [mdazfar2/Ezyshop#835]
### Description

The links in the footer looks very simple.Its hover can be enhanced.

### Screenshots

https://github.com/user-attachments/assets/f4e650ae-bb84-43a8-ab04-486d24566f98

Please assign this issue to me under level1.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Arghya-Chakraborty0812, as we are not decided to add any hover effect to our website, we will let you know if there's any work related to it. You can search for other issues/bugs and raise an issue accordingly. Thank you for raising the issue.
- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
