### ISSUE TITLE
[BUG] Replace Hardcoded Store List with Dynamic Data from Database  

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#841]
## Issue Description  
This issue aims to **remove the hardcoded list of stores** from the frontend and instead **fetch the stores dynamically from the database**. The goal is to display the store list while **maintaining consistency** with the current UI.

---

## Steps to Implement:  
1. **Backend:**  
   - Create a **GET API route** to fetch the list of stores from the database.  
   - Ensure the route is **optimized** and only returns necessary store details.

2. **Frontend:**  
   - Replace the **hardcoded store list** with a **fetch request** to the new API.  
   - Display the fetched stores **within the existing UI layout** to maintain consistency.  
   - Handle **loading states** while the store data is being retrieved.  
   - Add **error handling** to gracefully manage failed requests.

3. **Integration:**  
   - Ensure that the UI remains **consistent with the current design** after integrating the dynamic store list.  
   - Verify that the store list updates automatically if new stores are added in the database.

---

### How to Test:  
1. Load the **Stores page** and verify the list is dynamically fetched from the database.  
2. Check the **loading and error states** to ensure smooth transitions.  
3. Add a new store to the database and confirm it **appears on the frontend** without hard refresh.  
4. Ensure the design remains **consistent** with the existing UI after dynamic data integration.

---

### Checklist:  
- [x] Created a GET API route to fetch store data from the database.  
- [x] Replaced hardcoded stores with dynamic fetch requests.  
- [x] Handled loading and error states gracefully.  
- [x] Verified that the frontend stays consistent with the original design.  

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by MastanSayyad** [comment]
@mdazfar2 There are other open issues as well. Can you assign them to contributors or at least close them with proper context? If you assign issues to a single contributor while neglecting others, it could be seen as favoritism from the PAs, which shouldn’t happen.

To avoid this, kindly review the other issues too. You were a Project Admin in previous GSSoC programs, so you are already well aware of the guidelines.

Also, I have seen that @ShivanshPlays has already 50+ PRs which are already merged/closed so you should look over it once and give other contributors fair chances

**Comment by mdazfar2** [comment]
Okay @MastanSayyad, I will review all the issues as well. Actually, my platelets are low, and it’s been hard for me to manage all the contributors. Many contributors are raising the same issues repeatedly after they’ve been closed, which is a bit frustrating. That’s one reason I haven't been able to check the issues, but I will go through them now. Thank you for letting me know.
