### ISSUE TITLE
[BUG] Comment section doesn't works

### ISSUE THREAD

**Issue by DrashtiMistry** [mdazfar2/Ezyshop#846]
### Description

Can't able to do comments!

### Screenshots

![image](https://github.com/user-attachments/assets/0e31c384-6d5d-4bf2-90c5-580fe214c633)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by DrashtiMistry** [comment]
@mdazfar2  Please assign this issue to me

**Comment by mdazfar2** [comment]
@DrashtiMistry we will let you know after the completion of login and signup.
