### ISSUE TITLE
[BUG] Fix social media buttons

### ISSUE THREAD

**Issue by KhanjarSingh** [mdazfar2/Ezyshop#848]
### Description

Instagram button doesnt take us to insta page 

### Any additional information?
Buttons should open the links to new tab

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by KhanjarSingh** [comment]
@mdazfar2 i want to fix this issue, can you please assign it to me under the tag under the tag hacktober fest

**Comment by KhanjarSingh** [comment]
@mdazfar2 can i work on this ?

**Comment by mdazfar2** [comment]
Hey @KhanjarSingh, we don't have an Instagram account for Ezyshop at the moment. Once we create one, we'll let you know to add the correct redirection link.
