### ISSUE TITLE
[BUG] Center Ezyshop Founder in about and teams

### ISSUE THREAD

**Issue by TanishqMehrunkarIIPSDAVV** [mdazfar2/Ezyshop#85]
### Description

![image](https://github.com/user-attachments/assets/ef6aa3fe-1e0f-416f-b917-7e8b6c54c159)
founder logo can be centered in about and teams pages

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@TanishqMehrunkarIIPSDAVV Go ahead.

- please ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)

**Comment by Divyansh2992** [comment]
i want to contribute

**Comment by TanishqMehrunkarIIPSDAVV** [comment]
@Divyansh2992 for contributing you have to raise an issue and then the admin will assign you the task to overcome the issue you raised, then you can contribute by raising a PR.

**Comment by mdazfar2** [comment]
not response now
