### ISSUE TITLE
 Improve Event Title Visibility in Light Mode and Add "Mailto" Functionality for Email Links

### ISSUE THREAD

**Issue by sriharsha0x1** [mdazfar2/Ezyshop#851]
### Description

Could you please assign both of these to me? @mdazfar2 
i will also improve the UI of footer

### Screenshots

![image](https://github.com/user-attachments/assets/9462d358-114f-401a-b3b2-38294cac3d23)

![image](https://github.com/user-attachments/assets/1c165849-2be7-4d07-9c8c-cfe953b8abb3)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@sriharsha0x1 On my side, it looks fine. Please raise another issue that is really needed for our website. Here, you can see the screenshot below as proof that everything is working well.

**Comment by sriharsha0x1** [comment]
@mdazfar2 Try to enter name and email you get the issue i.e, Light text
