### ISSUE TITLE
[BUG] Login/signup not working

### ISSUE THREAD

**Issue by Sourabh782** [mdazfar2/Ezyshop#854]
### Description

Loging and signup not working (Even after correct credentials)

### Screenshots

![Screenshot 2024-10-21 205133](https://github.com/user-attachments/assets/2c1e8772-0f9a-42d6-aba3-bc91a81f7af6)
![Screenshot 2024-10-21 205058](https://github.com/user-attachments/assets/b20b8632-f5ef-4ffe-bae6-35cf4804a9fc)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Sourabh782, actually, we haven't updated our .env variables in Vercel, which is why it's not working properly. But after the update, you will receive the OTP on your email address.
