### ISSUE TITLE
[BUG] authentication pages are not responsive for mobile screen sizes and authentication giving 500 error in deployment

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#857]
### Description

Please assign me and I will work on seller authentication page responsiveness under this issue.

### Screenshots

![image](https://github.com/user-attachments/assets/1c72b5f8-f4f3-41f0-ab48-806e8b417feb)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ShivanshPlays** [comment]
This is an update on this issue:
I found one more issue while working, there are bug in the backend that are causing the users an error while authenticating themselves:
![image](https://github.com/user-attachments/assets/4485e818-1cf2-4140-958b-7b526f9cc526)
I have worked on this bug can I include that in this pr only?
@mdazfar2

**Comment by mdazfar2** [comment]
Thanks for letting me know, @ShivanshPlays. Sure, you can attach the same thing to that issue and raise a PR accordingly.
