### ISSUE TITLE
[Doc]: Added All Contributors' Profile Photos

### ISSUE THREAD

**Issue by say-het** [mdazfar2/Ezyshop#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

 - It lacks Contributors Profiles in Readme.md
 - It should be Like the image that I have shared
 - Hey! @mdazfar2  I have already fixed it. Can you assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR.

### Suggested Change

 **I will add this type of Live Contributor Profile Photos in it**
![image](https://github.com/user-attachments/assets/c109d3d6-a375-493e-a01b-aaf9370d603c)

### Rationale

 - Little about me: I am an experienced contributor as I have successfully completed Hacktoberfest-2020, Hacktoberfest-2023 and GSSoC-2024.

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@say-het As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- please ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
