### ISSUE TITLE
[Feat] Add FAQ (Frequently Asked Questions) Section to the Website

### ISSUE THREAD

**Issue by 13Sharad** [mdazfar2/Ezyshop#860]
### Description

🔴 Tech stack:

HTML
CSS(TailWind.Css)
JavaScript (optional for collapsible or interactive FAQ)

🔴 Objective:

Provide users with a dedicated section to address common queries and provide detailed answers, improving user experience by offering quick access to essential information.

🔴 Summary:

The FAQ section will help visitors quickly find answers to common questions regarding EzyShopz services, shipping policies, product details, returns, and more. By organizing the most frequently asked questions in an easily navigable format, users can save time and reduce the need to contact support. Optionally, adding collapsible questions with JavaScript will create a clean, user-friendly layout that doesn’t overwhelm the page.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @13Sharad, as you mentioned, you used the tech stack HTML, but we have now completely shifted to the Next.js framework. We are not planning to add any FAQ page for now; if there is a need in the future, we will let you know.
