### ISSUE TITLE
[Feat]: Adding Best seller button 

### ISSUE THREAD

**Issue by Stpchethan** [mdazfar2/Ezyshop#864]
### Description

By enabling best seller button user can **quickly access the best seller products** and there is a **high scop  of buying a product** of 
 best seller .
![Screenshot (84)](https://github.com/user-attachments/assets/84e43424-6096-428a-95b9-2ac6de47d253)
Please assign me the issue .
i'm a GSsoc-Extended '24 conrtributor.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Stpchethan As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
