### ISSUE TITLE
[BUG] Text Not Visible in Login and Register Pages

### ISSUE THREAD

**Issue by ShobhitPatra** [mdazfar2/Ezyshop#865]
### Description

The Heading text "Log In" and "Sign Up" is not visible.Small styling issue.

### Screenshots

![Untitled design](https://github.com/user-attachments/assets/70586702-f742-4b3e-8e02-494633a0320e)

### What browser are you seeing the problem on?

Google Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShobhitPatra As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
