### ISSUE TITLE
[Feat] Adding (Update location) button.

### ISSUE THREAD

**Issue by Stpchethan** [mdazfar2/Ezyshop#867]
### Description

By adding **update location button (API)** , website  can easily access the **location of the user** with out any discrepancies for the **online delivery** of the user .
![Screenshot (85)](https://github.com/user-attachments/assets/ea6b7fd5-a1e0-48fe-93bc-30c1bce2526b)
Please assign the issue . 
GSsoc'24-Extd Contributor.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Stpchethan As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
