### ISSUE TITLE
Generate Popups/ Notification/ Alert on the Landing Page 

### ISSUE THREAD

**Issue by dev129** [mdazfar2/Ezyshop#869]
### Description

The aim is to enhance user engagement and boost website traffic for the Ezyshop website by offering interactive features like alerts, popups, and notifications. These features are designed to promote  exclusive deals, and keep users updated about Ezyshop activities, keeping them hooked to websites.

What do you think @mdazfar2 about this ?
### Screenshots

https://github.com/user-attachments/assets/b41e0567-b038-49d1-ac04-389652e45753
This is an example of popup notification I create for GDG-RCCIIT website.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@dev129 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
