### ISSUE TITLE
[Feat] Adding feedback form

### ISSUE THREAD

**Issue by TBorundia** [mdazfar2/Ezyshop#871]
### Description

Create a feedback form to collect user input and improve website features. The form should include the following:

Input fields for name, email, and feedback message.
A star rating system for user satisfaction.
Form validation to ensure all fields are correctly filled before submission.
A responsive design that works seamlessly on all devices.
A success/failure message after form submission.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @TBorundia, we already have a feedback form. Please look at every page carefully and raise issues accordingly.

_Thank you!_
