### ISSUE TITLE
[Feat]Adding Scroll Progress Bar

### ISSUE THREAD

**Issue by RachitSahu26** [mdazfar2/Ezyshop#872]
### Description

@mdazfar2 
I would like to add scroll progress bar
could you please assign it to me

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@RachitSahu26, as of now, we don't plan to add a scroll bar since the simple look is good. So, for now, I'm closing this issue. Please raise any other issue, which I’d be happy to assign to you.
