### ISSUE TITLE
[Feat] Add of a custom 404 Page Not Found, fallback page when page is not found

### ISSUE THREAD

**Issue by RachitSahu26** [mdazfar2/Ezyshop#873]
### Description

The project currently does not have a custom 404 - Page Not Found fallback. A personalized 404 page improves user experience by guiding users back to the main site or suggesting helpful links when they land on a non-existent page.

Proposed Solution
Create a custom 404 page with a friendly message and navigation links (e.g., “Go to Home” or “Explore Dashboard”).
Update the routing configuration to display this page for unknown URLs.
This will enhance usability and make the site feel more polished.

assign me @mdazfar2 

### Screenshots

![375737169-535b6b36-b116-435e-87a6-9d1d08b10830](https://github.com/user-attachments/assets/f7d1f721-b133-47b0-bb20-db4f8f0f0388)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @RachitSahu26, this is really good, but the UI doesn’t look good to me. Can you please make it similar to the [Blinkit](https://blinkit.com/) website? I mean, when you enter something on the [Blinkit](https://blinkit.com/) website that is not available, the UI shows a message and automatically redirects to the homepage. You can check the video below for reference.

<br/>


https://github.com/user-attachments/assets/7060c864-105e-4b04-888f-f3fca6cb01d7

<br>

Now I am also attaching the screenshot below, which looks exactly like that, but on your side, you just have to change the color to match our website.

![image](https://github.com/user-attachments/assets/13b025ca-5504-4db9-bd9b-13e82e56a32d)

<br/>

Hope you know that our website is fully converted to the Next.js and Tailwind CSS framework, so you have to work accordingly.

- Read our [Contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md) and make sure to contribute accordingly.


_Thank you!_

**Comment by RachitSahu26** [comment]
I wanted to update you all that I have successfully set up the project locally. I'm excited to start working on the improvements we discussed, particularly enhancing the UI to make it more aligned with the Blinkit website.

I’ll focus on implementing the message display for unavailable items and the automatic redirection to the homepage. Looking forward to making some great progress! @mdazfar2
