### ISSUE TITLE
[Feat] Add animated cursor 

### ISSUE THREAD

**Issue by RachitSahu26** [mdazfar2/Ezyshop#874]
### Description

Enhance the website's interactivity and aesthetics by adding an animated cursor. A custom cursor can make the UI feel more engaging and provide a unique user experience.

Proposed Solution
Implement a smooth, animated cursor using CSS and JavaScript.
Offer fallback to the default cursor for unsupported browsers.
Optionally, customize the cursor based on user actions (e.g., hover effects or different pages).
This feature will make the site more dynamic and visually appealing.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@RachitSahu26 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
