### ISSUE TITLE
[Feat] Add Subscription Plans for Regular Users.

### ISSUE THREAD

**Issue by Anshikapal05** [mdazfar2/Ezyshop#875]
### Description

A subscription model allows users to sign up for regular frequent purchase, such as groceries or household essentials.
-Schedule Recurring Orders: Set weekly, bi-weekly, or monthly deliveries of selected items.
-Flexible Management: Users can adjust delivery schedules, skip deliveries, or cancel subscriptions anytime.
-Discounts on Subscriptions: Offer special discounts for subscribers to incentivize long-term commitments.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Anshikapal05** [comment]
@mdazfar2 Could you please assign this task to me? It would be really helpful of you.

**Comment by mdazfar2** [comment]
@Anshikapal05 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
