### ISSUE TITLE
[Feat] Make the Nav bar sticky

### ISSUE THREAD

**Issue by RachitSahu26** [mdazfar2/Ezyshop#876]
### Description

assign me  @mdazfar2 ,
i would like to work on it

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @RachitSahu26 You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
