### ISSUE TITLE
[Feat] Add a map showing the more number of buyers

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [mdazfar2/Ezyshop#878]
### Description

Add a map showing the more number of buyers

### Screenshots

<img width="958" alt="map" src="https://github.com/user-attachments/assets/40370ccc-9a35-4f7d-afb5-c0c9148877df">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@KapuluruBhuvaneswariVspdbct As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
