### ISSUE TITLE
to provide hover effect over the divs in "OUR FACILITIES SECTION"  !

### ISSUE THREAD

**Issue by 2004pra** [mdazfar2/Ezyshop#879]
### Description

i will be providing hover effect over these divs one by one
please assign me this issue under gssoc extd 24, hactober fest, make it atleast level 2 because it hard to complete the css design easily.
@mdazfar2 

### Screenshots

these are the div where i will provide hover effect
![Screenshot 2024-10-22 155726](https://github.com/user-attachments/assets/26fd5988-be2f-4212-a4d5-0be457a7ccdd)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @2004pra, as we are not decided to add any hover effect to our website, we will let you know if there's any work related to it. You can search for other issues/bugs and raise an issue accordingly. Thank you for raising the issue.
- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
