### ISSUE TITLE
[Feat] Implement Dark Mode Feature

### ISSUE THREAD

**Issue by rajlakshmi18704** [mdazfar2/Ezyshop#88]
### Description

#88
I would like to propose adding a dark mode feature to the EzyShop platform. This feature will enhance the user experience by allowing users to switch between light and dark themes based on their preferences, especially in low-light environments.

 A user-friendly toggle button should be implemented to allow users to easily switch between light mode and dark mode.

I am willing to work on this issue.Please assign this issue to me under hacktoberfest and GSSoC'24-Extd 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
hey @rajlakshmi18704 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- please ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
