### ISSUE TITLE
[Doc]: adding Stargazers and Forkers section to readme.md 

### ISSUE THREAD

**Issue by amiya-cyber** [mdazfar2/Ezyshop#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

adding Stargazers and Forkers section to readme.md 

use case

1. Stargazers highlight the GitHub users' profiles who starred the repository.
2.  And forkers show the people who have already forked the repository

### Suggested Change

update in 
![2024-10-22 (8)](https://github.com/user-attachments/assets/f99be619-6d24-4968-b6ad-cd53baac66c0)
readme.md

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@amiya-cyber As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
