### ISSUE TITLE
To add a search bar

### ISSUE THREAD

**Issue by kusol2004** [mdazfar2/Ezyshop#881]
### Description

want to add a search bar at the top

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by A7Lavinraj** [comment]
can i work on it?

**Comment by mdazfar2** [comment]
@A7Lavinraj As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
