### ISSUE TITLE
[Feat] Enhancement of the navbar

### ISSUE THREAD

**Issue by shriyadindi** [mdazfar2/Ezyshop#882]
### Description

i would like to do the Enhancement of the navbar

### Screenshots

![Screenshot 2024-10-22 172337](https://github.com/user-attachments/assets/e58e94b1-9db4-46b1-b9da-2f9ffd7c8a70)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@shriyadindi As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
