### ISSUE TITLE
[⭐FEATURE] Add a Visitor Counter feature ✨ 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [mdazfar2/Ezyshop#884]
### Description

I want to add a Visitor Counter feature properly.

@mdazfar2  PA please assign me this task.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Subhajit-2023-44** [comment]
@mdazfar2

**Comment by mdazfar2** [comment]
@Subhajit-2023-44, I don't think the visitor count feature would be beneficial for our website. Please raise valid issues that are actually needed for our website. Avoid raising unnecessary issues like FAQ pages, contributor pages, visitor counts, language translation, etc. Please read our README.md file and raise issues accordingly. Don't raise issues that are not needed for our website.
