### ISSUE TITLE
[BUG] when in dArk mode the signup page is not visible properly

### ISSUE THREAD

**Issue by REHAN-18** [mdazfar2/Ezyshop#885]
### Description

can change the ui of the sign up page do better sign up ui 

### Screenshots

<img width="1182" alt="Screenshot 2024-10-22 at 6 20 00 PM" src="https://github.com/user-attachments/assets/8a5e1316-46e0-4d5a-a2d0-bd2eb8ce5b7d">

### What browser are you seeing the problem on?

Safari

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@REHAN-18 You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
