### ISSUE TITLE
Add Cursor Pointer to "Proceed as a" Section on Signup Page

### ISSUE THREAD

**Issue by ansiace** [mdazfar2/Ezyshop#889]
### Description

I found a bug on the **Signup page** where the **"Proceed as a"** section does not have the appropriate cursor pointer when hovered. This makes the section feel less interactive and may confuse users about its functionality.

#### Problem:
- The **"Proceed as a"** section lacks the `cursor: pointer` property, which is a standard for clickable elements.
- This may lead to a poor user experience as users might not realize that the section is interactive.

### Screenshots

https://github.com/user-attachments/assets/214bbe6f-8707-407f-a82e-b3b719b5a676

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ansiace, I understand this is a genuine bug, but we're currently focusing on the backend of the login/signup pages for both sellers and customers. To avoid conflicts with our ongoing work, I'd recommend closing this issue for now. We'll revisit it once the backend changes are complete. ***Thank you!***

**Comment by ansiace** [comment]
Ok fine
