### ISSUE TITLE
[Feat] Creating a like icon for the blog post .

### ISSUE THREAD

**Issue by RabdeepKaur** [mdazfar2/Ezyshop#892]
### Description

Add a "like" icon (thumbs up) to the blog post.
Icon should be clickable and Include a counter next to the icon to display the number of likes.

### Screenshots

![Screenshot_2024-10-22-22-23-24-594_com android chrome-edit](https://github.com/user-attachments/assets/f72bc34b-a472-46ea-940d-824a670c562b)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by RabdeepKaur** [comment]
@mdazfar2  please assign this issue to me under gssoc-extd  and hacktoberfest label

**Comment by mdazfar2** [comment]
hey @RabdeepKaur As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
