### ISSUE TITLE
[BUG] When you click on 'Start Shopping,' it redirects to the shopping page.

### ISSUE THREAD

**Issue by govindbairi** [mdazfar2/Ezyshop#894]
### Description

I am experiencing a bug where clicking on the "Start Shopping" button does not redirect users to the shopping page as intended. Instead, the action either results in no response or an error message.

### Screenshots

![Screenshot 2024-10-22 235834](https://github.com/user-attachments/assets/1e26fd5f-45c0-4983-9076-db7dc6272232)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @govindbairi, we are working on that button, which is connected to the Seller dashboard. We are currently working on the backend of the Seller dashboard and will complete it soon, making the button visible. For now, I am closing this issue. Please don’t be discouraged. ***Thank you!***
