### ISSUE TITLE
Improve Card design on Landing page

### ISSUE THREAD

**Issue by shubhagarwal1** [mdazfar2/Ezyshop#899]
**Changes to be made**
- Will make it hoverable 
- Make it look appealing
- Add badges to it 
![image](https://github.com/user-attachments/assets/16670f2c-2397-4e40-9201-2cc9e3f9506b)

**Comment by shubhagarwal1** [comment]
> **Changes to be made**
> 
> * Will make it hoverable
> * Make it look appealing
> * Add badges to it
>   ![image](https://private-user-images.githubusercontent.com/105449260/379068668-16670f2c-2397-4e40-9201-2cc9e3f9506b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDg1NTksIm5iZiI6MTcyOTY0ODI1OSwicGF0aCI6Ii8xMDU0NDkyNjAvMzc5MDY4NjY4LTE2NjcwZjJjLTIzOTctNGU0MC05MjAxLTJjYzllM2Y5NTA2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwMTUwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzI0NjM1MTIxZmY0YjA0ODFlMDdiYmViN2U5OWNmZjk3MWE4MjA3NTFlZGE0NWY0NzlhYzgwMjlhNjRhYWE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ods_FktT8hDQtVvP8N92go2cXh5GuuYB0hvLxXypv1Y)

Hey @mdazfar2 please assign me this task, if you do not find it improving please suggest something i can work on

**Comment by mdazfar2** [comment]
Hey @shubhagarwal1, as we are not decided to add any hover effect to our website, we will let you know if there's any work related to it. You can search for other issues/bugs and raise an issue accordingly. Thank you for raising the issue.
- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
