### ISSUE TITLE
[BUG] Inconsistent Styling of Card Elements Across Website

### ISSUE THREAD

**Issue by Hamza20203064** [mdazfar2/Ezyshop#9]
### Description

There is an inconsistency in the styling of the card elements throughout the website. Each card has different dimensions, padding, font size, or other styling properties, leading to a visually disjointed user experience.

### Screenshots

![Screenshot 2024-10-01 203401](https://github.com/user-attachments/assets/e2ca6689-e73c-49ad-99fa-baecabf4d344)
![Screenshot 2024-10-01 203342](https://github.com/user-attachments/assets/89f3750b-9506-4954-8332-bded08a542c0)
![Screenshot 2024-10-01 203325](https://github.com/user-attachments/assets/0edd09a6-fe4a-4cd4-8c71-cc8b3a342110)
![Screenshot 2024-10-01 203302](https://github.com/user-attachments/assets/5e6d0852-b9f0-41e2-8e47-bf074a26a42f)

### Any additional information?

**Expected Behavior:** All card elements should have a consistent look and feel across the website.

**Actual Behavior:** Card elements vary in size, spacing, and font across different pages.
**If you assigned this issue to me under GSSoC'24 extd. I would love to work on that.**

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Hamza20203064 go ahead

**Comment by Hamza20203064** [comment]
thanks brother...............

**Comment by rohitsharma2610** [comment]
hey, i have experience in front-end development and i can solve this issue so can you assign me for this issue?

**Comment by mdazfar2** [comment]
hey @Hamza20203064 I hope you are doing well!

- It has been 2 days and you haven't responded to anything. Unfortunately, I have to close this issue because there are many duplicate issues raised. Please don't be discouraged. Thank you.

**Comment by Hamza20203064** [comment]
@mdazfar2 I think this issue is not yet resolved. If you give me permission to work on it, I can submit a pull request in the morning.

**Comment by mdazfar2** [comment]
Sure @Hamza20203064 thanks for letting me know.
