### ISSUE TITLE
[BUG] "Shop Now" button does not navigate to category items

### ISSUE THREAD

**Issue by Chitrakadyan2005** [mdazfar2/Ezyshop#902]
### Description

Clicking the "Shop Now" button on a category does not redirect users to the list of items in that category. Instead, the button is  unresponsive , preventing users from browsing and selecting items.

### Screenshots

https://github.com/user-attachments/assets/f258b2ab-92c4-4620-a5e8-ec2f53debb24

### Any additional information?

Expected Behavior: When a user clicks on the "Shop Now" button for a category, they should be redirected to a page displaying all items available in that specific category, allowing them to choose and purchase products.

Actual Behavior: Clicking the "Shop Now" button does not take users to the category page. It results in no action, which hinders the shopping experience.

please assign it to me under GSSOC'24EXTD, hacktoberfest'24 and level labels.
@mdazfar2 

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by jainritikaa** [comment]
Hi, I'd like to work on this issue. It seems like the "Shop Now" button is not properly triggering a redirection to the category items page. I will investigate whether the button is missing an event listener or if there's an issue with the routing logic. I'll ensure the button becomes responsive and properly navigates users to the correct item list.

Please assign this to me, and I'll start working on it right away!

**Comment by mdazfar2** [comment]
@Mrigank118 @Chitrakadyan2005 @jainritikaa

You guys are really appreciated for showing interest in working on our project. It really means a lot to me.

Actually, we are working on that button, which is connected to the Seller dashboard. We are currently working on the backend of the Seller dashboard and will complete it soon, making the button visible. For now, I am closing this issue. Please don’t be discouraged. **Thank you!**

- Please give a Star ⭐ to our [repository](https://github.com/mdazfar2/Ezyshop)
- Don't forget to follow us on [LinkedIn](https://www.linkedin.com/company/ezyshop)
