### ISSUE TITLE
[Feat] Bottom to up button 

### ISSUE THREAD

**Issue by devxMani** [mdazfar2/Ezyshop#904]
### Description

button

### Screenshots

![image](https://github.com/user-attachments/assets/28434003-c951-488a-bb7f-8df44b2ec057)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@devxMani go ahead, but make sure the color matches the website and also switches correctly between dark and light modes.

**Comment by sameer-soni** [comment]
@mdazfar2  this issue hasn't been solved yet, can i get assigned?
