### ISSUE TITLE
Adding 'What our user say' section

### ISSUE THREAD

**Issue by AswaniBolisetti** [mdazfar2/Ezyshop#905]
@mdazfar2 
I would like to work on it
Could you please assign it to me

**Comment by mdazfar2** [comment]
@AswaniBolisetti I don't exactly understand what you're trying to say. You described it in just two sentences, which doesn't clearly explain what you want to work on. Please don't do that.

You raised a blank issue. You should choose the appropriate issue template and describe it accordingly, as the chosen template will clarify what you want to work on. I will be happy to assign issues that are clearly understandable. Please keep this in mind—I'm not instructing you, just trying to show the correct roadmap for working on open source. Please don't be discouraged; I am closing this issue for now.
