### ISSUE TITLE
[Feat]: Site Map

### ISSUE THREAD

**Issue by paridhi1114** [mdazfar2/Ezyshop#907]
### Description

I want to add a site map feature to the website in order to enhance ease and accessibility for the user.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@paridhi1114 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
