### ISSUE TITLE
Add a Quick Scroll-Up Button for Enhanced User Experience.

### ISSUE THREAD

**Issue by smog-root** [mdazfar2/Ezyshop#909]
I suggest implementing a quick scroll-up button on the platform to improve navigation, especially for pages with long content. This feature would be highly beneficial for users by allowing them to return to the top of the page with a single click, reducing the need for extensive scrolling.

<br>

**Benefits:**

**Improved User Experience:** Users can easily navigate to the top of the page, making browsing smoother and faster.

**Accessibility:** Particularly helpful for mobile users and those with limited scrolling capability.

**Enhanced Usability:** Makes revisiting top-page content, such as navigation bars or menus, more convenient.

**Aesthetics:** It adds a professional touch to the user interface, making the site feel more intuitive.

<br>

**Feature Details:**

- A small button (typically in the bottom-right corner) that appears after the user scrolls down a certain distance.
- On click, the page scrolls smoothly to the top.

**_Note_**: kindly add level2 (or) level3 for this issue and assign me! @mdazfar2

**Comment by mdazfar2** [comment]
@smog-root You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
