### ISSUE TITLE
Adding a star rating system to the testimonial section

### ISSUE THREAD

**Issue by vararaghu002** [mdazfar2/Ezyshop#91]
### Screenshots

![Screenshot 2024-10-03 173242](https://github.com/user-attachments/assets/ad2bbfe3-8fa7-4132-87ed-c1d4ec5a4b7b)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@vararaghu002 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- please ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
