### ISSUE TITLE
[BUG] OTP Send Function Issue in NextAuth Signup

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#910]
#### Description:
The current implementation of the OTP send function during user signup is causing authentication issues. Specifically, when a new user signs up, the OTP function attempts to **update the `otp` field in the database**. However, this field does **not exist yet** for new users, leading to an error when NextAuth tries to update it.

#### Expected Behavior:
- On user signup, an empty `otp` field should be created in the database.
- This ensures that subsequent OTP updates can be made without errors.

#### Current Behavior:
- The `otp` field is not initialized during signup.
- NextAuth fails when trying to update the non-existent `otp` field, causing authentication errors.

#### Steps to Reproduce:
1. Register a new user through the signup process.
2. NextAuth attempts to send an OTP for authentication.
3. Observe the error indicating that the `otp` field is missing.

#### Suggested Fix:
Modify the signup logic to **initialize the `otp` field as an empty string ("")** for new users.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by A7Lavinraj** [comment]
can i work on it? well i am trying to grab a issue but sometimes someone already take it or it get closed, so please grant me permission to fix it

**Comment by mdazfar2** [comment]
Sorry @A7Lavinraj, please don't be discouraged, but this issue is already assigned to someone. Only one person can work on a single issue at a time. You can raise another issue, and I will be happy to assign it to you, but make sure that the issue you raise is valid and really needs to be addressed on our website; otherwise, invalid issues will be closed. **Thank you!**
