### ISSUE TITLE
[Feat] Feature for sellers to add a billboard and it should reflect on shops page

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#911]
#### Description:
We need to implement a feature allowing sellers to **add a cover picture to their shop** through their dashboard. This cover picture will be displayed on their shop profile page and also on the **shops listing page** of the website.

#### Requirements:
1. **Cover picture upload functionality** on the seller’s dashboard.
2. **Display the cover picture** on:
   - Shop profile page.
   - Shops listing page.
3. **Database schema modification** to store the cover picture URL or binary data.
4. **Frontend changes** to:
   - Include a file upload input for the seller's dashboard.
   - Display the cover picture on relevant pages.
5. **Backend API endpoint** to handle the upload, storage, and update of the cover picture.

#### Steps to Implement:
1. **Modify the database schema** to store the cover picture field.
2. **Add file input** to the seller's dashboard for uploading a cover picture.
3. **Create a backend endpoint** to update the cover picture.
4. **Update the frontend** to display the cover picture on the shop profile and listing pages.

#### Environment:
- **Frontend:** React, Next.js 14.2.14
- **Backend:** Node.js, Express.js, Prisma
- **Database:** MongoDB

---

Please let me know if any further clarifications are required.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays you are assigned.
