### ISSUE TITLE
Enhance Contact Us

### ISSUE THREAD

**Issue by Bhum-ika** [mdazfar2/Ezyshop#912]
I would like to make the better UI
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by mdazfar2** [comment]
@Bhum-ika, you are assigned, but I noticed that you raised the issue using a blank issue template. This time, I'll assign the issue, but next time, please use the issue template as it provides clarification and helps other contributors understand why you are being assigned. Hope you understand. I'm not instructing you, just showing the correct way to work on open source.

_Thank you!_
