### ISSUE TITLE
[Feat] Enhance Our facilities section 

### ISSUE THREAD

**Issue by SumaLatha2023** [mdazfar2/Ezyshop#915]
### Description

The current "Our Facilities" section on the website lacks interactive hover effects and could benefit from improved styling to make it more visually engaging. This issue focuses on adding hover animations, improving the styling for better readability and a modern look.

Benefits:
-Improved user engagement and interactivity.
-Enhanced readability and emphasis on key features.
-A more professional and modern UI that aligns with user expectations.

### Screenshots

![Screenshot 2024-10-23 230659](https://github.com/user-attachments/assets/ac4e7313-e26a-4054-9fa6-68b0d5f2e4fa)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @SumaLatha2023, as we are not decided to add any hover effect to our website, we will let you know if there's any work related to it. You can search for other issues/bugs and raise an issue accordingly. Thank you for raising the issue.
- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
