### ISSUE TITLE
[Feat]  Implement Dynamic Loading of Blog Pages Based on Blog Card Selection

### ISSUE THREAD

**Issue by kavya410004** [mdazfar2/Ezyshop#916]
### Description

Currently, there are two types of blog-related pages:

- **Blog Grid Page:** Displays blog posts in a grid format, with each post represented as a card.
- **Blog Page:** Displays the full content of a particular blog.

The Blog Grid page is displaying the cards correctly, but when clicking the "Read More" button on any blog card, it does not load the corresponding blog's full content. Instead, the same static blog page is displayed, regardless of which card is selected.
### Proposed Solution:
- Fetch the blog data from the database, where the data consists of blog with its title, images, sub sections, content etc.
- Update the logic to make the Blog Page load dynamically based on the selected blog card.
- When the "Read More" button of a blog card is clicked, the Blog Page should display the content of the corresponding blog by accessing the data from the array.
- Ensure that each blog's unique information is passed correctly from the Blog Grid page to the Blog Page, allowing it to render the correct content dynamically.
### Expected Outcome:
- Each blog card should redirect to a blog page that displays the full content of the selected blog post.
- The blog's title, images, and content should be loaded dynamically based on the card selection, using data from database.

### Screenshots

Blog Grid Page:
![image](https://github.com/user-attachments/assets/d9a80270-ef8e-4e3a-825d-2d3b71566273)

Same blog page displayed for every blog card:
![image](https://github.com/user-attachments/assets/ee96a20f-e474-4f84-bcee-f9cd765f2d1d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@kavya410004 Issue acknowledged! You are going to be assigned.

**Comment by ShivanshPlays** [comment]
@kavya410004 I have a request, kindly make the components of detailed blog page reusable and dynamic so the they can be used with backend fetched data in the future.

**Comment by kavya410004** [comment]
> @kavya410004 I have a request, kindly make the components of detailed blog page reusable and dynamic so the they can be used with backend fetched data in the future.

Sure

**Comment by kavya410004** [comment]
> Hey @kavya410004, can you do that? You need to fetch the blog details from the database, as the database is working fine on the Vercel deployment. It would be great if you could handle fetching the data from the database. _Thank you!_

Yes, for that I need to create a schema for blog in the database and add entries to it. Shall I raise a new issue to implement that and fetch the details to blog grid?

**Comment by mdazfar2** [comment]
Sure @kavya410004.
