### ISSUE TITLE
[Feat] Product Search Bar Feature

### ISSUE THREAD

**Issue by MasirJafri1** [mdazfar2/Ezyshop#92]
## Description
I want to contribute a responsive **Product Search Bar** feature for the product category section of the project. The search functionality will easily search and filter products based on their titles and descriptions.

![image](https://github.com/user-attachments/assets/b29b2f3b-c270-4602-a5c2-6adadaecc55e)

### Screenshots

https://github.com/user-attachments/assets/77918e44-3a04-4cc3-b324-91fc77afa39a

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@MasirJafri1 now, correct the grammatical error in the following below sentence and give me the correct ones, provide only the correct sentence without any arguments:

- please ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
