### ISSUE TITLE
[Feature] : Design Categories Page for Seller

### ISSUE THREAD

**Issue by mehul-m-prajapati** [mdazfar2/Ezyshop#926]
### Description

- Current Page is just rending table data by fetching the same from db.
- We need to add selection of pre-defined categories : Beauty Products, Gadgets, House Hold etc.
- Improve UI/UX of this page

#### Current Design
![p2](https://github.com/user-attachments/assets/9824bc49-d143-4d6a-98e7-a1a88c85ecdd)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Omvinchhi** [comment]
Can i try it ?
