### ISSUE TITLE
Improvement of CSS portion

### ISSUE THREAD

**Issue by noobremon** [mdazfar2/Ezyshop#930]
### Description

I would like to improve the css portion of the website and also add some pages
Also the live deployment link is not working I want to fix it too

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by noobremon** [comment]
Please assign this to me @mdazfar2

**Comment by mdazfar2** [comment]
Hey @noobremon, firstly, we don't use any CSS file. Can you please describe in detail where and exactly what place you want to improve? You just raised the issue and described it in two sentences, which doesn't provide enough context. I can't understand the issue based on a two-line description that doesn't make sense. You must explain it properly so I can understand and assign the issue to you.

- Please don't do this again.
