### ISSUE TITLE
[Feat] Product Reviews and Ratings

### ISSUE THREAD

**Issue by snehas-05** [mdazfar2/Ezyshop#932]
### Description

 I propose adding a Product Reviews and Ratings section beneath each product on the EzyShopz platform. This feature would allow users to provide feedback by leaving a rating (out of 5 stars) and a written review for the products they purchase. It will help future customers make informed decisions based on real user experiences and increase overall engagement on the site.

Feature Details:

Star Rating System:
Users will be able to rate products with a 1–5 star system. The average rating will be displayed under the product title, calculated dynamically based on all user reviews.

User Reviews:
Along with the rating, users can submit a written review detailing their experience with the product.
Reviews will include the user's name (or anonymous), their rating, and the date of submission.

Display:
The reviews will be displayed in a list under each product, sorted by date or rating (highest to lowest).
The average star rating and total number of reviews will be displayed prominently.

Review Submission:
A "Write a Review" button will allow users to submit their feedback.
If a user has already submitted a review, they can edit or delete their review.

This feature would build trust among users, enhance the shopping experience, and increase product transparency.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@snehas-05 customer reviews is not suitable for now. It would be great if the website is fully functional, then we can add this feature. Thank you.
