### ISSUE TITLE
[BUG] add feedback form to know user experience

### ISSUE THREAD

**Issue by SandhyaBadwaik** [mdazfar2/Ezyshop#941]
### Description

issue: can add the feedback form to know the overall experience of the user after shopping from this platform.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@SandhyaBadwaik As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
