### ISSUE TITLE
[Feat] : Improvising the UI of the OUR FACILITIES section 

### ISSUE THREAD

**Issue by AADESHak007** [mdazfar2/Ezyshop#944]
### Description

I would like to improve the UI of the boxes under the FACILITIES section  .
one possible way could be adding hover effects that do not stand out too much .
I personally want to add transition upon color change .
Please assign this issue to me and have a look at the changes . If  you have any problem I would be happy to work again on it .

### Screenshots

![Screenshot 2024-10-24 210546](https://github.com/user-attachments/assets/b07302e0-7c8f-47ee-b7fe-fbcafa1b41c6)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @AADESHak007, as we are not decided to add any hover effect to our website, we will let you know if there's any work related to it. You can search for other issues/bugs and raise an issue accordingly. Thank you for raising the issue.
- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.
