### ISSUE TITLE
[Feat]:Cookie Policy Pop up and Sign up Pop

### ISSUE THREAD

**Issue by jjf2009** [mdazfar2/Ezyshop#947]
### Description

Add a popup asking users to sign up and a cookie policy popup 

### Screenshots

Examples
![Screenshot 2024-10-24 194557](https://github.com/user-attachments/assets/9e38b1b2-317b-4837-9d0e-e4279e33023f)
![Screenshot 2024-10-24 194456](https://github.com/user-attachments/assets/13bb117a-b693-4a0a-aa93-d20ba0ed12f2)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@jjf2009 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
