### ISSUE TITLE
wishlist count 

### ISSUE THREAD

**Issue by RahulPrasadYadav** [mdazfar2/Ezyshop#951]
### Description

in wishlist page .. count item how many  in wishlist

exmple ==  wishlist item (2) like this 

### Screenshots

![Screenshot (409)](https://github.com/user-attachments/assets/a7859917-e6be-4e92-9ecf-51ea04fb18bb)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@RahulPrasadYadav As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
