### ISSUE TITLE
[Feat]: Integrate Auto-Generating Blogs using Gemini AI for EzyShop

### ISSUE THREAD

**Issue by Titus210** [mdazfar2/Ezyshop#952]
### Description:
Enhance the EzyShop platform by integrating an auto-generating blog feature powered by Gemini AI. This feature will automatically generate relevant blog posts related to local shopping trends, product highlights, and seasonal promotions, providing valuable content to users and improving SEO for the platform.

### Objectives:

- Integrate Gemini AI to generate blog content related to local shopping.
- Automate blog post creation based on predefined topics or categories.
- Schedule blog posts to be published at regular intervals to keep content fresh and engaging.
- Enable user customization to allow specific interests to influence the type of content generated.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Titus210, that's a nice idea. Can you please tell me how you fetch images and which language you use for GeminiAI integration? I think it should be Python, right? If not, please tell me how it is possible, and one more thing, can we use GPT or any other platform instead of Gemini?

**Comment by Titus210** [comment]
> Hey @Titus210, that's a nice idea. Can you please tell me how you fetch images and which language you use for GeminiAI integration? I think it should be Python, right? If not, please tell me how it is possible, and one more thing, can we use GPT or any other platform instead of Gemini?
> 
> Kindly share examples where it has been implemented, or share images or a demo video of your previous work.

Gemini API uses Vertex AI, which can automatically generate content with Gemini and images using DALL·E 3. Here is an example of a [project](https://www.youtube.com/watch?v=AUKcdiv5HuY&t=6s) that demonstrates how we can automatically generate content using Gemini and DALL·E 3 from Google AI Studio. Yes, we will be using Python for the implementation. Gemini will be used for text content generation, which can also be substituted with any other text-generating model such as GPT; however, for images, the DALL·E 3 API is the most effective option in this context.
