### ISSUE TITLE
no scroll up button at landing page 

### ISSUE THREAD

**Issue by 2004pra** [mdazfar2/Ezyshop#953]
allow me to add the scroll up button with some major changes in css and javascript 
please assign me this issue under gssso extd24 , hactober fest , please make it atleast level 2 sir please ....
@mdazfar2

**Comment by mdazfar2** [comment]
@2004pra You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
