### ISSUE TITLE
Enhance footer with social Media links

### ISSUE THREAD

**Issue by alo7lika** [mdazfar2/Ezyshop#957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The documentation update aims to enhance the website's footer by including social media links for improved connectivity and user engagement. Adding links to relevant social media profiles will allow users to easily connect with the project or organization on platforms like Twitter, LinkedIn, GitHub, and Facebook. This enhancement can help in building a stronger community, improving visibility, and providing users with additional channels to stay updated on project news, releases, and events.

The update will also include best practices for implementing social media links, such as using recognizable icons, ensuring accessibility, and maintaining a consistent design. This addition will make it easier for users to find and follow social media channels, fostering a more connected user base.

### Suggested Change

The proposed documentation update focuses on enhancing the website footer by integrating social media links to improve user connectivity and engagement. This change will include adding easily recognizable icons for platforms like Twitter, LinkedIn, GitHub, and Facebook, each linking directly to the corresponding social media profiles. To ensure accessibility, each icon will feature descriptive alt text, allowing screen readers to identify the links accurately. The design of the icons will align with the website's current color scheme and aesthetic, providing a cohesive look while drawing attention to the new feature. This update aims to create a more connected user experience by offering multiple channels for users to stay informed and engaged with project news, updates, and events.

### Rationale

N/A

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@alo7likaI think the UI of the footer is good according to our website. Please raise any other issue that is really needed for our website. As of now, I am closing this issue. Please don't be discouraged, I really appreciate your enthusiasm in open source. Keep going! ***Thank you!***
