### ISSUE TITLE
[Feat]: Implement Return Policy Page

### ISSUE THREAD

**Issue by RachitSahu26** [mdazfar2/Ezyshop#958]
### Description

The current shopping project lacks a dedicated page for the Return Policy, which is crucial for informing users about the terms and conditions related to returns and exchanges. To enhance user trust and satisfaction, I propose adding a comprehensive Return Policy page.

Proposed Features:
Detailed Return Policy: Clearly outline the terms for returning products, including the time frame within which returns are accepted, condition requirements, and any exceptions.
Exchange Process: Explain the process for exchanging items, including how users can initiate exchanges and any associated costs or conditions.
Refund Information: Provide details on how refunds are processed, including time frames for refunds and the methods used for returning funds.

### Screenshots

https://github.com/user-attachments/assets/66766dd1-ef4c-4490-9550-e5664f4a6805

 I wanna add like this 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@RachitSahu26 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
