### ISSUE TITLE
[BUG] "Login/Signup Button Not Functioning Properly on Frontend"

### ISSUE THREAD

**Issue by amanver45** [mdazfar2/Ezyshop#96]
### Description

The login/signup button on the frontend is not functioning as expected. When clicked, there is no response or redirection to the appropriate login or signup page. This prevents users from accessing their accounts or creating new ones.

Steps to Reproduce:

1. Navigate to the homepage.
2. Click on the "Login" or "Signup" button.

Expected Behavior:Users should be redirected to the login/signup page or a modal should appear for entering credentials.

Current Behavior:Nothing happens upon clicking the button.

Proposed Solution: I would like to add the functionality to the login button, ensuring users can access the login/signup feature. T

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@amanver45 everything working fine. Please check again and raise an issue accordingly, which I’ll be happy to assign to you. Thank you!

- please ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
