### ISSUE TITLE
[Feat]Feedback_form_could_be_attached

### ISSUE THREAD

**Issue by piyahub** [mdazfar2/Ezyshop#960]
### Description

Providing a feedback form could help in customizing the website and also to know what the customers like and what they don't.
It could be a really good way to know what changes are actually needed and which ones are beneficial.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@piyahub As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
