### ISSUE TITLE
Adding feature forgot password in the login page 

### ISSUE THREAD

**Issue by akruti123-hub** [mdazfar2/Ezyshop#961]
Add the Link: Below the form, include a link labeled "Forgot Password?" that directs users to a password recovery page. This link can be created using an anchor tag (<a>) that points to the relevant URL.

Please assign me for this task.

**Comment by mdazfar2** [comment]
@akruti123-hub As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
