### ISSUE TITLE
[Feat] Adding a "Back to Top" Button

### ISSUE THREAD

**Issue by oathar** [mdazfar2/Ezyshop#962]
### Description

Dear maintainers @Kavita1928 , @thakuratul2 , @mdazfar2  I want to add a "Back to Top" button which enhances website usability by providing a convenient way for users to quickly return to the top of the page. Upon clicking it, the page smoothly scrolls back to the top. This feature is implemented using HTML for the button, CSS for styling, and JavaScript for functionality. It improves navigation, especially on longer web pages, making for a more user-friendly experience. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by oathar** [comment]
@Kavita1928  , @thakuratul2  , @mdazfar2  . Please assign this to  me.

**Comment by mdazfar2** [comment]
@oathar You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)
