### ISSUE TITLE
[Feat] Addition of SearchBar and Sort By Feature for the Categories Page

### ISSUE THREAD

**Issue by Shariq2003** [mdazfar2/Ezyshop#963]
### Description

I want to add search and sort by functionality in the categories page

### Screenshots

![image](https://github.com/user-attachments/assets/6bd52e0b-01cb-4924-8e6c-0ee10a925a00)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Shariq2003 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
