### ISSUE TITLE
Read More buttons display identical content on all blog cards.

### ISSUE THREAD

**Issue by msv6264** [mdazfar2/Ezyshop#967]
### Description

When clicking on the "Read More" button for any of the three blog cards, each card opens the same content, specifically titled "10 Ways to Save on Groceries This Month." This issue causes all blog cards to display the same heading and content regardless of which card is clicked.

Expected Behavior: Each "Read More" button should display unique content corresponding to its specific card.

Actual Behavior: All "Read More" buttons link to the same article, "10 Ways to Save on Groceries This Month," and display identical content.

### Screenshots

![Screenshot 2024-10-25 230739](https://github.com/user-attachments/assets/247355db-00eb-4ca8-98a8-abb28bf5d65c)
![Screenshot 2024-10-25 230751](https://github.com/user-attachments/assets/8550523d-b7f5-4058-a2a0-a0493fc803da)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [x] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@msv6264 You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)



- Don't forget to give a star to our [repository](https://github.com/mdazfar2/ezyshop). 🌟

- Follow us on [LinkedIn](https://linkedin.com/company/Ezyshopz).

- Join our official [Discord](https://discord.gg/YnABU7tdU3) server where we can easily talk about how to enhance our project even better.


**Thank you!**
