### ISSUE TITLE
## CSS Fix: "Opening Hours" Section in Contact Page

### ISSUE THREAD

**Issue by sanikamandale17** [mdazfar2/Ezyshop#97]
### Description
The "Opening Hours" section in the Contact Page needs a CSS update to ensure proper spacing and alignment between the icon and text.

### Problem
The alignment and spacing between the clock icon and the text are inconsistent compared to other sections like "Address", "Email", and "Phone". This results in a visually unbalanced layout.

### Expected Behavior
The "Opening Hours" section should follow the same formatting as other contact details, with:
- Proper alignment of icons and text.
- Consistent spacing between elements.
- Better visual hierarchy for readability.

### Current Behavior
Currently, the text overlaps slightly with the icon, and the "Our platform is available 24/7" text appears too close to the heading, making it visually cluttered.

### Proposed Solution
The following CSS modifications are recommended to fix the layout:

### Screenshots

![image](https://github.com/user-attachments/assets/20b29d9c-1519-4390-90e6-143f691b21a5)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@sanikamandale17 everything looks good. Please check again and raise an issue accordingly, which I’ll be happy to assign to you. Thank you!

![{7FE86BA8-BF97-4FFE-B424-44F354E2E7B3}](https://github.com/user-attachments/assets/1294026f-6807-484c-ad73-f3ba9bac9173)


- please ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
