### ISSUE TITLE
Add button in sign up and login page ..google facbook and X

### ISSUE THREAD

**Issue by RahulPrasadYadav** [mdazfar2/Ezyshop#970]
### Description

onvenience: Users can log in without creating and remembering a new username and password. This reduces friction and makes logging in easier.

Faster Onboarding: With social sign-ins, users can quickly register with a few clicks, reducing the amount of information they need to provide (name, email, etc.) since it can be fetched from the social profile.

ncreased Sign-Up Conversions: The easier it is to sign up, the more likely users are to complete the registration. Social logins tend to boost conversion rates by reducing the barrier to entry.

Accurate Data Collection: By using social profiles, businesses can collect accurate, up-to-date data (like verified emails and names) which can improve user profiling and personalization efforts.

Reduced Password Management: With social logins, there’s less risk of users forgetting passwords and contacting support, which reduces customer service costs.

### Screenshots

![Screenshot (428)](https://github.com/user-attachments/assets/748a98c7-0f0d-4f39-b013-862a3678b17e)
![Screenshot (429)](https://github.com/user-attachments/assets/247bee2c-ee0d-4891-9486-77e58a2ed992)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @RahulPrasadYadav, that's a good suggestion, but have you noticed that major e-commerce websites mainly use phone number verification with SMS OTP? This is not feasible for us because it's a paid service, which is why we use email OTP verification for easy login and signup. I hope you understand why we’re not implementing this feature.
