### ISSUE TITLE
[Feat] Add a fully responsive and designed contributors page 

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#971]
### Description

I will design and a a fully responsive and designed contributors page to the website and attach a link in the footer for the same.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @ShivanshPlays, yes, we are considering adding a contributor page, and we already have a page on the navbar called `/Team`. When you click on `/Team`, you'll see the prompt for it. Actually, I want to update the contributor section on the team page to make it look more special, so I need some time for that. I will let you know if there are any updates for the team page. _Thank you!_

**Comment by mdazfar2** [comment]
@ShivanshPlays, do one thing: add a dropdown on the `team` navbar and a button for Contributor. After clicking on Contributor, the contributor page should appear and fetch contributor data from GitHub. Design a good contributor page that looks professional.

Leave the team navbar as it is, and a popup should appear after clicking on the team.

- Hope you understand. Ask if you have any questions.
