### ISSUE TITLE
[BUG] 🐞 Bug Report:

### ISSUE THREAD

**Issue by aanushkaguptaa** [mdazfar2/Ezyshop#978]
### Description

Summary: The My Orders, Wish List, and Cart options should be accessible only after a user has logged in. Currently, these options are visible to all users, including those who are not logged in, which could lead to confusion. Implementing authentication/authorization for these options and placing them under a dropdown menu after login can create a more seamless experience.

1. Authentication & Authorization: The My Orders, Wish List, and Cart options should only be visible to logged-in users. These options could be placed in a dropdown menu under the user profile for better navigation and user experience.

Expected Behavior:
- When logged out, users should not see the My Orders, Wish List, and Cart options.
- After logging in, these options should be accessible and displayed in a dropdown under the profile menu.

Actual Behavior:
- The options for My Orders, Wish List, and Cart are visible to all users, regardless of their login status.

Proposed Solution:
_1. Implement authentication/authorization checks for these sections._

### Screenshots

![image](https://github.com/user-attachments/assets/e9b10cd4-5370-4b4c-a45e-4ee3168c3058)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @aanushkaguptaa, that's an amazing idea. Actually, don't hide these options; just add an alert message so that when a user clicks on My order, wishlist, or my cart without logging in, a popup alert message will appear saying, "Please login as a Customer first."

When a user logs in as a seller, the dashboard will be fully changed, and that's already implemented. You only need to work on the customer login. When a customer logs in, they should be able to see all three options. Without logging in, a popup will appear. I hope you understand what I mean. Please let me know if you can do this.

- Don't forget to give a star to our [repository](https://github.com/mdazfar2/ezyshop). 🌟

- Follow us on [LinkedIn](https://linkedin.com/company/Ezyshopz).


***Thank you!***

**Comment by mdazfar2** [comment]
Hey @aanushkaguptaa, that's an amazing idea. Actually, don't hide these options; just add an alert message so that when a user clicks on `My order`, `wishlist`, or `my cart` without logging in, a popup alert message will appear saying, --> `Please login as a Customer first`

When a user logs in as a seller, the dashboard will be fully changed, and that's already implemented. You only need to work on the customer login. When a customer logs in, they should be able to see all three options. Without logging in, a popup will appear. I hope you understand what I mean. Please let me know if you can do this.

- Don't forget to give a star to our [repository](https://github.com/mdazfar2/ezyshop). 🌟

- Follow us on [LinkedIn](https://linkedin.com/company/Ezyshopz).


***Thank you!***

**Comment by aanushkaguptaa** [comment]
Hi @mdazfar2 ,

Thank you for the feedback! I now have a clear understanding of the changes you’d like. Instead of hiding the My Orders, Wish List, and Cart options, I’ll implement a popup alert prompting users to log in when they attempt to access these sections without being logged in as a customer. I'll make sure that all three options will become accessible once the user is logged in, and will work only on the customer login flow as the seller dashboard is already handled.

If everything looks good, could you please accept my issue request and assign me to this task? It would be great if you could also add the relevant labels. Looking forward to getting started!

Thanks again!

**Comment by mdazfar2** [comment]
@aanushkaguptaa You are going to be assigned.

- Read our [Contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md) and contribute accordingly.

- Don't forget to give 🌟 to our repository.

- Follow us on [LinkedIn](https://linkedin.com/company/Ezyshopz).


***Thank you!***

**Comment by mdazfar2** [comment]
Hey @aanushkaguptaa, how are you? Is everything fine? It’s been a week, and you haven’t responded. Do you still want to work on this issue, or should I assign it to someone else? Please let me know if I should give this opportunity to others.

Try to reply within 2 hours; otherwise, you’ll be unassigned, and the issue will be assigned to someone else.

***Thank you!***

**Comment by priyanshuverma-dev** [comment]
Hi @mdazfar2 
I am interested to work on this issue

**Comment by mdazfar2** [comment]
@priyanshuverma-dev, did you read all the replies for a better understanding? If not, please read all of my replies and Anushka's replies, and then let me know.

**Comment by priyanshuverma-dev** [comment]
I have understood the context that i need to implement a pop up toaster when user tries to access My order, wishlist, or my cart without logging in. And normal when logged in.


@mdazfar2

**Comment by mdazfar2** [comment]
@priyanshuverma-dev We have two dashboards: one for sellers and another for customers. For sellers, we have a different dashboard and navbar, while for customers, the navbar and dashboard are the same as shown in the navbar. Please make sure to understand the codebase, and I've assigned this issue to you.



Make sure to read the [Contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md) and contribute accordingly.

**Comment by aanushkaguptaa** [comment]
> Hey @aanushkaguptaa, how are you? Is everything fine? It’s been a week, and you haven’t responded. Do you still want to work on this issue, or should I assign it to someone else? Please let me know if I should give this opportunity to others.
> 
> Try to reply within 2 hours; otherwise, you’ll be unassigned, and the issue will be assigned to someone else.
> 
> _**Thank you!**_

Hi

I mailed you on October 27 regarding some issues I encountered while getting started, hoping for your guidance before proceeding. I understand you've now reassigned the issue, and that's perfectly fine.

If any other tasks come up where I could contribute, please feel free to let me know.

Best,
Anushka

**Comment by mdazfar2** [comment]
> Hi

> I mailed you on October 27 regarding some issues I encountered while getting started, hoping for your guidance before proceeding. I understand you've now reassigned the issue, and that's perfectly fine.

> If any other tasks come up where I could contribute, please feel free to let me know.


@aanushkaguptaa, I haven't received any email, and I’m actively checking my inbox. You mentioned that you emailed me on October 27th, but I haven’t received anything on my end. Please double-check; you may have accidentally sent it to someone else. See the screenshot below for proof that I haven't received any email from you.

<br>

![image](https://github.com/user-attachments/assets/f9e3288c-cc02-456e-a277-7a3cb8141e08)

<br>

If you encounter any issue next time and need to reach me, feel free to ping me on  [Discord](https://discordapp.com/users/877531143610708028) or [LinkedIn](https://linkedin.com/in/md-azfar-alam/).

**Comment by aanushkaguptaa** [comment]
> > Hi
> 
> > I mailed you on October 27 regarding some issues I encountered while getting started, hoping for your guidance before proceeding. I understand you've now reassigned the issue, and that's perfectly fine.
> 
> > If any other tasks come up where I could contribute, please feel free to let me know.
> 
> @aanushkaguptaa, I haven't received any email, and I’m actively checking my inbox. You mentioned that you emailed me on October 27th, but I haven’t received anything on my end. Please double-check; you may have accidentally sent it to someone else. See the screenshot below for proof that I haven't received any email from you.
> 
> 
> ![image](https://private-user-images.githubusercontent.com/100375390/382315420-f9e3288c-cc02-456e-a277-7a3cb8141e08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0Nzc5ODUsIm5iZiI6MTczMDQ3NzY4NSwicGF0aCI6Ii8xMDAzNzUzOTAvMzgyMzE1NDIwLWY5ZTMyODhjLWNjMDItNDU2ZS1hMjc3LTdhM2NiODE0MWUwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxNjE0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTEyZTAwNjEzOTFkNmJiOGUxODA1YTEyNGJlN2FkMGYwY2VkNGFhNTExNjUwY2QzZDUxNWQ2N2M5MzIwZThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VWt6K-C8fZtHlx6tCkANRcs0MrgrOBNli91R6mRD_LE)
> 
> 
> If you encounter any issue next time and need to reach me, feel free to ping me on [Discord](https://discordapp.com/users/877531143610708028) or [LinkedIn](https://linkedin.com/in/md-azfar-alam/).

Must be some technical error then! 
![image](https://github.com/user-attachments/assets/233a308e-33f0-41e3-b4d2-a2249379e665)
I'll reach out to you through telegram or discord next time, of I raise a PR request/or am assigned

**Comment by mdazfar2** [comment]
> Must be some technical error then! ![image](https://private-user-images.githubusercontent.com/106096425/382337429-233a308e-33f0-41e3-b4d2-a2249379e665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NzkxMDMsIm5iZiI6MTczMDQ3ODgwMywicGF0aCI6Ii8xMDYwOTY0MjUvMzgyMzM3NDI5LTIzM2EzMDhlLTMzZjAtNDFlMy1iNGQyLWEyMjQ5Mzc5ZTY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxNjMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmQzZGIxOGE0NDQzOTQ3NmQzZWY5NzE1N2M4ZDY4MjRkOGExNzdlMWNkNjAyNmM3MzJmZTUyMTE5ZWU4OTRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.C_rM11I_cygdMzzSgk6KMKNeHaVFQpZYJTgpA32dNr0) I'll reach out to you through telegram or discord next time, of I raise a PR request/or am assigned


<br>

Hey @aanushkaguptaa, the email you sent wasn’t to the correct address. Check out my GitHub profile for my contact details, and connect accordingly. My email is: azfaralam.ops@gmail.com.
