### ISSUE TITLE
UPDATION IN README.MD FILE REQUIRED 

### ISSUE THREAD

**Issue by soham0028** [mdazfar2/Ezyshop#981]
Hello @mdazfar2 
the current readme file lacks proper structure and does not contain : 
1. table of contents 
2. featured in section 
3. forkers and stargazers section 
4. back to top button 

kindly assign me the issue under gssoc-extd labels so my work counts for these events

**Comment by mdazfar2** [comment]
@soham0028 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
