### ISSUE TITLE
Start Shopping button not working

### ISSUE THREAD

**Issue by 1ShahidBashir** [mdazfar2/Ezyshop#986]
@mdazfar2 start shopping button is not working
![image](https://github.com/user-attachments/assets/bcb2ba3f-3880-49d4-9ae3-18e1b50fe70a)

**Comment by 1ShahidBashir** [comment]
@mdazfar2 assign this issue to me we can work this 0ut

**Comment by mdazfar2** [comment]
@1ShahidBashir I don't exactly understand what you're trying to say. You described it in just one sentence, which doesn't clearly explain what you want to work on. Please don't do that.

You raised a blank issue. You should choose the appropriate issue template and describe it accordingly, as the chosen template will clarify what you want to work on. I will be happy to assign issues that are clearly understandable. Please keep this in mind—I'm not instructing you, just trying to show the correct roadmap for working on open source. Please don't be discouraged; I am closing this issue for now.
