### ISSUE TITLE
Add Table of Contents to README

### ISSUE THREAD

**Issue by T-Fathima** [mdazfar2/Ezyshop#987]
### Description

Currently, the README lacks a table of contents, making it challenging for users to navigate sections quickly. Adding a table of contents will enhance readability and allow users to locate information faster.

@mdazfar2 I would like to work on it.
Please assign it to me under gssoc-ext and hacktoberfest.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @T-Fathima, why do you keep raising the same issue again and again- again and again? I’m getting frustrated now. A few days back, you raised the same issue, and I closed it.

Our README.md file is good, and people can easily understand our project.

Here is proof of your previous issue where I closed it by saying something. Check this out 👇 https://github.com/mdazfar2/Ezyshop/issues/987
