### ISSUE TITLE
improving the Contact Us page 

### ISSUE THREAD

**Issue by anuza08** [mdazfar2/Ezyshop#99]
### Description

the page is not properly aligned. Details are repeated and not properly aligned 

### Screenshots

![{C3635B13-2354-4AE1-855A-3B0D9435DC31}](https://github.com/user-attachments/assets/14eb1066-6bbb-4267-8e41-7cc85d95f54f)

### What browser are you seeing the problem on?
Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@anuza08 everything looks good. Please check again and raise an issue accordingly, which I’ll be happy to assign to you. Thank you!

![image](https://github.com/user-attachments/assets/e55f00bc-625c-4115-9bb1-9fe1bd982247)


- please ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
