### ISSUE TITLE
[Feat] Add dynamic product fetching and summary to cart page and option of moving a product to cart from wishlist.

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#993]
### Description

# Issue: Dynamic Product Fetching, Cart Summary, and Wishlist-to-Cart Functionality

## Description

This issue involves enhancing the **cart page** by adding the following features:

1. **Dynamic Product Fetching:**  
   - Fetch products dynamically from the database based on the products added to the user's cart.
   - Ensure that any updates to product details (e.g., price changes) are reflected in real-time on the cart page.

2. **Cart Summary:**  
   - Display a **summary section** on the cart page with:
     - Total number of items in the cart.
     - Aggregate cost of all items (with and without discounts).
     - Any applied **coupon or discount codes**.
   - Handle edge cases (e.g., empty cart) by showing appropriate messages or UI elements.

3. **Move to Cart from Wishlist:**  
   - Provide an **option to move products from the wishlist to the cart** directly on the wishlist page.
   - Ensure:
     - The product is removed from the wishlist upon successful addition to the cart.
     - User feedback through **toast notifications** for both success and error cases.
     - Prevent duplicate entries in the cart by checking if the product is already present.

4. **State Management & Performance Optimization:**  
   - Use **state management** to ensure the cart page updates dynamically when products are added, removed, or moved from the wishlist.
   - Avoid redundant API or database calls by maintaining a **client-side state** that syncs with the server efficiently.

---

## Tasks

1. **Backend:**
   - Add new API endpoints or modify existing ones for:
     - Fetching cart products dynamically based on user session.
     - Moving products from the wishlist to the cart.
     - Ensuring product data stays up-to-date.

2. **Frontend:**
   - Implement a **cart summary section** that displays item count, total cost, and discounts.
   - Add functionality to **move products from the wishlist to the cart**, ensuring smooth transitions with proper state handling.
   - Update UI/UX to reflect changes dynamically without requiring a page reload.

3. **Testing:**
   - Test the flow of moving items from the wishlist to the cart.
   - Ensure the cart summary is updated correctly after adding or removing products.
   - Validate all edge cases, such as empty cart or duplicate entries.

---

## Expected Outcome

- **Improved Cart Page** with real-time product data and a detailed summary section.
- **Seamless Wishlist-to-Cart Transfer** functionality with clear user feedback.
- **Optimized State Management** to ensure minimal server calls and improved performance.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays Great issue found. You are going to be assigned.
