### ISSUE TITLE
[BUG]  Optimize Image Loading with Compression and Lazy Loading

### ISSUE THREAD

**Issue by madhumitha-b** [mdazfar2/Ezyshop#999]
### Optimize Image Loading with Compression and Lazy Loading

**Description:**
Currently, the images on the platform may not be optimized for performance. This can lead to slower load times and a suboptimal user experience, especially on slower networks. To improve this, we should implement image compression and lazy loading techniques.

**Proposed Solution:**
1. **Image Compression:**
   - Compress all images to reduce their file size without significant loss of quality.
   - Use tools like `imagemin` or similar for automated compression during the build process.

2. **Lazy Loading:**
   - Implement lazy loading for images to ensure that images are only loaded when they enter the viewport.
   - Use the `loading="lazy"` attribute for images or a JavaScript library like `lazysizes`.

**Benefits:**
- **Faster Load Times:** Reduces the initial page load time by loading images only when necessary.
- **Improved Performance:** Enhances the overall performance of the website, especially for users on slower networks.
- **Better User Experience:** Provides a smoother and faster browsing experience for users.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Hamza1821, this is a very good feature, but it does not look good on our website. According to our website's design, a simpler effect and feature will look more attractive. So, as of now, I don’t think this issue is necessary for our website. Please work on any other issue that is needed and raise issues accordingly. ***Thank you!***
